### ISSUE TITLE
There seems to be an error in the Vaadin Combo Box

### ISSUE THREAD

**Issue by corbettcode** [vaadin/vaadin-combo-box#1005]
Found the error below in Chrome...Vaadin 14.5.1

BTW, your 'Please submit an issue..." URL is incorrect.

VM95 44176bf4-7a9a-11eb-b64a-6d92f208f1a0:2 There seems to be an error in the Vaadin Combo Box:
Cannot read property 'overlay' of undefined
Please submit an issue to https://github.com/vaadin/vaadin-combo-box-flow/issues/new!
(anonymous) @ VM95 44176bf4-7a9a-11eb-b64a-6d92f208f1a0:2
Promise.then (async)
(anonymous) @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2047
(anonymous) @ VM95 44176bf4-7a9a-11eb-b64a-6d92f208f1a0:2
initLazy @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2047
eval @ VM893:3
eval @ VM893:3
hu @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1028
gu @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:982
eu @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:593
Mr @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:501
js @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
QB @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:951
Or @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1032
ds @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
tk @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:432
Gr @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1033
Hr @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1014
Wt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
uC @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
(anonymous) @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:606
sb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:440
vb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:897
(anonymous) @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:627
XMLHttpRequest.send (async)
sC @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:945
rC @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:574
Ot @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:966
ps @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:988
ms @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:957
rs @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:922
Ft @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:576
Jt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
Nt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
Ob @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:981
Hb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:693
Sb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
Mb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:209
sb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:440
vb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:897
(anonymous) @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:627
d @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:717
setTimeout (async)
Pb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:718
Jb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:727
po @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:597
Gt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:721
vt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:526
yt @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:905
Cv @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
(anonymous) @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:995
sb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:440
vb @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:897
(anonymous) @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:627
(anonymous) @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2053
(anonymous) @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2053
(anonymous) @ VM95 44176bf4-7a9a-11eb-b64a-6d92f208f1a0:2
(anonymous) @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2053
(anonymous) @ VM95 44176bf4-7a9a-11eb-b64a-6d92f208f1a0:2
M @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
A @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
x @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
_propertiesChanged @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
Dx.s._propertiesChanged @ client-FCEED70EEBF39D99A31584E81D10B720.cache.js:1037
_flushProperties @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:1107
_flushProperties @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
_invalidateProperties @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
_setProperty @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:848
Object.defineProperty.set @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:1107
_activateItem @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2053
_onClick @ vaadin-bundle-aa7ae81a6adda2ec3418.cache.js:2053

**Comment by yuriy-fix** [comment]
Dear @corbettcode ,

Can I kindly ask you to follow the issue template available in the repository? You will be able to access it when submitting an issue.

At least could you please share a project/application where the issue can be reproduced to get into the context of the issue?

**Comment by vlukashov** [comment]
Thanks for reporting an issue! And sorry for the wrong URL 🙈 

In order for the Vaadin team to investigate and fix the issue with ComboBox we need to be able to reproduce it. And that requires a list of sepcific steps, like:

#### Steps to reproduce
1. create a new project with Vaadin **version** using https://start.vaadin.com
2. ...
3. ...
4. see the error

Could you please share the steps to reproduce with us?
That would be much appreciated, and also would increase the chances of getting this issues fixed.
