### ISSUE TITLE
Highlight matches in the filtered list

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-combo-box#106]
Add a means to control HOW the filtered list is rendered.

ie: in our app, we want to highlight portions of the matched items as to better show WHERE the matches occur in each item.

**Comment by Saulis** [comment]
Hi @ktiedt, highlighting matches when filtering is actually something that we've been designing.

@jounik could share some more info if it's going to be a separate feature or a part of #51.

Here's one of our design mockups: 
![image](https://cloud.githubusercontent.com/assets/1039468/12443036/8d96b838-bf5d-11e5-9a49-7002cb880d36.png)

As for the API, we've also had some plans on providing support for custom filtering at some point.

**Comment by ktiedt** [comment]
Oh great, @Saulis that does definitely sound like it could cover things... after looking at #51 I might suggest 2 distinctions. A combobox historically (to my knowledge) allows for custom input values, but provides a default list of options. One that does not, to my knowledge has generally been called a filtering select (selects have a defined list of valid options, and you can reduce them by beginning to type your selection).

**Comment by jounik** [comment]
@ktiedt right, that’s the definition we’ve been using more or less. Previously there was just some confusion if there was some technical or API issue regarding custom values, hence the explicit issue regarding it.

For the filtering highlighting, it’s not really part of #51, the mockups just contain initial visual design for it also. As the title says, it relates more to custom item renderers.

**Comment by ktiedt** [comment]
@jounik as long as its on the table somewhere (mockups are promising) :)

**Comment by ktiedt** [comment]
Anymore thought gone into this? If there is and it can be published, happy to work towards it, going to need this very shortly.

**Comment by jounik** [comment]
Not much progress with this unfortunately.

I was thinking that this might somehow be related to custom item templates, but perhaps it is actually a totally separate feature that you acn easily toggle on or off.

I was initially thinking that window.find might be used for this, but it seem overkill, and simple innerHTML.indexOf traversal/manipulation might do the trick. I just don’t know how it will work together with the iron-list templates.

**Comment by ktiedt** [comment]
Yeah, I had similar concerns, I may ping the Polymer team to see if they have done any similar effects on any of their sites yet maybe.

**Comment by jounik** [comment]
And just to be clear, this feature is not coming to 1.0, as we’re already in beta with it (meaning feature additions/removals). But it’s one of the top things we consider for 1.1.

**Comment by Saulis** [comment]
As a workaround, with combo-box `1.3.0` and item templates, you can make a highlighter element yourself: https://gist.github.com/Saulis/48229751ba472e949b75eedc3d84de5b

**Comment by flyweight** [comment]
@Saulis With your example https://gist.github.com/Saulis/48229751ba472e949b75eedc3d84de5b say I include several `vaadin-combo-box` elements on the same page using the `regex-highlighter` component.  The `filter="{{filter}}"` attribute and data binding is shared between the `vaadin-combo-box`, causing them all to rerun the regex match.  Without renaming them (some are dynamically created in a dom-repeat template), is it possible to get `filter` to just the regex highlighter without it being shared elsewhere?  Thanks for the help.

**Comment by Saulis** [comment]
Hi @flyweight, as the `filter` can only be exposed as a parent property, it can't currently be used in your use case in other ways than renaming the property for each instance.

To enable your use case properly, we would need to expose the `filter` property inside the item template – which we probably will during the implementation of this feature, but I recommend filiing a separate feature request for exposing the `filter` in the template if you want to see it happening faster :-)

As a workaround, something like this might work: https://jsfiddle.net/Saulis/qx16t1y4/ – basically listening to `filter-changed` event and mapping each filter separately for each combo-box instance inside the `dom-repeat`. Hope it helps!

**Comment by tomivirkki** [comment]
Closing. The items can nowadays be customized with a `renderer` function. We have no plans to provide built-in match highlighting.
