### ISSUE TITLE
Make API consistent with paper-input

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/vaadin-combo-box#107]
Currently some of paper-input-container API properties (for example, noLabelFloat and alwaysFloatLabel) are missing in vaadin-combo-box API.

**Comment by jounik** [comment]
We are considering the option that you could wrap any input element with vaadin-combo-box, so that we could avoid duplicating any attributes.

**Comment by Saulis** [comment]
See #198 for customising input element. Current plan is to avoid coupling combo-box API with `paper-input`

**Comment by jouni** [comment]
@fluorumlabs, we’ve started designing and prototyping #198 more closely, so now would be a great time to start giving more feedback how it’s going to look like. Check out the comments in that issue and let’s continue the discussion there. Thanks!

**Comment by Saulis** [comment]
Fixed in #254
