### ISSUE TITLE
Add items property

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#12]
- Support primitive types only at this point
- Put a `iron-list` inside `iron-selector`
- `vaadin-combo-box` should expose `items`
- Push, Pop, Empty, Update and other array related mutations need to be tested

**Comment by patriciapds** [comment]
Any plans to support objects?

**Comment by Saulis** [comment]
Hi @patriciapds!

If you mean using objects as values instead of string literals, that's already supported: https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-combo-box/demo/objects.html

**Comment by web-padawan** [comment]
@patriciapds I think `items` could support iterables in the future, once Polymer implements that for `dom-repeat`, `iron-list` etc. Is it what you mean?
