### ISSUE TITLE
Overlay is not closed on blur if focus is moved to document.body

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#122]
Overlay doesn't close if focus is moved to for example browser toolbar, which makes `document.activeElement` getting changed to `document.body`

**Comment by Saulis** [comment]
Had to revert this in 29c2a1e due to regressions which made the input blur close the overlay when clicking on items and toggle button. 

Work continues in #132

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
