### ISSUE TITLE
Unnecessary functions in the public api

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-combo-box#125]
"clear" and "toggle" functions in the component's public API feel a bit out-of-place. Should be made private.

combobox.clear(); is currently just a short for combobox.value = '';

combobox.toggle() is something you'd rather expect in the API of a component with two states such as a checkbox or dropdown

**Comment by platosha** [comment]
Don't we have two states in combobox? And a dropdown?

As for me, combobox.toggle() is a handy method for making an external label-like element, which should toggle combobox dropdown on click.

**Comment by tomivirkki** [comment]
There's already open() and close() for that. No reason to bloat our APIs with handy utilities.
Combobox doesn't have 2 states, a dropdown inside it does.

Take a look at paper-dropdown-menu API for example

**Comment by Saulis** [comment]
Fixed in #134
