### ISSUE TITLE
Disabled and read-only

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#141]
Add a disabled and read-only properties (like in paper-input).

The dropdown should not be openable and the dropdown toggle and clear input buttons should be hidden when either property is set.

**Comment by jermsv1** [comment]
I just submitted a pull-request, but i implemented it for the normal combobox here: https://github.com/jermsv1/vaadin-combo-box/commit/adeb7f65b4ad89e78f8a6da1cede262760d6f62f
