### ISSUE TITLE
Feature backlog

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#148]
Moved from https://github.com/vaadin/vaadin-core-elements/issues/8
### 1.0
- [Input + button for opening and closing a display (dropdown menu or fullscreen popup) of static items](https://github.com/vaadin/vaadin-combo-box/issues/5)
  - Touch support
- [User can select an item from the static list and the item is displayed as the value of the input](https://github.com/vaadin/vaadin-combo-box/issues/10)
- [The value of the input is sent as a part of an HTTP request when vaadin-combo-box is used inside a form element](https://github.com/vaadin/vaadin-combo-box/issues/11)
- [Dynamic list of items (0–9999 items, not lazy loading)](https://github.com/vaadin/vaadin-combo-box/issues/12)
  - Supports primitive types only
- [Default filtering "contains"](https://github.com/vaadin/vaadin-combo-box/issues/17)
  - Move filtering outside the items property
- [Keyboard navigation](https://github.com/vaadin/vaadin-combo-box/issues/16)
  - Left/right arrow keys not working the the input (in the prototype)
  - Allow the user to empty the field
- [Enable Scrolling](https://github.com/vaadin/vaadin-combo-box/issues/22)
- Test suite
  - Unit tests for each feature
- [Documentation](https://github.com/vaadin/components-team-tasks/issues/28)
- Default Material Design styling
- Issues in the prototype
  - [Dropdown menu positioning and sizing (open above the field when not enough space underneath in the viewport, never grow the dropdown bigger than the viewport etc.)](https://github.com/vaadin/vaadin-combo-box/issues/21)
  - [Dropdown menu positioning on iOS](https://github.com/vaadin/vaadin-combo-box/issues/22)
- [Basic accessibility support (ARIA roles)](https://github.com/vaadin/vaadin-combo-box/issues/34)
  - Utilize [a11ySuite.js](https://github.com/Polymer/web-component-tester/blob/94b201ae9cfc394c20352ba88837d3ebde3c1302/data/a11ySuite.js)
- [Custom input value support](https://github.com/vaadin/vaadin-combo-box/issues/51)
- [Support for object types](https://github.com/vaadin/vaadin-combo-box/issues/96)
- User testing, end users and developers
### 1.1
- Allow wrapping any "input" element? #198 
- Allow wrapping any "selector" element?
### Future
- Customizable filtering #259 
- Lazy loading of items
- [Customizable `<template>` support for list items](https://github.com/vaadin/vaadin-combo-box/issues/165)
  - Customizable `<template>` support for the selected item(s) in the input area
- Multi-selection (#88)
- Autocomplete/suggest feature
  - Is this just "no custom input allowed" + lazy loading?
  - Allow complex layouts and functionality inside the dropdown (implement OS X Spotlight for example)

**Comment by tomivirkki** [comment]
Issues corresponding to the topics listed in the "Future" list exist in backlog / are shipped already. Closing.
