### ISSUE TITLE
Separate display values and true values.

### ISSUE THREAD

**Issue by edgeeffect** [vaadin/vaadin-combo-box#159]
On an HTML combo box we have the option to have a computer-meaningful value and a human-meaningful value:
<select name="select">
<option value="1">Wolfie</option> 
<option value="2">Ken</option>
<option value="3">Tucker</option>
</select>
Vaadin-combo box is really lacking for not having this functionality. The human displayable value is of any use very rarely  and needing to look it's key up is just an annoyance.
This (what I would consider to be) normal behaviour is vital.

**Comment by Saulis** [comment]
Hi there!

Please have a look at #96, we're just around the corner on fixing this.

**Comment by edgeeffect** [comment]
Marvelous!
