### ISSUE TITLE
Improvement:autoopen="false" parameter

### ISSUE THREAD

**Issue by JesusSD** [vaadin/vaadin-combo-box#160]
When get focus I need a new parameter as autoopen="false"

**Comment by Saulis** [comment]
Hi!

Just to clarify: do you mean that the dropdown shouldn't open when the user clicks or taps on the input field? Because just focusing (with tab key) does not open the dropdown currently.

**Comment by JesusSD** [comment]
I want someone to tell the ComboBox that does not automatically open when the user click on any part and only opens when you click the "˅" icon to display the list.
So not part of the form is hidden, with the list.
Thank you.

**Comment by jounik** [comment]
I would like to hear a reason why you would want to prevent the dropdown from opening. Currently I feel there shouldn’t be a need to prevent it from opening.

As we see it, and have designed and implemented it, it provides the user with immediate access to the top of the list to see there are options to choose from. It helps mouse-only users, as it makes the click target much larger than only the arrow button.

**Comment by JesusSD** [comment]
In my application usually different values that appear on the list are entered, but the user can open the list to select to select a particular value.

**Comment by jounik** [comment]
So do you feel like the list will confuse the users in your use case?

Would you want the dropdown to never open when the user types in the field (no filtering and offering options)? So that the dropdown list would be a very secondary feature for the users, only when they don’t really know what to input they could open the list and choose an option.

**Comment by jounik** [comment]
Would be helpful to learn your use case more concretely, what type of values are the users typing/selecting and in what context. I guess I am questioning the need for this feature a little before I understand the need/use case better.

**Comment by JesusSD** [comment]
Example:
Open in Chrome: [http://triancal.esy.es/?p=12&t=6](http://triancal.esy.es/?p=12&t=6)
In this case the user usually introduce any value to the side "a". But in the event that user wants to set the maximum or minimum value will display the list.
![any or list](https://cloud.githubusercontent.com/assets/12623174/13222608/fce93a98-d980-11e5-88cb-eb1e0e8ea48a.JPG)

**Comment by jounik** [comment]
Thanks, that clears up the use case quite well.

It’s something we haven’t really considered, as we’ve mostly concentrated on the "filtered option list" use case more.

Your use case would also require limiting the allowed characters to numbers-only, right? Currently we don’t expose that from the contained `paper-input` element.

**Comment by web-padawan** [comment]
Closing in favor of #863 which is actually the same feature and now it is being implemented.
