### ISSUE TITLE
Improvement:label atribute in option tag

### ISSUE THREAD

**Issue by JesusSD** [vaadin/vaadin-combo-box#161]
I need a "label" attribute to the option tag look like as "datalist" in Chrome browser or "data-subtext" in Bootstrap.
![chrome label in datalist](https://cloud.githubusercontent.com/assets/12623174/13207199/dd169492-d90b-11e5-9b09-ae9fd3043bd1.jpg)

**Comment by Saulis** [comment]
Hi!

Template support in #148 should enable rendering the items like this. Can't say for sure if we can enable behaviour like this by default in #96

**Comment by jounik** [comment]
No plans on adding such formatting by default, but should be doable after we have the custom item template support.

**Comment by manolo** [comment]
Doable using templates
