### ISSUE TITLE
Combo box init with some value    is not  selected

### ISSUE THREAD

**Issue by tookit** [vaadin/vaadin-combo-box#168]
when I created a combo box like this

                <app-combo-box 
                  label="Select Group"  
                  items='[{ "id":"1","name":"admin" },{ "id":"2","name":"tech" }]'
                  id="group" 
                  name="group" 
                  value="1"
                  item-label-path="name" item-value-path="id">
                </app-combo-box>  

the "admin" item is not selected as I expect.

**Comment by Saulis** [comment]
Thanks for reporting this! We'll fix it asap.

**Comment by tookit** [comment]
Thanks for your reply.
I searched the code, and found that the observer '_valueChanged' is always executed first, then the "_setItems".

**Comment by tookit** [comment]
It seems that the string's observer is always executed first. So I thought maybe we can set another observer like this:
'init(items,value)'

this can make sure "items", "value" are both set.
so we can set the status in this observer  that can fix the issue.
