### ISSUE TITLE
Dropdown height limited by body height

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#169]
As `<vaadin-combo-box>` calculates the dropdown height and position with document's `body`, small body height shows a very small dropdown.
![combo-box-demo](https://cloud.githubusercontent.com/assets/8615573/13313357/f418a81e-dba5-11e5-9c58-418cd09a359d.PNG)

**Comment by jounik** [comment]
We should modify the behaviour so that if the bottom edge of the body is above the bottom edge of the viewport, the viewport edge should limit the dropdown height.

**Comment by Saulis** [comment]
@jounik then you get the problem with Safari and overscrolling, remember? :man_with_turban:
