### ISSUE TITLE
Infinite loop when a shared bound value is set to null

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#173]
This code fails when 'name' is undefined, see attached screenshot

```
 <vaadin-combo-box items="[[robots]]" value="{{name}}" label="Select a Robot"></vaadin-combo-box>

```
<img width="611" alt="screen shot 2016-02-27 at 22 51 17" src="https://cloud.githubusercontent.com/assets/161853/13375622/0de5327a-dda5-11e5-832c-a60afbfb0a69.png">

**Comment by Saulis** [comment]
Can't seem to be able to reproduce this either with `undefined` or `null` values. Could you provide a test case or a JSBin?

**Comment by Saulis** [comment]
For the record, here's the snippet used by manolo: https://gist.github.com/manolo/aa8afdbfc0a63d5a6982

Problem is actually the `paper-input` firing two `value-changed` events. If the `paper-input` and the `vaadin-combo-box` have their values bound to the same parent property, the extra `value-changed` event from the `paper-input` will always reset the value back to `null` and infinite loop is created.

See polymerelements/paper-input#66

**Comment by Saulis** [comment]
Thinking we need to either set the `value` asynchronously after all the events have been fired, or drop the whole feature of setting `value` to empty.

**Comment by Saulis** [comment]
As an additional information, the value check is originally added in #112 to prevent setting `undefined` as value, which can lead problems with computed properties: 
http://jsbin.com/niditu/edit?html,output - computed properties with more than one parameter don't get notified.

**Comment by manolo** [comment]
I might have some relation with #202
