### ISSUE TITLE
Unable to scroll all items fully visible

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#177]
Happens in all browsers.

![screen shot 2016-02-29 at 11 29 28](https://cloud.githubusercontent.com/assets/66382/13392063/b560b092-dee0-11e5-8433-79eb7a7628fb.png)

See the scrollbar going outside the bottom of the dropdown.

**Comment by Saulis** [comment]
As a fix, the `max-height` of the `#selector` needs to be decreased by the paddings applied to it (8 + 8px)

**Comment by jounik** [comment]
You can use calc for that.

**Comment by Saulis** [comment]
Might be related with #180
