### ISSUE TITLE
Intermittent uncaught TypeError when programmatically setting value

### ISSUE THREAD

**Issue by kriswillis** [vaadin/vaadin-combo-box#182]
We're using the vaadin-combo-box within one of our custom elements and we seem to be getting an uncaught TypeError intermittently when trying to set the selected value from within an observer…

    Uncaught TypeError: Cannot read property 'offsetHeight' of null

…which appears to be happening somewhere in iron-list ([line 944](https://github.com/PolymerElements/iron-list/blob/v1.0.3/iron-list.html#L944)).

This only seems to be happening after setting the value with something like: 

    this.$.combo.value = selection;

When thrown, the elements fails to render.

**Comment by Saulis** [comment]
Thanks for the report!

Would you be able to produce an isolated test case / JSBin where this occurs?

**Comment by Saulis** [comment]
Might be related with #128
