### ISSUE TITLE
Dropdown broken with Angular 2 (Firefox)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-combo-box#190]
Adding Angular 2 (beta8) dependencies to the same page with vaadin-combo-box breaks the combo box dropdown height on Firefox.

![screenshot 2016-03-17 09 38 17](https://cloud.githubusercontent.com/assets/1222264/13839549/7cf9062c-ec24-11e5-8eea-3fb725cc84aa.png)

**Comment by tehapo** [comment]
The reason seems to be the angular2-polyfills.js dependency (also beta9).

`<script src="https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js"></script>`

**Comment by jounik** [comment]
Related to #185

**Comment by tomivirkki** [comment]
The problem occurred with Angular 2 beta 8. With the newest beta the dropdown works fine. Closing..
