### ISSUE TITLE
Toggle button icon `menu` is confusing 

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#191]
Toggle button looks confusing when the `menu` icon is used for instance in drawer-panel, because `menu` has a different meaning.

It should be an arrow or be configurable, attached some screenshots

<img width="706" alt="screen shot 2016-03-17 at 23 47 13" src="https://cloud.githubusercontent.com/assets/161853/13863842/22822d12-ec9d-11e5-9cbd-8c9d9476235b.png">
<img width="703" alt="screen shot 2016-03-17 at 23 47 33" src="https://cloud.githubusercontent.com/assets/161853/13863841/22824522-ec9d-11e5-8f7e-e37673b3f5c4.png">

<img width="739" alt="screen shot 2016-03-17 at 23 49 29" src="https://cloud.githubusercontent.com/assets/161853/13863840/227f77d4-ec9d-11e5-8586-cb999cee2451.png">
<img width="747" alt="screen shot 2016-03-17 at 23 49 42" src="https://cloud.githubusercontent.com/assets/161853/13863839/227a72b6-ec9d-11e5-827a-cff43d072c84.png">

**Comment by jounik** [comment]
#196 will provide a way to change the icon.
