### ISSUE TITLE
Increase icon touch target area to 32x32px

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#197]

**Comment by jounik** [comment]
This relates a little to #156

**Comment by jounik** [comment]
Let’s quickly mockup this up and do a prototype implementation based on that. Probably that’s the final implementation as well.

**Comment by jounik** [comment]
40px touch touch are for both icon buttons feels like a lot, visually. 36px would be a little bit easier on the eyes, and not that awkward on desktop.
<img width="813" alt="screen shot 2016-04-12 at 09 02 06" src="https://cloud.githubusercontent.com/assets/66382/14451171/8acd8f8e-008d-11e6-9c0b-106163f565b5.png">

**Comment by jouni** [comment]
At the same time, make the clear button visible on touch devices as well.
