### ISSUE TITLE
combo-box loses focus when value selected (Win10/Chrome)

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#203]
![combo_enter](https://cloud.githubusercontent.com/assets/8615573/14108577/c0c33994-f5c6-11e5-8d0b-c395a0edff61.gif)

**Comment by Saulis** [comment]
This behaviour might be caused by @samiheikki touch enabled laptop – on touch devices we want to blur the input for close the virtual keyboard.

**Comment by manolo** [comment]
How can I reproduce this in a virtual box? or do I need touch enabled device?

**Comment by platosha** [comment]
I can reproduce in Chrome DevTools. Enable device mode, then in the device size bar menu set User Agent Type to Desktop with Touch.
