### ISSUE TITLE
Focus on element after click

### ISSUE THREAD

**Issue by JosefJezek** [vaadin/vaadin-combo-box#237]
I have issue with focus on the element after click with left button, right button is ok.

I have Chrome Version 50.0.2661.94 m on Windows 10 64b. I tested this issue in incognito window.

![nimbus-record-video](https://cloud.githubusercontent.com/assets/2110319/15114019/146181b8-15f8-11e6-91d3-bfca287b5544.gif)
First click is left button and second click is right button.

After remove `on-down="_preventDefault"` from `paper-input-container` element is focus ok after click left button.

https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box.html#L148

**Comment by jouni** [comment]
Hi! I don’t completely understand the issue?

The dropdown is supposed to open when you click the input, so the behavior is expected for the left button click. For right clicking, perhaps we should open the dropdown from that as well, but I’m not sure.

**Comment by JosefJezek** [comment]
I have the issue with loss focus after click for enable writing to input element.

**Comment by Saulis** [comment]
Tested on a Surface Pro running Chrome 50 and Windows 10, and combo-box does *not* focus on left click. Right click does focus. Tapping with a finger does focus. Firefox and Edge work normally also with a mouse.

On a Windows 10 VM and Chrome 50 mouse works normally, so to me it seems to be a touch device issue.

@JosefJezek do you happen to have a MS Surface or a laptop with a touch screen?

**Comment by JosefJezek** [comment]
@Saulis Yes, I have Dell notebook with touch screen.
