### ISSUE TITLE
Show clear button always when the field has a value

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#238]
Currently we require the user to focus the element before showing the clear button, mainly to keep the UI uncluttered. The common behaviour, on the other hand, is to show the clear button always when the field has a value.

**Comment by Saulis** [comment]
Some details required:

- Assuming the icon should be visible when hovering over the whole input field.
- Currently the icon is visible only when overlay is open – should the icon become visible on hover when the overlay is not open? When the overlay is open, should the icon be always visible or only when hovered over the input? 
- Should the icon be visible when hovering over the open overlay?
- What about touch devices which don't have hover?

**Comment by jouni** [comment]
> Assuming the icon should be visible when hovering over the whole input field.
Yes.

> Currently the icon is visible only when overlay is open – should the icon become visible on hover when the overlay is not open?
Yes.

> When the overlay is open, should the icon be always visible or only when hovered over the input?
Always visible when the overlay is open.


> Should the icon be visible when hovering over the open overlay?
Doesn’t make a difference because of the previous point.

> What about touch devices which don't have hover?
I think it should be always visible on touch devices. We improved the touch target sizes a while ago, so that shouldn’t be a big issue any more, but we should of course test that before shipping the change.
