### ISSUE TITLE
Pass 'no-label-float' to <paper-input-container>

### ISSUE THREAD

**Issue by depeele** [vaadin/vaadin-combo-box#247]
If the `<vaadin-combo-box>` component has a `no-label-float` attribute, pass it on to `<paper-input-container>`

I've submitted a pull-request that provides this functionality: #245

**Comment by jouni** [comment]
As mentioned in the PR, this will be handled by #198

**Comment by jouni** [comment]
@depeele, we’ve started designing and prototyping #198 more closely, so now would be agreat time to start giving more feedback how it’s going to look like. Check out the comments in that issue and let’s continue tye discussion there. Thanks!

**Comment by platosha** [comment]
Resolved by #254.
