### ISSUE TITLE
Dynamic data

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#26]
Two possible approaches:

## Use `<vaadin-grid>`
- Prototyping already done
- Supports multiple columns out of the box
- Supports  multi select, but probably needs some rework to be usable in a combobox?
- Smaller cache footprint (grid discards items out of the viewport)
- Supports lazy-loading out of the box
- Anything else?

## Use `<iron-list>`
- Has a templating model for custom rows (and multiple columns)
- Supports multi select
- Smaller in size and simpler
- Performs faster
- Implementing lazy loading should be straight forward (there are examples) 
- Anything else?

**Comment by Saulis** [comment]
@jounik We need your input on this. We did have a prototype using `<vaadin-grid>`, but we we're thinking if we should use `<iron-list>` instead? What do you think? At least a prototype?

**Comment by jounik** [comment]
Yeah, I’d like to try it out. Do you have any estimate how long it would take to build the lazy-loading on top of `iron-list`, to get it as solid as with the grid? The only things we would miss from the grid would be multiple column support (and headers/footers).

**Comment by Saulis** [comment]
I guess we can take some hints from the iron-lists demo: https://elements.polymer-project.org/elements/iron-list?view=demo:demo/collapse.html&active=iron-list (on my phone right now so cant see how the demo source looks like)

For multiple columns, isnt the template model in iron-list sufficient?

**Comment by jounik** [comment]
Full-blown columns is a little bit more than just some divs and CSS. But
it’s not something we need for 1.0.

And instead of spending time figuring out lazy loading, I would like us to
polish the component in all other ways before that. So all the other end
user features should be higher priority that these highly technical ones.

**Comment by Saulis** [comment]
Yeah, I guess the main motivation here was to try if `iron-list` would be a more light weight and smoother option also from the users perspective. I did a quick test run using `iron-list`, here's some observations:

- Was originally assuming that `firstVisibleIndex` in `<iron-list>` has `notify:true` and it could be used to trigger loading items. This was not the case, had to register a crude event listener to listen to `mousewheel` events instead and use an event handler to check the `firstVisibleIndex`
- Scroll bars show the height depending on the `items` property, and not the actual datasource size like in `<vaadin-grid>`
- The actual implementation was fairly easy, just using `firstVisibleIndex` to determine how many items we need to have loaded, then binding the needed item count parameter in `<iron-ajax>` and the hooking a `on-response` handler to append the new items to the `items` property of the `iron-list`

That said, considering the scroll bar issue and the way events need to be handled, it's probably better to go ahead with `<vaadin-grid>` at this point.

**Comment by Saulis** [comment]
Iron-list 1.2.0 introduces support for https://github.com/PolymerElements/iron-scroll-threshold which helps a lot in making a lazy loading implementation.

See also #128

**Comment by Saulis** [comment]
Closing the issue for now as it's not relevant currently.
