### ISSUE TITLE
Lazy loading of items

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#260]
A database might have hundreds of thousands of rows of items that should be displayed in the combo box. Rather than always sending all of the items to the client, it should be possible to load the items lazily.

The first "page" of items could be loaded when the user opens the dropdown (focuses the field or clicks the toggle button). After that, new items/pages would be loaded on demand when the users either scrolls the or filters the list.

There should be a visual indication to the end user when new items are being loaded (perhaps a spinner in place of the toggle button).

**Comment by Saulis** [comment]
Scope for the MVP: just add a feature for "remote data", so no paging. Everything is loaded at one go! :ship:

**Comment by jouni** [comment]
Related: #284

**Comment by manolo** [comment]
> Scope for the MVP: just add a feature for "remote data", so no paging. Everything is loaded at one go!

We don't need to do anything to cover this, just binding iron-ajax with combo-box on load or on open gives you all the items at `one go`.

To actually fix this issue, I think is almost unrelated with the filtering. Filtering could already have a couple of thousands of results. So it's a way to just display the items in the viewport. Is similar to a grid, so given a search criteria, and without changing it, the component should detect that need more items and ask the user for more pages somehow.

**Comment by Saulis** [comment]
See summary here: https://github.com/vaadin/components-team-tasks/issues/218#issuecomment-262237926
