### ISSUE TITLE
incorrect event name in documentation

### ISSUE THREAD

**Issue by joebordes** [vaadin/vaadin-combo-box#263]
On the "handle value" documentation page:

https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-value.html

you have this code:

```
<vaadin-combo-box on-value-change="valueChanged"></vaadin-combo-box>
```

I copied that and it didn't work until I changed the the event name to "on-value-changed"

```
<vaadin-combo-box on-value-changed="valueChanged"></vaadin-combo-box>
```

**Comment by tehapo** [comment]
Fixed, thanks for reporting! 👍
