### ISSUE TITLE
Add an autocapitalize property

### ISSUE THREAD

**Issue by kito99** [vaadin/vaadin-combo-box#265]
This would allow us to turn of the auto-capitalization capability (like paper-input). Another option would be to provide a CSS mix-in for the embedded paper-input.

**Comment by tomivirkki** [comment]
Hi @kito99,

We released `vaadin-combo-box` 1.1.0 last week with a new feature that allows you to define a custom input field for the element.

This issue can most likely be resolved by using a customized `paper-input` inside a `vaadin-combo-box-light` element.

Here's an example:
https://github.com/vaadin/vaadin-combo-box/blob/master/demo/custom-input.html#L91

**Comment by kito99** [comment]
@tomivirkki , thanks for the pointer. Clearly it'd be easier to just have an autocapitalize property (like the other paper components), but this could be a decent work-around.

**Comment by kito99** [comment]
Good point about customizablity.

I didn't realize you could already target the contained paper-input. Thanks! Is that in the documentation?

**Comment by tomivirkki** [comment]
There seems to be a brief [mention](https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L46) of it in vaadin-date-picker's apidocs but it's indeed missing from vaadin-combo-box's. Polymer has some [documentation](https://www.polymer-project.org/1.0/docs/devguide/styling) on CSS property inheritance in general but we should address this in our instructions on styling Vaadin Core Elements. Thanks.
