### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#266]
When selecting item from list, the following error is thrown (only the first time):
```
vaadin-combo-box-behavior.html:371 Uncaught TypeError: Cannot read property 'length' of undefined
```
You can see an example [here](https://saulis.github.io/iron-data-table/demo/filtering.html) - check "Custom Filter Input" demo.

Seems that `_inputElementValue` should have a default value (not undefined, maybe just empty string).
This seems not no occur when using `read-only` attribute.

**Comment by tomivirkki** [comment]
Hi @web-padawan 

Thanks for the report. Seems that the combo box can't handle undefined value & allow custom values combination. Fix is on the way.
