### ISSUE TITLE
angular tests make typescript fail in angular2-cli projects

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#269]
- create a new angular-cli project
- follow instructions for adding polymer components in angular2-polymer doc
- add vaadin-combo-box component with bower
- run `ng serve` and you get this error:
tmp/broccoli_type_script_compiler-input_base_path-9eeMSCsT.tmp/0/public/bower_components/vaadin-combo-box/test/angular2/main.ts (2, 51): Duplicate identifier 'enableProdMode'.

Probably we should not deliver components with tests ?

**Comment by tomivirkki** [comment]
Duplicate #267
