### ISSUE TITLE
Disable Keyboard on touch devices

### ISSUE THREAD

**Issue by pad90** [vaadin/vaadin-combo-box#274]
Is it possible to prevent the virtual keyboard from opening on touch devices ?

**Comment by Saulis** [comment]
There's no API for doing this, but you can try setting `combobox.$.input.readOnly = true;`

**Comment by pad90** [comment]
That prevents the virtual keyboard from opening but it disables the dropdown too

**Comment by Saulis** [comment]
@pad90 works just fine for me: http://jsbin.com/tigozofiya/edit?html,output

**Comment by pad90** [comment]
yes. this way its working. 
i tried
@Saulis 
`this.$.combobox.input.readOnly = true;`

and not

 `this.$.combobox.**$**.input.readOnly = true;`

for what is the second **'$'** ?

**Comment by Saulis** [comment]
@pad90 `$` is a shortcut for accessing elements by id inside the components local DOM. So in this case we're accessing an element with `id="input"` inside the `<vaadin-combo-box>`.

**Comment by pad90** [comment]
@Saulis ahh nice! thank you for explaining and helping!

**Comment by Saulis** [comment]
I'm going to close this issue now as it seems unlikely we're going to add a property for disabling keyboard only for touch devices due to how uncommon use case it is.

Please feel free reopen the issue if you think this is should be included or there is a more common use case I've missed.

**Comment by GTimpano** [comment]
Hi Saulis,

i have the same problem with a view webapp application that run on smartphone mobile..
and when i press Reclining tendon selection, the keyboard hide full screen and i'm not able to choose from combobox item list

i need to disable opening / appearance the keyboard in comboBox Vaadin component

it's possible to do?
how?

thanks

**Comment by Saulis** [comment]
Read the comments above ^^
