### ISSUE TITLE
Horizontal scrollbar appears when adding a combo box to a body without margin

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-combo-box#276]
```
<html>
<head>
<style>
html,body {
margin: 0;
}
</style>
<link rel="import"
href="http://polygit.org/vaadin-combo-box+vaadin+v1.1.1/polymer++v1.4.0/components/vaadin-combo-box/vaadin-combo-box.html">
</head>
<body>
<vaadin-combo-box id="rangeStart" label="Range start"
items="[0,10,20,30,40,50,60,70,80,90]"></vaadin-combo-box>
</body>
</html>
```

It is caused by the dropdown button ("toggleIcon") having position:absolute, right:-4px. This moves it outside the containing area.

Probably related to #228 / https://github.com/vaadin/vaadin-combo-box/pull/228/commits/d6e3edc4e6a6a8853d1989b0217e0fd53fd5bfb7

**Comment by jouni** [comment]
IMO the ise case of having the combo box 100% of the body is rare, and we would not need to accommodate that out of the box (as it affects the visuals of the element), when you can fix it with customization.

**Comment by tehapo** [comment]
The reported issue here might be a rare case, but this issue would still cause scrollbars in all places where the parent has `overflow: auto` (without any padding) and the `vaadin-date-picker` takes the full width.

I'm fine with abandoning the PR and having this as a feature, but somehow I feel like we should address this problem.

**Comment by tehapo** [comment]
Possibly also worth mentioning that the example code in this issue is missing the HTML5 doctype declaration. It does not affect this particular issue in any way, but sometimes causes weird behavior (as I noticed when trying the same test code with `vaadin-date-picker`).

**Comment by jouni** [comment]
Noted by @tomivirkki, that even if we remove the negative offset, the element will still overflow during the rotation animation (when opened). This could be fixed with 50% border-radius, but that will reduce the clickable target, so it’s a usability issue.

I’m proposing we close this as a wontfix (same for the date picker).

**Comment by tehapo** [comment]
Wontfix.
