### ISSUE TITLE
this._readied before firing 'selected-item-changed' - see plnkr

### ISSUE THREAD

**Issue by mbana** [vaadin/vaadin-combo-box#279]
It looks like the event is being fired from the component when the component is not ready.
Please see this example: http://plnkr.co/edit/0PnnbD?p=preview. Click on the button to see the all the captured ready states. They should all be **_true_**.
This is a problem since the component has yet to be initialized.

As an aside, the combox documentation could do with more examples, especially for the 'selected-item-changed', 'value-changed' and the rest of the events being fired as I found it to be a fiddly at times.

**Comment by Saulis** [comment]
Hi!

As `selectedItem` and `value` (the string representation of `selectedItem`) are kept in sync, `selected-item-changed` is being fired after the value from `comboVal` is bound to `value` property of the combo-box. 

This is done through Polymer's normal `notify: true` setting, so I'm afraid there isn't much we can do to either prevent the notification from happening or delaying it until all the properties have been set and the component is `ready`.

For the docs, have you checked out https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-value.html ?

**Comment by platosha** [comment]
Closing, since, as explained above, we can not do much about this.

As a workaround, you can use `change` event, which is dispatched only after the value was changed by a user.
