### ISSUE TITLE
this.inputElement is undefined throw

### ISSUE THREAD

**Issue by mediasoftpro** [vaadin/vaadin-combo-box#280]
While using vaadin-combo-box in my angular 2 project, some options not shown in first attempt, when review in firbug it throw error

TypeError: this.inputElement is undefined
if (!this.inputElement.focused) { ....

I tried my best to investigate why it happens but failed. can someone know why it causes. i am using firefox and chrome.

--
Screen of output (only display few items even there are more items in first attemp)

![issue01](https://cloud.githubusercontent.com/assets/1935364/17084414/78088440-51d6-11e6-8bcd-ad616dc5024c.png)

Next screen shows error in firebug.

![issue02](https://cloud.githubusercontent.com/assets/1935364/17084415/780f33e4-51d6-11e6-8c5f-87669abe9169.png)

**Comment by Saulis** [comment]
Hi!

Could you provide us with an isolated test case or an example app we could have a look at? 

Thanks!

**Comment by mediasoftpro** [comment]
Hi Saulis, i used it here

https://taskmanager-mediasoftpro.c9users.io/appv1/

Click on 'Enter something to add' text field. you will see combo boxes.

I just used example code mentioned on vaadin without making any changes.
