### ISSUE TITLE
Themes CSS

### ISSUE THREAD

**Issue by josepoma** [vaadin/vaadin-combo-box#286]
there are themes or css styles to change the appearance of the combo-box?

**Comment by tehapo** [comment]
The [styling options](https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-styling.html) for the default `vaadin-combo-box` are a bit limited. Of course some basic CSS styles can still be applied, like `width` and `background` for example.

You can however replace the input field with your own custom field, which opens up the option to completely customize the appearance. See the [documentation](https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-customization.html) for more details.
