### ISSUE TITLE
Scrolling the dropdown is broken on iOS

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-combo-box#288]
Scrolling the dropdown list of items is currently broken on iOS. See the attached screencast recorded on iOS Simulator.

![ios-scrolling-combo-box](https://cloud.githubusercontent.com/assets/368220/17505480/168a0438-5e0a-11e6-99c4-fe9f19307d7a.gif)

**Comment by tehapo** [comment]
Also affects focusing the field on touch devices. This issue was introduced in Polymer 1.6.0, when `preventDefault` was fixed for `down` events originating from touch.

See https://github.com/Polymer/polymer/pull/3693 for details.

**Comment by JesseShaw** [comment]
Verified broken on Android as well.
