### ISSUE TITLE
Angular2 rc5 reactive forms

### ISSUE THREAD

**Issue by unnamed666** [vaadin/vaadin-combo-box#290]
Hi, is it possible to use vaadin-combo-box with reactive forms from angular2 ?
i'am trying to use it like this ()

`<vaadin-combo-box label="Some label" [items]="types" ngDefaultControl formControlName="type"></vaadin-combo-box>`

and it works 50%
on init, proper value is selected, but value change is not working, as on submit i still have default value, any pointers how to fix it ? :)

**Comment by platosha** [comment]
It is an issue with the `@vaadin/angular2-polymer` package. The reactive forms support (aka, new forms API) is not yet implemented there.

But the good news are: we have the Angular 2 rc4-compatible implementation in this pull request: https://github.com/vaadin/angular2-polymer/pull/55. We are currently updating it to support rc5 as well. After the update it is going to be merged and released. Meanwhile, it would be helpful for us if you could try the [feature branch](https://github.com/vaadin/angular2-polymer/tree/feature/new-forms-api) and provide your feedback.

Closing this issue for now. Please see the PR to track the progress. If you’ll have any further issues with the Angular 2 forms support, please file them to the [vaadin/angular2-polymer repository](https://github.com/vaadin/angular2-polymer).
