### ISSUE TITLE
border-radius makes text fuzzy

### ISSUE THREAD

**Issue by ktiedt** [vaadin/vaadin-combo-box#299]
In vaadin-combo-box-overlay the `border-radius: 0 0 2px 2px;` causes text to appear blurry.

**Comment by tomivirkki** [comment]
Does this occur in some specific case/browser? Tried toggling the property on and off on desktop Chrome, Firefox and IE but couldn't notice any difference in text blurriness.

**Comment by ktiedt** [comment]
We never narrowed it down to a specific cause beyond this -- happened in desktop Chrome and possibly Firefox -- one of our team identified it in March and the bug just never made it back upstream.

**Comment by Saulis** [comment]
@ktiedt is this still an issue or OK to close?

**Comment by ktiedt** [comment]
I can re-test this, I wasnt aware I was holding this up still.

**Comment by ktiedt** [comment]
So, I don't see blurry myself... but there is definitely a difference. I'll get the original team member to re validate this as well to see if they see the same problem they previously saw.

no radius
![image](https://cloud.githubusercontent.com/assets/97242/19087332/7531bdc6-8a26-11e6-87f2-ee89f7d29a2f.png)

radius
![image](https://cloud.githubusercontent.com/assets/97242/19087395/a47e48d8-8a26-11e6-88cd-948ce7b99c1e.png)

**Comment by ktiedt** [comment]
And co-worker confirmed the above is exactly what they were seeing, as well. note: We are on a slightly older version v1.1.3 -- I didn't see anything else modifying the font for the overlays that may be relevant either.... I tried confirming on the demo page here but everytime the dev console takes focus, the comboboxes close which makes it difficult to verify :(

**Comment by manolo** [comment]
Removed border radius in version 3.0.x serie
