### ISSUE TITLE
Make vaadin-combo-box compatible angular2@rc6

### ISSUE THREAD

**Issue by sixrandanes** [vaadin/vaadin-combo-box#301]
Hello,

This element is not compatible with angular2@rc6.
In vaadin-combo-box.ts, we have (line 16)
`import { NgControl, NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/common';`
instead of
`import { NgControl, NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';`

Line 26, there is `new Provider() ` which is deprecated and removed from angular.
Use of `{provide:....}` instead.

In vaadin-combo-box/test/angular2/main.ts, the test use `bootstrap `  which is also deprecated.

Any help would be very helpul...

**Comment by platosha** [comment]
Hi! The Angular directives in the elements are deprecated. We don’t update them and they’re probably gonna be removed in one of the coming versions.

Please use the [@vaadin/angular2-polymer](https://github.com/vaadin/angular2-polymer) package to make the elements operate in Angular 2. The rc.6 support is coming soon there, see the PR: https://github.com/vaadin/angular2-polymer/pull/80.

**Comment by sixrandanes** [comment]
Thank you for your quick answer.

If the directive is deprecated and obsolete, why the source is still in the directory ?

I am currently using angular-cli and the files i downloaded from bower are in the directory bower_components. If i want my files to be served, I need to pu then inside src/*** directory.

The point is, if the files are in src, they also be take into account for typescript transpilation, and the directive is transpiled, but with errors cause the code is not updated anymore.

The workaround is find a way to exclude some file/directory from transpilation.

**Comment by platosha** [comment]
Good question. The reason was that removing a feature is a breaking API change, which is not acceptable for 1.x minor releases.

On the other hand, thanks to your issue report, now we have a good reason to do it. We should indeed consider removing the deprecated directives.

**Comment by niveo** [comment]
bower_components/vaadin-combo-box/directives/vaadin-combo-box.ts

this is a temporary solution.

import { NgControl, NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/common';
**change to**
import { NgControl, NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';


**Remove**

const VAADIN_DATE_PICKER_CONTROL_VALUE_ACCESSOR...

**Modify**

@Directive({
  selector: 'vaadin-combo-box',
  providers: [{provide:NG_VALUE_ACCESSOR, useExisting: forwardRef(() => VaadinComboBox), multi: true}]
})
