### ISSUE TITLE
[Angular-cli] The list of items is not displayed with internet explorer

### ISSUE THREAD

**Issue by Chabane** [vaadin/vaadin-combo-box#306]
Hi,

I added vaadin-combo-box on angular-cli application. The list of items is not displayed with internet explorer (IE11). It works fine with Chrome and Firefox.

```
 <vaadin-combo-box label="Select cat" [items]="catsList" item-label-path="race"
      (keyup)="getCatsList($event.target.value);" 
      (selected-item-changed)="selectCat($event.detail.value)" 
      item-value-path="race"
      [(value)]="item">
    </vaadin-combo-box>
```

Angular-cli : 1.0.0-beta.11-webpack.8
Angular : 2.0.0-rc.5 
Form : 0.3.0

**Comment by tehapo** [comment]
Thanks for reporting! We will look into this.

**Comment by jiveshrelhan** [comment]
Facing same issue ! +1

**Comment by tehapo** [comment]
Tried to reproduce the issue with no luck. The items were displayed on Chrome, Firefox and IE11 (running in VirtualBox).

Could you check if you see any error messages on the console of IE11?

**Comment by Chabane** [comment]
To populate the list, I used an asynchronous call. I tried many things with no success. Have you created a plunker to test it with my browser?

With a synchronous call, the list is displayed but on the bottom of the screen : 

![image](https://cloud.githubusercontent.com/assets/1231559/18587397/22dfce8a-7c22-11e6-8499-4ca6fa56590c.png)

**Comment by samiheikki** [comment]
I can verify that this is happening in IE11

**Comment by platosha** [comment]
Sorry to say, but we have discontinued the Angular support in our elements a while ago. Won’t fix this.

Closing for now. Feel free to reopen if it does occur outside Angular as well. Please provide a code snippet and/or steps to reproduce.
