### ISSUE TITLE
Not working with angular 2 Rc6 upgrade !

### ISSUE THREAD

**Issue by jiveshrelhan** [vaadin/vaadin-combo-box#308]
![error](https://cloud.githubusercontent.com/assets/8507036/18537557/121ad67a-7b24-11e6-9246-c49b6abbf93e.PNG)

- vaadin-combo-box/directives/vaadin-combo-box.ts (16, 10): ../path/node_modules/@angular/common/index"' has no exported member 'NgControl'.

- directives/vaadin-combo-box.ts

 (26, 53): Cannot find name 'Provider'

**Comment by tehapo** [comment]
The Angular 2 directives in `vaadin-combo-box` are deprecated and will be removed in the next release.

Please try out the [vaadin/angular2-polymer](https://github.com/vaadin/angular2-polymer) package as a replacement.
