### ISSUE TITLE
Can't select text with vaadin-combo-box-light

### ISSUE THREAD

**Issue by panuhorsmalahti** [vaadin/vaadin-combo-box#313]
Here's my template:
```
<vaadin-combo-box-light><paper-input></paper-input></vaadin-combo-box-light>
```

If I move the `paper-input` outside `vaadin-combo-box` I can select text with mouse. This issue occurs with vaadin-combo-box 1.1.2, 1.1.3 and 1.1.4. I can select text with the keyboard. In addition, when I click the text inside the input the cursor is always set to the end of the input for some reason.

The same issue occurs with iron-input:
```
<vaadin-combo-box-light><input is="iron-input"></input></vaadin-combo-box-light>
```

**Comment by tomivirkki** [comment]
It's a bug indeed. All down events are canceled in `<vaadin-combo-box-light>` currently. Sent a PR for fixing this.

As a workaround you could try the following with the current version:
`combobox.unlisten(combobox, 'down', '_preventDefault');`
