### ISSUE TITLE
Clicking the dropdown toggle of an open dropdown opens it again

### ISSUE THREAD

**Issue by panuhorsmalahti** [vaadin/vaadin-combo-box#320]
This only affects vaadin-combo-box-light, the bug doesn't exist in vaadin-combo-box. The issue affects at least vaadin-combo-box 1.1.4 and 1.1.5.

I've reproduced it on my own element and also using the example in the documentation:

```
            testItems: {
                type: Array,
                value: () => ["abc", "test2", "test3"]
            }

<vaadin-combo-box-light attr-for-value="value" items="[[ testItems ]]">
  <paper-input label="Elements" class="input">
    <iron-icon icon="toll" prefix></iron-icon>
    <paper-button suffix class="clear-button">Clear</paper-button>
    <paper-button suffix class="toggle-button">Toggle</paper-button>
  </paper-input>
</vaadin-combo-box-light>

```

What should happen:
After clicking the dropdown toggle, the dropdown should be closed

What actually happens:
After clicking the dropdown toggle the dropdown is closed and the opened. Both `vaadin-dropdown-closed` and `vaadin-dropdown-opened` are fired.

Note that if I press mouse down and move the cursor outside the input the dropdown doesn't open again.

Occurs on latest Firefox ja Chrome, not on IE.

**Comment by samiheikki** [comment]
This is a bug. Happens also in `vaadin-combo-box` with custom toggle-button #335

**Comment by platosha** [comment]
Seems to be working as expected, as of now.

Tried here: https://cdn.vaadin.com/vaadin-combo-box/2.0.0-alpha4/demo/advanced.html#replacing-the-input-with-a-paper-input-
