### ISSUE TITLE
(value-changed) is call 3 times

### ISSUE THREAD

**Issue by ybarbaria** [vaadin/vaadin-combo-box#330]
I am using your component combo-box with angular2.

`<vaadin-combo-box #cbClients label="Clients" [items]="clients" [(value)]="client"
                                          item-label-path="name"
                                          (value-changed)="onClientChanged(cbClients.selectedItem)"
                                          (contextmenu)="onContextMenuCbClient($event)"></vaadin-combo-box>`

My function "onClientChanged" is call 3 times, first time selectedItem is null, 2 and 3 time is set with my object. 
And after the last call the combo is empty. 

Do you know why? 

thx

**Comment by platosha** [comment]
Please try without binding for the `[(value)]`. Do you still get 3 calls then?

**Comment by platosha** [comment]
Sorry to say, but the Angular support was discontinued a while ago. Won’t fix this.

Note that you can also use the `change` event now, which is fired only for user changes.
