### ISSUE TITLE
Custom clear icon does not work

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#334]
Custom clear icon does not clear the combo-box input. Doesn't register `tap` event. (See the demo/advanced.html site)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/8615573/19717879/6f0bdeda-9b6b-11e6-898a-ba26344c11b2.gif)

**Comment by platosha** [comment]
Probably due to missing import of `<paper-icon-button>`.

**Comment by samiheikki** [comment]
@platosha import doesn't fix it
