### ISSUE TITLE
Custom toggle-button re-opens the dropdown

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#335]
Custom toggle button re-opens the dropdown when trying to close with it. (See the demo/advanced.html site)
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/8615573/19718013/15ce7ad4-9b6c-11e6-930c-0c680c233cc6.gif)

**Comment by platosha** [comment]
Seems to be working properly as of now.
