### ISSUE TITLE
Demos are broken in IE11

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#345]
### Description
*All* demos are broken in IE11. None of the combo-boxe's have any items as when the items array is set.

### Expected outcome
All demo combo-boxes have items.

### Actual outcome
None of them have items + errors in console (`'elements' is undefined`)

### Live Demo
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [X] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by panuhorsmalahti** [comment]
I can confirm this. However, the dropdown works in my actual project (although I'm using combo box light).

**Comment by web-padawan** [comment]
Same for me, demos are broken. Several errors: http://prnt.sc/enl6z5

**Comment by tomivirkki** [comment]
Works with the latest version of combo-box and demo helpers. Closing.
