### ISSUE TITLE
“Clear” button does not clear the visible input value when the internal value is empty

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#352]
When the internal value of the combo box is empty, pressing the “clear” button does not empty the visible input value:

![](http://g.recordit.co/EaBSOuRp6P.gif)

**Comment by Saulis** [comment]
Caused by https://github.com/vaadin/vaadin-combo-box/commit/1cc8d729a9e297f4868d678face7fa427fd66e61#diff-c4921ad82a63bbd7a5ccbfaa0cc4af19R423 not checking for empty strings.
