### ISSUE TITLE
the value of `errorMessage` is always visible

### ISSUE THREAD

**Issue by BartoszGalek** [vaadin/vaadin-combo-box#355]
### Description
the `errorMessage` (defined in a property) should not be visible when invalid=false on the `vaadin-combo-box` 

### Expected outcome
the `errorMessage` property should not be visible when the invalid property is not set (false)

### Actual outcome
the `errorMessage` is visible when the vaadin-combo-box invalid=false

### Live Demo
https://jsbin.com/duvaje/1/edit?html,output

### Steps to reproduce
1. Put a `vaadin-combo-box` element in the page.
2. Add an error-message to the vaadin-combo-box
3. Open the page in a web browser.
4. `vaadin-combo-box` error-message is visible even thou the `vaadin-combo-box` is not set to invalid.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Indeed, looks like `vaadin-combo-box` doesn't automatically import `paper-input-error`.

If you add `<link rel="import" href="paper-input/paper-input-error.html">` to your example it works as expected.

**Comment by tomivirkki** [comment]
Fix in https://github.com/vaadin/vaadin-combo-box/pull/356, thanks for reporting

**Comment by BartoszGalek** [comment]
happy to contribute 👍

**Comment by BartoszGalek** [comment]
I've seen the pr and the import is there. The issue can be closed once the #356 is merged
