### ISSUE TITLE
The event "custom-value-changed" is not fired when value is empty

### ISSUE THREAD

**Issue by lousley** [vaadin/vaadin-combo-box#357]
### Description
The vaadin-combobox does not fire event "custom-value-changed" when the value reset to empty

### Expected outcome
The event "custom-value-changed" must fire when value is reset to empty (by hand or by reset icon)

### Actual outcome
The event "custom-value-changed" is not fired

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by Saulis** [comment]
Hi!

This is by design: empty string is not considered to be a custom value.

You can listen to `value-changed` to detect when the value was cleared. 

If this doesn't work for you, please fill us in on your use case so we can understand it better! Thanks!

**Comment by platosha** [comment]
Closing due to no response. Please respond if this is still relevant.
