### ISSUE TITLE
Support object items which have the same string value representation

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#359]
When using objects, if `item-value-path` isn't mapped to a property of the object, setting `value` won't match any of the items in the `items`, which is OK.

However, setting `selectedItem`, results in `value` being set to `[Object object]` which in turn assigns `selectedItem`  with the first item from `items` (since `[Object object]` will match to all of the items).

The latter behaviour is of course pretty unexpected. Proposing adding a console warning when we detect that `selectedItem` doesn't have the property mapped in `item-value-path` - will save some time debugging.

**Comment by platosha** [comment]
This feels wrong in the implementation, that setting the `value` after `selectedItem` triggers assignment for the `selectedItem`. Preventing this kind of a reaction should probably resolve the issue.

**Comment by Saulis** [comment]
Discussed with @platosha:

As adding a console warning does not still support the use case, where user has actually set `item-value-path`, but has object which have same string value representations, we should instead make sure setting `value` does *not* change `selectedItem` if the value change was triggered by setting a `selectedItem`.

**Comment by Saulis** [comment]
Relates to #310

**Comment by fmaiolo** [comment]
I ran into this as well. There should really be a note in the docs that you MUST have a value field specified, even if you are just using the selected item
