### ISSUE TITLE
document keydown event listener should be added on dropdown open and cleaned on close

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-combo-box#36]
Currently, we add global document event listeners to prevent `<iron-dropdown>` scroll manager from eating the events when overlay is opened.

The listeners aren't cleaned up at all, which might cause issues if there are other elements trying to listen the events.

**Comment by Saulis** [comment]
As discussed with Tomi, `<vaadin-combo-box` effectively blocks currently all `left` and `right` `keydown` events on `document` globally.
