### ISSUE TITLE
Does not respect shift-right-click browser's context menu

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-combo-box#360]
### Description

There is an accessibility/usability function in browsers where shift right clicking will open the browser's context menu instead of the custom context menu.

For example, go to Google Drive/Docs/etc. and right click and you'll see the custom context menu, but if you shift right click, you'll see the browser's context menu.

![shift-right-click-example](https://cloud.githubusercontent.com/assets/4591840/21163333/57fd40ba-c147-11e6-93b1-6676ea1bb207.gif)

### Expected outcome
Browser's context menu should always come up when shift is held.

### Actual outcome
Only the vaadin-context-menu comes up.

### Live Demo
Any of the demos here:
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-context-menu/

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by Saulis** [comment]
This issue was moved to vaadin/vaadin-context-menu#47
