### ISSUE TITLE
Leaking input styles

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#361]
### Description
The `vaadin-combo-box` element styles affect globals scope when using bundling.
All my inputs have padding due to the following lines: 

```
    #input {
      box-sizing: border-box;
      padding-right: 28px;
    }
```

**Comment by platosha** [comment]
What tools are you using for bundling? It’s a local style of `<vaadin-combo-box>`, I wonder why the tooling does not scope it.

**Comment by tomivirkki** [comment]
It's probably due to `<style>` being defined outside `<template>` in https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box.html

**Comment by web-padawan** [comment]
I use `polymer-build`. AFAIK styles shouldn't live outside of  templates, this is the thing which may break globals styles somehow. Will send a PR to fix that.
