### ISSUE TITLE
[enhancement] Possible to use it as an autocomplete/typeahead text field?

### ISSUE THREAD

**Issue by flyweight** [vaadin/vaadin-combo-box#368]
Works really well for doing typeahead currently, however the field is cleared if it doesn't end up matching anything items.  Is it possible to avoid this behavior or is this an enhancement request?

**Comment by jouni** [comment]
Maybe you’re looking for the `allow-custom-valu` property? https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/#vaadin-combo-box:property-allowCustomValue

**Comment by flyweight** [comment]
Yes, perfect!  Thanks for pointing me in the right direction.
