### ISSUE TITLE
Software keyboard is not closed when scrolling the overlay when using a custom <paper-input> element

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#369]
Also, the software keyboard is not closed when a value is selected from the overlay list.

The screen recording first shows how the default, built-in paper-input works – the software keyboard is closed when you scroll the overlay, and after you choose an item from the overlay. Then, it shows how it works when using a custom paper-input:

<img src="https://cloud.githubusercontent.com/assets/66382/21848639/8e20e50a-d80a-11e6-9ce7-f4aa9cae6d97.gif" width="320px">

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
