### ISSUE TITLE
Hide internal elements and behaviors from the API docs

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#377]
![image](https://cloud.githubusercontent.com/assets/1039468/22195628/a68a96e0-e151-11e6-997b-cb99bf0855b5.png)

I think we should hide `<vaadin-combo-box-overlay>`, `<vaadin-combo-box-shared-styles>`, `<vaadin-combo-box-item>`, `<vaadin-spinner>`, `OverlayBehavior`

**Comment by tomivirkki** [comment]
Closing as a duplicate of https://github.com/vaadin/components-team-tasks/issues/266
