### ISSUE TITLE
Add example for paper-item in item templates

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#383]
`<paper-item>` is a ready-made item wrapper with material design look. It covers plenty of simple cases.

Since `<vaadin-combo-box>` is also material-like by default, pointing to`<paper-item>` in the examples could be helpful for the users.

**Comment by Saulis** [comment]
- Add the Jouni's super nice awesome paper-face-item example to code examples. (https://jsfiddle.net/18qLdegq/3/)
