### ISSUE TITLE
Illustrate the example code in live demos and docs

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#386]
When looking through the live demos, it is not immediately visible what item templates do. Users have to open the combo-boxes to see it.

This could be resolved by adding screenshots or keeping the combo-boxes open.

Asciidoc should also have screenshots next to the code examples.

**Comment by Saulis** [comment]
- Add screenshots for the examples in https://vaadin.com/docs/-/part/elements/vaadin-combo-box/vaadin-combo-box-item-template.html
- Change the example and inline demo in `README.md` to use the Jouni's super awesome paper-face-item demo. Update the screenshot also.
