### ISSUE TITLE
selectedItem not updating with mouse input

### ISSUE THREAD

**Issue by Link2Twenty** [vaadin/vaadin-combo-box#399]
### Description
_overlaySelectedItemChanged does not update selectedItem on click but does fire

### Expected outcome
this.selectedItem = detail.item

### Actual outcome
this.selectedItem remains unchanged

### Tempurary solution
```js
    _overlaySelectedItemChanged: function(event, detail) {
      if (this.selectedItem !== detail.item) {
        this.selectedItem = detail.item;
      }

      if (this.opened) {
        this.close();
      }

      // stop this private event from leaking outside.
      event.stopPropagation();
    },
```

Changed to

```js
    _overlaySelectedItemChanged: function(event, detail) {
      while(this.selectedItem !== detail.item) {
        this.selectedItem = detail.item;
      }

      if (this.opened) {
        this.close();
      }

      // stop this private event from leaking outside.
      event.stopPropagation();
    },
```

### Extra info
It works fine if you use keyboard input, or if you call comboBox._overlaySelectedItemChanged(event, object) from the console.

I'm using polymer 1.8 but the same was true with polymer 1.7
I'm also using the latest combo box.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] Android Chrome

**Comment by Saulis** [comment]
Hi!

I'm not able to reproduce the issue.

Can you modify this example to reproduce it? https://jsfiddle.net/Saulis/hah7nbro/

Thanks!

**Comment by Link2Twenty** [comment]
Hmm, I can't recreate it there so it must be something in my code.
Though it only started happening after I updated the element 😕
