### ISSUE TITLE
Define developer user test for 1.0-alpha1

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#4]
Conduct API user testing for the first draft of the API.

- [x] Define test tasks
- [x] Define the number of test users
- [x] Define test platforms

**Comment by tuomasnironen** [comment]
vaadin-combo-box / Developer Usability Test (in progress):
https://docs.google.com/document/d/1rKfpB0Hms6b7ihXF9pR6ZXA7RsyrsY5FlHtpzxp1w1Q/edit#

Combo-box user test starter kit (in progress):
https://gist.github.com/tomivirkki/da611326a6710fde6477

**Comment by tuomasnironen** [comment]
## Test tasks (moderated/remote testing template)
* Editable: https://docs.google.com/a/vaadin.com/forms/d/1ax57q_fegjcaTUHa5xnSB96B1gguXMUtl0a8IFtqswY/edit
* Viewable: https://docs.google.com/forms/d/1ax57q_fegjcaTUHa5xnSB96B1gguXMUtl0a8IFtqswY/viewform

**Comment by tuomasnironen** [comment]
Test page (index.html) in Gist:
https://gist.github.com/tomivirkki/da611326a6710fde6477
