### ISSUE TITLE
Hover/focused & selected customizations

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/vaadin-combo-box#410]
### Description
The `vaadin-combo-box` element does not provide a way to override the hover/focused & selected styles.

The focused state is using _background: #eee;_ which should be given via a CSS variable so that it could be changed externally. Apart from that CSS mixins should be used by default for both cases.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by Saulis** [comment]
Hi!

With the custom item templates introduced in `v1.3.0` you can apply some custom styles to the items, although it requires some work. Here's an example: https://jsfiddle.net/Saulis/q50qa303/

We will be working on #403 and #367 to provide a better way for styling the items.

**Comment by web-padawan** [comment]
@attilapuskas this can now be achieved with the theme support introduced in 3.0.0 release of the `vaadin-combo-box`. Starting from the 4.0.0, this element uses Valo theme by default and [this file](https://github.com/vaadin/vaadin-combo-box/blob/master/theme/valo/vaadin-combo-box-item.html) contains styles for both `selected` and `focused` states

It is also possible to implement your own theme, see `ThemableMixin` [wiki](https://github.com/vaadin/vaadin-themable-mixin/wiki) page. Therefore I am closing with issue, but feel free to ping us if you have more questions.

**Comment by attilapuskas** [comment]
Thank you! :)
