### ISSUE TITLE
Add support for Material Chips

### ISSUE THREAD

**Issue by JosefJezek** [vaadin/vaadin-combo-box#412]
Could you add support for Material Chips?

- https://www.webcomponents.org/element/WebPaperElements/paper-input-autocomplete-chips
- https://material.io/guidelines/components/chips.html#chips-specs
- http://materializecss.com/chips.html
- https://material.angularjs.org/latest/demo/chips

**Comment by jouni** [comment]
The plan is to make this possible with the multi-select feature (#88), so that you can use any material chip components yourself to represent the selected items.

**Comment by JosefJezek** [comment]
@jouni ok, do you have term for multi-select feature?

**Comment by jouni** [comment]
We don’t anything more specific planned except that we want to do it before Q4 this year.

In the meantime, you should be able to use vaadin-combo-box-light to render the single selected item as a chip, if you don’t need multi-select. I can try to do an example.

**Comment by JosefJezek** [comment]
@jouni I don't need multi-select, please example...

**Comment by jouni** [comment]
Here’s a barely functional example: http://jsbin.com/hokucasupu/edit?html,output

The paper-chip element I used there isn’t perhaps the best out there, so you might want to search for alternatives to that.

**Comment by jouni** [comment]
I cleaned up the example a bit, used another paper-chip element which seems to work better.

**Comment by JosefJezek** [comment]
@jouni thank you

**Comment by web-padawan** [comment]
Closing in favor of #88 as mentioned in https://github.com/vaadin/vaadin-combo-box/issues/412#issuecomment-285030791
