### ISSUE TITLE
Allow custom input

### ISSUE THREAD

**Issue by vinerz** [vaadin/vaadin-combo-box#422]
### Description
This element is awesome, congratulations for its contributors!

### Expected outcome
A config property for the element that allows it to not be constrained by its items values, allowing custom inputs when nothing matches. This way, the combo box should act only as a helper to get to the result faster.

### Actual outcome
Today, when an inserted value is not present on the items array property, the blur event just wipes the combo box data.

--

Can it be done today with some config property or is it on the roadmap? Couldn't find it on the docs.

Thanks in advance!

**Comment by jouni** [comment]
Hi, and thanks for the nice feedback!

This feature is already available, precisely named as “allow custom value”. So, you can enable ot woth the attribute `<vaadin-combo-box allow-custom-value>`. 

Here’s an example: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/demo/advanced.html#typing-custom-values

**Comment by vinerz** [comment]
Oh! Fool me. How could I miss the first property on the documentation?
I really need some rest.

Thank you for the help @jouni!
