### ISSUE TITLE
this._debounceTemplate is not a function in 2.0-preview

### ISSUE THREAD

**Issue by Desproposito** [vaadin/vaadin-combo-box#428]
### Description
When trying to add the vaadin-combo-box 2.0-preview I'm getting the following error.

Uncaught TypeError: this._debounceTemplate is not a function
    at HTMLElement._setOverflow (iron-list.html:809)
    at Object.runMethodEffect [as fn] (property-effects.html:900)
    at runEffectsForProperty (property-effects.html:127)
    at runEffects (property-effects.html:100)
    at HTMLElement._propertiesChanged (property-effects.html:1735)
    at HTMLElement._flushProperties (property-accessors.html:443)
    at HTMLElement._flushProperties (property-effects.html:1629)
    at HTMLElement.ready (property-effects.html:1663)
    at HTMLElement.ready (legacy-element-mixin.html:135)
    at HTMLElement.ready (class.html:198)

### Expected outcome
Combo-box is supposed to render.

### Actual outcome
The shadow doom is generated but the combo-box is not visible at all and the rest of the page stop rendering.

### Steps to reproduce
Using the simple demo combobox throws the error.

### Browsers Affected
- [x] Chrome

**Comment by Desproposito** [comment]
I have tried using _items_ attributes and changing it imperatively, and also using a static array.

**Comment by limonte** [comment]
Hi @Desproposito and thanks for reporting this issue! 

Could you please show some code so we can reproduce and fix it.

**Comment by Desproposito** [comment]
I have tried in many different ways before opening the issue, but this is the simplest one...
```

<!-- rest of html -->
<template>
	<vaadin-combo-box id="demo1" items="[[testItems]]" label="Element"></vaadin-combo-box>
</template>

<script>
	class MyClass extends Polymer.Element {

                 //Rest of javascript

             static get properties() {
                return {
                   testItems: {
                      type: Array, values: ['Hi', 'All']
	           }
               };
          }
	}
</script>

```

**Comment by limonte** [comment]
`2.0-preview` branch isn't ready for use currently. We're actively working on it and I will notify you here when it's ready.

Thanks again and have a nice day!

**Comment by Desproposito** [comment]
Oops, I thought it was already working although not stable. My fault then, thanks.

**Comment by jaichandra** [comment]
It works after updating `iron-list` dependency to use the `2.0-preview` branch.

**Comment by mflorence99** [comment]
Many thanks and apologies for the poor follow-up. This issue is no longer apparent in the 2.0.0-alpha3 version.

**Comment by limonte** [comment]
Thanks for the feedback @mflorence99

**Comment by zapphyre** [comment]
I have tried suggested on the 'polymer-2-application' application, but combo box doesn't render...
Not on the Firefox not on the chrome...

```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">
<link rel="import" href="../../bower_components/polymer-element.html">
<link rel="import" href="../../bower_components/vaadin-combo-box/vaadin-combo-box.html">
<!--<link rel="import" href="../../bower_components/polymer/lib/elements/dom-if.html">-->
<!--<link rel="import" href="../../bower_components/polymer/lib/elements/dom-repeat.html">-->

<dom-module id="polytest-app">
    <template>
        <style>
            :host {
                display: block;
            }
        </style>
        <h2>Hello [[prop1]]!</h2>
        <vaadin-combo-box items="[[types]]" id="demo2"></vaadin-combo-box>

    </template>

    <script>
        /** @polymerElement */
        class PolytestApp extends Polymer.Element {
            static get is() {
                return 'polytest-app';
            }

            static get properties() {
                return {
                    prop1: {
                        type: String,
                        value: 'polytest-app'
                    },
                    types: {
                        types: Array, values: ['Hi', 'All']
                    }
                };
            }
        }

        window.customElements.define(PolytestApp.is, PolytestApp);
    </script>
</dom-module>
```

**Comment by ananthsubbu** [comment]
hi @zapphyre   you have a typo in your code. properties object should contain `value` not `values`

change this line of code 
`types: {
              types: Array, values: ['Hi', 'All']
             }`
to this
`types: {
              types: Array, value: ['Hi', 'All']
             }`

hope this helps you.
