### ISSUE TITLE
Fullscreen combo-box should close when tapping outside the list

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-combo-box#43]
Fullscreen combo-box should close when tapping on the grey area under the list.

![close-area](https://cloud.githubusercontent.com/assets/368220/11142158/f51ba1d4-89f3-11e5-960b-e52bf9bd98ee.png)

**Comment by tehapo** [comment]
Should we actually have this also for non-fullscreen mode? My initial implementation works this way and to me it feels pretty natural to close the dropdown by clicking somewhere outside it.

**Comment by tomivirkki** [comment]
It used to work on desktop afaik. Something changed with Chrome? Still seems to work on FF

**Comment by tehapo** [comment]
Oh, sorry. My bad, it does work already on desktop.

**Comment by tehapo** [comment]
For the record, this confusion was from the Polydev browser plugin, which caused some JS errors that broke the functionality. :-1:

**Comment by tomivirkki** [comment]
Damn, need to reopen. Was under the impression that Reviewable doesn't show the "merge" button unless all tests pass. Apparently some tests were still failing.

**Comment by tehapo** [comment]
So it seems. I'll look into it.
