### ISSUE TITLE
The component is not selecting the elements

### ISSUE THREAD

**Issue by distribuidoralemes** [vaadin/vaadin-combo-box#431]
### Description
The `vaadin-combo-box` element is not selecting the elements. I'm using angular 2.

### Expected outcome
Fire the change event and select the item.

### Actual outcome
The component close and not fire the change event and also not put the label in input

### Steps to reproduce

```
public items: Object[] = [
    { "id": 11, "name": "Mr. Nice", "birthday": "1980-01-11" },
    { "id": 12, "name": "Narco", "birthday": "1980-01-12" },
    { "id": 13, "name": "Bombasto", "birthday": "1980-01-13" },
    { "id": 14, "name": "Celeritas", "birthday": "1980-01-14" },
    { "id": 15, "name": "Magneta", "birthday": "1980-01-15" },
    { "id": 16, "name": "RubberMan", "birthday": "1980-01-16" },
    { "id": 17, "name": "Dynama", "birthday": "1980-01-17" }
  ];
```

```
<vaadin-combo-box #comboBox 
        label="Test" 
        [(value)]="selected" 
        [items]="items" 
        item-label-path="name" 
        item-value-path="id"></vaadin-combo-box>
```

This event is not called:
```
this.vaadinComboBox.nativeElement.addEventListener('changed', function(e) {
    console.log('mudou' + JSON.stringify(e.target.selectedItem));
});
```

**Comment by distribuidoralemes** [comment]
When I use directly on element, then it works

```
@ViewChild('comboBox') vaadinComboBox;

public ngAfterContentInit() {
    this.vaadinComboBox.nativeElement.items = this.items;
}
```

**Comment by jouni** [comment]
Hi! Doing two-way databinding between Angular and Polymer is something that requires additional work, if I’ve understood correctly. You should take a look at the [angular-polymer](https://github.com/platosha/angular-polymer) project which could offer a solution.

At least the fact that the event listener for the “changed” event, that you add to the combo box, will not be called as vaadin-combo-box doesn’t fire such an event. It fires `selected-item-changed`, `value-changed` and `change` events: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/#vaadin-combo-box:events (scroll to the bottom of the page).

**Comment by jouni** [comment]
I suppose the `selected` property which you bind to the `value` property of vaadin-combo-box is an id number? Not 100% sure, but it might be that vaadin-combo-box converts that first to a string before doing the comparison (as the value can only be a string), so it would not select anything. You could try binding to the `selectedItem` property instead, which takes an object.

**Comment by distribuidoralemes** [comment]
I'm already use angular-polymer, but doesn't work yet. I'll investigate a little bite more

**Comment by H3dz** [comment]
I had the same issue because value was a string instead of an integer.
