### ISSUE TITLE
Overlay height is too small in Firefox and IE

### ISSUE THREAD

**Issue by strepon** [vaadin/vaadin-combo-box#432]
In Firefox and IE11, the overlay is only 2 rows high, whereas the height is reasonable in Chrome or Edge.

See this plunker:
http://plnkr.co/edit/whtDhx481e9WpbpT21gP?p=preview

The problem seems to lie in the `_maxHeight` function in `vaadin-overlay-behavior.html` where incorrect scrollHeight is obtained.

**Comment by jouni** [comment]
What is the height of the body element?

**Comment by strepon** [comment]
The body height is `undefined`.

**Comment by jouni** [comment]
Right, but what about the computed height? The height of the body restricts the overlay height, if I remember correctly.

**Comment by strepon** [comment]
OK, the computed height is the height of the combo box (62 px) in this case, but I don't see any relation between these values (if I have more controls on the page and body height is greater, the overlay stays the same).

**Comment by web-padawan** [comment]
In polymer apps we usually use following styles:
```css
body {
  margin: 0;
  height: 100vh;
}
```
This should fix your issue.

**Comment by strepon** [comment]
Indeed, that does the job - thanks for the tip!

**Comment by web-padawan** [comment]
Closing per above comment. In the future, feel free to ping us in the [#vaadin](https://polymer.slack.com/messages/C6ULJ2F7S) channel of the Polymer Slack for any kind of questions related to Vaadin Elements.
