### ISSUE TITLE
Label doesn't show up in #2.0-preview when using Polymer 2

### ISSUE THREAD

**Issue by oskarlh** [vaadin/vaadin-combo-box#435]
### Description
`<vaadin-combo-box label="This label? You won't see it!"></vaadin-combo-box>`
The label doesn't show up in #2.0-preview when using Polymer 2.0.0-rc.7

### Expected outcome
The input element has a label.

### Actual outcome
The label doesn't show up in #2.0-preview when using Polymer 2.0.0-rc.7

### Steps to reproduce
1) Create a polymer 2.0.0-rc.7-based website.
2) Use `<vaadin-combo-box>` with a label attribute.
3) The label is invisible.

### Browsers Affected
- [X] Chrome
- [X] Firefox

### How to fix
In vaadin-combo-box.html, replace the line
`<label on-down="_preventDefault" id="label" hidden$="[[!label]]" aria-hidden="true" on-tap="_openAsync">[[label]]</label>`
with
`<label slot="label" on-down="_preventDefault" id="label" hidden$="[[!label]]" aria-hidden="true" on-tap="_openAsync">[[label]]</label>`
Tested with Polymer 2.0.0-rc.7. No idea how it affects users of earlier versions of Polymer.

**Comment by manolo** [comment]
Thanks for reporting, actually 2.0-preview is in the review process #427 . I'll leave a comment in the PR and close this issue to continue the conversation there.
