### ISSUE TITLE
Label missing in dropdown.  2.0-preview.

### ISSUE THREAD

**Issue by rkief** [vaadin/vaadin-combo-box#446]
### Description
Labels missing in dropdown.  Items are there for selection.  After items are selected, the labels show in dropdown.  2.0-preview.  Worked before latest update.

### Expected outcome
Items should appear in overlay.

### Actual outcome
Labels do not display in overlay.

### Live Demo
<vaadin-combo-box items='[{"label": "Hydrogen", "value": "H"},{"label": "test", "value": "M"}]' label="Type"></vaadin-combo-box>

### Steps to reproduce
1. Put a `vaadin-combo-box` element in the page.
2. Open the page in a web browser.
3. Click the input of `vaadin-combo-box` element.
4. The list of item are there but without labels.
5. After selecting item, the label appears in overlay.

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by mflorence99** [comment]
I see this also, exactly as described. Via Chrome dev tools, I believe I'm seeing that no text is actually in the `<vaadin-combo-box-item>`s at all until they are clicked.

**Comment by rkief** [comment]
Could be related to this issue:
Observers not called on component inside an iron-list template #4601
https://github.com/Polymer/polymer/issues/4601

**Comment by Saulis** [comment]
Does this issue reproduce in `v3.0.0-alpha1` ?

**Comment by rkief** [comment]
Using "vaadin-combo-box": "vaadin/vaadin-combo-box#v2.0.0-alpha4"
Not seeing v3.0.0-alpha1 except for grid.

**Comment by mflorence99** [comment]
Also not seeing v3.0.0-alpha1, but I can confirm that items are showing correctly in v2.0.0-alpha4.

**Comment by Saulis** [comment]
@rkief @mflorence99 yeah ugh, sorry I meant the `v2.0.0-alpha4` :+1: :-)

**Comment by rkief** [comment]
Upgraded everything and working fine with v2.0.0-alpha4.  Thank you.

**Comment by rkief** [comment]
Closing issue?
