### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#452]
### Description
Open latest demo in IE11, the overlay is never shown when clicking or focusing an input

### Live Demo
https://github.com/vaadin/vaadin-combo-box/releases/tag/v2.0.0-alpha3

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by manolo** [comment]
Related with #437

**Comment by platosha** [comment]
Seems to reproduce in Polymer v1 only for me.

Probably the demo page issue, as there are console errors: `Unable to set property 'items' of undefined or null reference`. Note that the console is updated with a very long delay, it might take a minute before you see the errors.

After I assign the items manually, the overlay works fine.

Not sure if we want to fix this.

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
