### ISSUE TITLE
not all items shown at first open

### ISSUE THREAD

**Issue by VladislavAnkudinov** [vaadin/vaadin-combo-box#454]
When I open up my combo box first time I don't see all the items provided. For example I could see 3 items of 6, but the size of dropdown is looks like it should contain 6 items. I just see empty space for the last 3 items. If I close dropdown and open it again this bug is gone and I can see everything.
Why could this happen?

**Comment by web-padawan** [comment]
Check if you have correct `iron-list` version.

**Comment by VladislavAnkudinov** [comment]
What is correct `iron-list` ? I use `"version": "1.4.6",`

**Comment by mflorence99** [comment]
I saw this problem in an earlier version (see #446) but no longer.

Don't you want `iron-list` version 2.0.0? That's what I have, just by grabbing all the Polymer components with `^2.0.0`.

**Comment by samiheikki** [comment]
@VladislavAnkudinov Can you provide a jsfiddle of your code for me to take a look? If not, I'm having same  the same hunch that iron-list could be updated.

**Comment by VladislavAnkudinov** [comment]
found the answer, it was old version of the grid `1.0.0`
