### ISSUE TITLE
Custom icons does't work (at least) in demos

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-combo-box#456]
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/demo/advanced.html#configuring-icons
```
<vaadin-combo-box id="demo2" label="Custom Icons">
  <paper-icon-button icon="remove-circle" class="clear-button"></paper-icon-button>
  <paper-icon-button icon="search" class="toggle-button"></paper-icon-button>
</vaadin-combo-box>
```
The two paper-icon-buttons are visible but clicking them won't open/close dropdown or clear selection.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge
- [X] IE 11
- [X] iOS Safari
- [X] Android Chrome

**Comment by manolo** [comment]
Problem seems that master is not updated, latest release have icons working:
https://cdn.vaadin.com/vaadin-combo-box/2.0.0-alpha4/demo/advanced.html#configuring-icons

**Comment by samiheikki** [comment]
Perfect, thanks @manolo
