### ISSUE TITLE
Customize input fiels when the component is disabled

### ISSUE THREAD

**Issue by robertop87** [vaadin/vaadin-combo-box#457]
### Description
Cannot customize the input field when the component is disabled

### Expected outcome
Provide a mixin **--vaadin-combo-box-input-disabled** to allow modify the styles when the component is disabled

### Actual outcome
There is no way to customize the input field when then component is disabled

**Comment by samiheikki** [comment]
Hi @robertop87 thanks for reporting the issue. For a use case such as this, we have created the `<vaadin-combo-box-light>` element. You can for example add a `paper-input` inside it which has `--paper-input-container-disabled` mixin available.

How to replace combo-box's input with paper-input: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-combo-box/demo/advanced.html#replacing-the-input-with-a-paper-input-
paper-input docs: https://www.webcomponents.org/element/PolymerElements/paper-input
