### ISSUE TITLE
Open always drop down downward

### ISSUE THREAD

**Issue by bohdaq** [vaadin/vaadin-combo-box#459]
### Description
I need to open drop down always in downward direction. Currently it opens upward if there is more space on top.

### Expected outcome

Dropdown opens downward 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment]
Can you describe your use case in more detail? What problem does it cause when the dropdown opens above the field?

**Comment by bohdaq** [comment]
@jouni we want to make consistent looking UI, and vaadin-combo-box fits pretty well, however we have different dropouts on UI and want to make UX consistent, so could you, please, advice wheter there is a property/option to achieve such behaviour?

**Comment by tomivirkki** [comment]
There’s nothing in the public API for this but here’s a hack that does the job :)
`combobox.$.overlay._shouldAlignAbove = function() {return false;}`

Notice that it accesses private APIs so there’s a risk (while unlikely) of this breaking at some point.

**Comment by bohdaq** [comment]
@tomivirkki @jouni yeah, that works perfectly, thanks!
