### ISSUE TITLE
Vaddin combo box filtered drop-down with hyperlink option for drop-down items

### ISSUE THREAD

**Issue by skandulapati** [vaadin/vaadin-combo-box#460]
Any provision for Vaddin combo box filtered drop-down with hyperlink option for drop-down items

**Comment by jouni** [comment]
What is the use case you are trying to accomplish? Do you want the whole item to be a link, or do you want to have a link in each item as a secondary action?

**Comment by skandulapati** [comment]
Hello Jouni, I want to have a link in each item as a secondary action..Upon clicking the drop-down item I have to get that clicked item name and based on that showing some pop-up with relevant information. Thanks for your message

**Comment by web-padawan** [comment]
Sorry about not answering earlier. Starting from the 4.2.0 release there is a new feature: renderer function allowing to configure item content.

Here is the example how to implement the requested use case:
