### ISSUE TITLE
Theming Support

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#462]
- Using a vaadin-text-field for the input
- Add parts like in date-picker: input, clear-icon, toggle-icon, overlay
- Make the items themable, consider having reusable `vaadin-item` element or something

**Comment by jouni** [comment]
Is it too early to split the clear button feature to vaadin-text-field? Eventually I think we want to do that, but just wondering if you consider it unnecessary at this point.

**Comment by bohdaq** [comment]
also i have one question regarding theming support, will i be able to apply a css mixin to combo-box e.q. @apply(--vaadin-combo-box)/ --vaadin-combo-box { height: 12px; width: 12px }?

**Comment by jouni** [comment]
@bohdaq: we are dropping CSS mixins from the pure Polymer 2 versions, which this issue relates to. Instead, you will be able to add style modules to the elements which can target certain parts inside the shadow DOM of the element, which is more flexible than CSS mixins.

**Comment by manolo** [comment]
>  split the clear button feature to vaadin-text-field
