### ISSUE TITLE
Remote filtering example not working for Safari/FF

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#465]
https://cdn.vaadin.com/vaadin-combo-box/2.0.0-alpha4/demo/filtering.html

"Remote data source" example not working for Safari or Firefox atleast. Chrome works normally.

**Comment by limonte** [comment]
This was fixed yesterday in https://github.com/vaadin/vaadin-combo-box/commit/195c3d7ee3157a393f06cfbf9b19051628ee16b8

Will be live after the next release (on Friday).
