### ISSUE TITLE
vaadin-combo-box not working with iron-list v2.0.1

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-combo-box#467]
I'm trying to use the vaadin-combo-box in a Polymer 2 application (vaadin-grid is working properly), but I get erratic behavior (I'm using the v2.0.0-alpha4 version), that it's so strange it must be coming from some version conflict with something else...
With a simple list of items, at every keyboard typing list is restricted or reset to the whole content, while nothing is displayed on screen.
What I'm asking is if you can imagine some way to narrow the problem: sometimes you have had the same kind of problem... :-)
Same behavior in Chrome and Firefox.
Thanks for some ideas, if any...
Andrea

**Comment by H3dz** [comment]
I'm also having strange behaviors with 2.0.0-alpha4

If I only click on the list or click dismiss everything works well.

It breaks when I start to type in the input, for some reason nothing is displayed in the input, basically whatever I type is not visible. After that the list disappears and I get a JS error:

vaadin-combo-box-behavior.html:403 Uncaught TypeError: Cannot read property '1' of undefined
    at HTMLElement._onClosed (vaadin-combo-box-behavior.html:403)

**Comment by andreabioli** [comment]
...exactly my same behavior... I thought it could be some conflict with some other library I'm using, but you are giving me other feelings... :-(
A

**Comment by Saulis** [comment]
Hi @andreabioli @H3dz I think I've bumped to the same issue. 
For me, downgrading `iron-list` from `v2.0.1` to `v2.0.0` seems to help. Can you verify if that also helps you?

**Comment by andreabioli** [comment]
...I'm shocked! :-) Now it works!
I'm more than happy, for the moment, even if I think that we'll have to wait for a better properly aligned version of the combo box...
Thanks really a lot!
Andrea
P.S.: does this mean that we are entering into the nightmare phase of developing software where every minor update can disrupt everything??? :-(((((((

**Comment by limonte** [comment]
> does this mean that we are entering into the nightmare phase of developing software where every minor update can disrupt everything??? :-(((((((

![](https://s-media-cache-ak0.pinimg.com/originals/7d/0e/c3/7d0ec35b7e0b14496f4db34ead87f529.jpg)

**Comment by andreabioli** [comment]
@Saulis: I didn't realize you are a developer in Vaadin... so double thanks for your kind and superfast answer! :-)

**Comment by Saulis** [comment]
@andreabioli Thanks!

I'll actually reopen this ticket since we need to figure out a way to make combo-box work also with `iron-list#2.0.1`

**Comment by Saulis** [comment]
`iron-list#2.0.2` seems to have a fix for this issue – so use that.

**Comment by andreabioli** [comment]
It looks very good, now, for me... so can we say that the problem wasn't in the vaadin component, but in the iron-list? :-)
