### ISSUE TITLE
how can I remove the 'cancel' button?

### ISSUE THREAD

**Issue by davidmaxwaterman** [vaadin/vaadin-combo-box#469]
I don't want the user to be able to cancel since it doesn't do what the docs say - they say it should revert to the original value, but it simply clears the field, which I don't want.

**Comment by web-padawan** [comment]
You could pass something like an invisible icon into `clear-button` slot. As of 1.x, this looks like this (for 2.x you should use slot instead of class):
```html
<paper-icon-button class="hidden clear-button"></paper-icon-button>
```

**Comment by limonte** [comment]
The solution for v3: https://jsfiddle.net/6r5htd05/33/

**Comment by jouni** [comment]
I don’t actually understand the original issue. There is no “cancel” button, only a “clear” button. Do we say “cancel button” somewhere in our docs?

**Comment by jouni** [comment]
Pressing ESC reverts to the currently selected value.

**Comment by web-padawan** [comment]
@jouni the possible use case is the required field which, once selected, should never be cleared and could be just changed.

E. g. some kind of entity version selector (if that entity, article etc, has no saved versions yet, it should not be displayed at all).

**Comment by jouni** [comment]
Sure, I understand that use case. But the original issue description doesn’t mention that, so I was wondering where @davidmaxwaterman found that piece of documentation.
