### ISSUE TITLE
API docs: missing state attributes

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#475]
Attributes such as `focused`, `focus-ring`, `disabled`, `invalid` are available on the host element for styling, but not listed in the API docs as of now.

API documentation should list all of the attributes available for styling.

**Comment by tomivirkki** [comment]
Fixed in https://github.com/vaadin/vaadin-combo-box/commit/77588835da38a85a2ec04b451fd16ca70e280b8d
