### ISSUE TITLE
Upgrade iron-form dependency version to v2.0.0

### ISSUE THREAD

**Issue by masonlouchart** [vaadin/vaadin-combo-box#479]
### Description
Bower is asking to chose between Polymer iron-form v2.0.0 or v2.0.0-preview at the install step.

### Expected outcome
Don't ask to chose Polymer version.

### Actual outcome
<img width="742" alt="capture d ecran 2017-07-10 a 16 35 03" src="https://user-images.githubusercontent.com/2325091/28023386-19dd5a72-658e-11e7-940c-42951d010ee8.png">

### Steps to reproduce
1. Create an app that require polymer^2.0.0
2. Install "vaadin-combo-box": "^2.0.0-beta1"
3. Remove "bower_components" folder
4. Run bower install

**Comment by masonlouchart** [comment]
Already done [5189da1](https://github.com/vaadin/vaadin-combo-box/commit/5189da14c005031c2225e2eeb57c164fb4ebc11f) but not released.

**Comment by web-devel** [comment]
Could it be backported to 2.x version ?

**Comment by andreabioli** [comment]
The dependency on iron-form#2.0-preview is still there...

**Comment by masonlouchart** [comment]
@andreabioli have you tried to use the version 2.0 of the `vaadin-combo-box` element? It seems the [dependency iron-form has been updated](https://github.com/vaadin/vaadin-combo-box/blob/2.0/bower.json#L24).

**Comment by andreabioli** [comment]
Oh... I see the code, and obviously your are right! :-)
What I'm wondering now is why with this line:

"vaadin-combo-box": "vaadin/vaadin-combo-box#^2.0.0",

I do NOT get the correct source code, when updating... :-(
I have to investigate better...
Thank you anyway for your support!
Andrea Bioli

**Comment by andreabioli** [comment]
And I can confirm that uninstalling in my project with:

bower uninstall --save vaadin/vaadin-combo-box

and installing it again with

bower install --save vaadin/vaadin-combo-box

creates a local copy with STILL the dependency with the preview version of iron-form:

"iron-form": "2.0-preview",

**Comment by masonlouchart** [comment]
@andreabioli Maybe the Bower's cache is responsible.
Run the command `bower cache clean vaadin/vaadin-combo-box` then retry to re-install it.

**Comment by web-padawan** [comment]
@masonlouchart @andreabioli this change is not tagged yet. For the time being you can pin bower dependency to this particular commit:
```
"vaadin-combo-box": "vaadin/vaadin-combo-box#d9a390a",
```

**Comment by masonlouchart** [comment]
Or pin the branch `vaadin/vaadin-combo-box#v2`.
