### ISSUE TITLE
errorMessage not shown (2.0.0-beta1)

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-combo-box#483]
### Description
When setting the combo-box invalid, the errorMessage is not shown.

### Expected outcome
The red text below the red line to be shown when invalid

### Actual outcome
Only the label and the line become red, but no text is shown
Due to the recent changes, I think that the paper-input-error is not updated. Changing the line 265 in file vaadin-combo-box.html from
`<paper-input-error>[[errorMessage]]</paper-input-error>`
to
`<paper-input-error slot="add-on">[[errorMessage]]</paper-input-error>`
apparently fixes the problem. Is it correct?

**Comment by platosha** [comment]
Correct. Can confirm, it’s indeed a bug in the `<vaadin-combo-box>`.

Same issue exists in v2.0.0-beta2 as well.

**Comment by andreabioli** [comment]
...oh, is there a beta2? :-)

**Comment by jouni** [comment]
Duplicates #470, which already has a PR waiting with a fix (#476).

**Comment by jouni** [comment]
@andreabioli, is it okay to close this issue as a duplicate?

**Comment by andreabioli** [comment]
Yes, sorry, sometimes I'm really crazy... :-(
