### ISSUE TITLE
Height of the component

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-combo-box#484]
### Description
I put in a row, side by side, a paper-input and a vaadin-combo-box, with default settings and fonts.

### Expected outcome
Both texts are aligned.

### Actual outcome
Vaadin-combo-box component appears to be 'below' the paper-input.

With Chrome Developer Tools I can see that apparently the generated DOMs are more or less the same, but the vaadin-combo-box inserts paper-icon-button(s) elements in the slot 'suffix', that are 32px high. This makes all the vaadin-combo-box 'larger', and the alignment is lost.
Apparently, but just in the default case, forcing the container input-wrapper to a height of 24px brings the alignment back, but it's just for the particular case, of course...

**Comment by andreabioli** [comment]
Just a little test to see what is the problem.
This simplified code:
```
<vaadin-combo-box>
    <div slot="clear-button" style="width:24px; height:24px">
        <paper-icon-button id="clearIcon" tabindex="-1" aria-label="Clear" icon="vaadin-combo-box:clear" class="clear-button small">
        </paper-icon-button>

    </div>
    <div slot="toggle-button" style="width:24px; height:24px">
        <paper-icon-button id="toggleIcon" tabindex="-1" icon="vaadin-combo-box:arrow-drop-down" aria-label="Toggle" aria-expanded$="[[_getAriaExpanded(opened)]]"
            class="toggle-button rotate-on-open">
        </paper-icon-button>
    </div>
</vaadin-combo-box>
```
Obtained copying the two icons in the slots (from the source code), and limiting their size, realigns the widget, even if the result is not good. There should be a generic way to get the right solution...

![image](https://user-images.githubusercontent.com/13900431/28163536-d412fbe2-67cb-11e7-90f0-19e6f7c53f7c.png)

**Comment by web-padawan** [comment]
In the latest version of the component, we dropped support for `slot="clear-button"` so it might be only reproduced in `vaadin-combo-box-light` which is not our main focus.

However, the component is still not aligned with neither `paper-input` not `mwc-textfield`:

![material](https://user-images.githubusercontent.com/10589913/78108362-e5f33f00-73ff-11ea-8c99-5e9c25dd885a.png)

We need to take this into account in case we want to actualise our Material theme.

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-text-field/issues/463
