### ISSUE TITLE
Expose z-index of vaadin overlay

### ISSUE THREAD

**Issue by anandanand84** [vaadin/vaadin-combo-box#486]
Expose vaadin overlay z-index for styling. Currently we cannot change the z-index of overlay, the current value can be problematic for certain applications which has their custom stack order.

**Comment by jouni** [comment]
You can add a custom style/theme module for `vaadin-overlay` and expose a custom property for adjusting the z-indexes. Place the following in your index.html or in a separate HTML import:

```html
<dom-module id="my-vaadin-overlay-fixes" theme-for="vaadin-overlay">
  <template>
    <style>
      :host {
        z-index: var(--vaadin-overlay-container-z-index);
      }
    </style>
  </template>
</dom-module>
```

**Comment by web-padawan** [comment]
Closing per above comment.
@anandanand84 if you still have problems with customizing Vaadin elements, please see the `ThemableMixin` [wiki](https://github.com/vaadin/vaadin-themable-mixin/wiki) page.

**Comment by jonmann20** [comment]
Hello, I am unable to modify the z-index.  It seems to be adding in my styles, but no effect.


![vaadin-overlay](https://user-images.githubusercontent.com/2007099/95124394-59fcff80-0721-11eb-9c99-e6500c1b0ee3.png)
