### ISSUE TITLE
Allow the <template> of the items to be set after the webcomponent is ready

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-combo-box#489]
### Description
Currently a `<template>` for the items inside the combo box is only evaluated when the `<template>` is present before the event `WebComponentReady` is triggered. When setting a `<template>` after the component is ready, it is ignored.

### Expected outcome
I expect the template to be used by the combo box whenever is set. This is needed when using the element though dynamic creation via JS DOM API.

### Actual outcome
The items are rendered in blank. They are still selectable, but no text is shown.

### Live Demo
https://jsbin.com/tuvohurobu/edit?html,output

**Comment by gilberto-torrezan** [comment]
A follow-up: apparently the problem doesn't happen if you set the contents of the template by using `templateElement.innerHTML = ...` instead of `templateElement.text = ...`.

**Comment by web-padawan** [comment]
Works correctly with the latest version: https://glitch.com/edit/#!/elated-carpenter?path=index.html:14:0
Closing as fixed, most likely while introducing renderers.
