### ISSUE TITLE
The 'Item Template with Material Design' example is broken

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-combo-box#491]
https://cdn.vaadin.com/vaadin-combo-box/2.0.0/demo/item-template.html#item-template-with-material-design

Something is wrong with spacing:
![](https://i.imgur.com/ntjuTWy.png)

Chrome 59/Linux

**Comment by manolo** [comment]
In master is already fixed.
Fixed in 2.0.0 https://github.com/vaadin/vaadin-combo-box/commit/ad90b0883a5bba56c16e6fb9655d3590432e3d65
