### ISSUE TITLE
Regression in 2.0: overlay does not open when tapping on the input

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#505]
1.x version (expected behavior):
 - Tapping the input opens the overlay and keyboard ✅
 - Scrolling the overlay closes the keyboard ✅

![combo1](https://user-images.githubusercontent.com/66382/29768470-0e50bb7c-8bef-11e7-91b2-799afd8c927b.gif)

2.0 version (incorrect behavior):
 - Tapping the input opens the keyboard, but not the overlay ❌
 - Scrolling the overlay closes the keyboard ✅

![combo2](https://user-images.githubusercontent.com/66382/29769048-3f2854ba-8bf1-11e7-995b-18a0a9558c41.gif)

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
