### ISSUE TITLE
Regression in 3.0: blurring the input refocuses it immediately after (iOS)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#506]
When tapping the “Done” button, the keyboard closes but pops up right after it. When you tap the “Done” button the second time, then the keyboard stays hidden (field does not get re-focused).

![combo4](https://user-images.githubusercontent.com/66382/29769259-3eaed71a-8bf2-11e7-8350-7746524143a3.gif)

**Comment by tomivirkki** [comment]
This seems to be occurring again
