### ISSUE TITLE
It's not possible to style items and the combobox itself

### ISSUE THREAD

**Issue by ThomasCybulski** [vaadin/vaadin-combo-box#508]
### Description
I'm using the vaadin-combo-box in version v3.0.0-alpha2 and I want to style the combobox itself and the items. 

### Expected outcome
The combobox has no border and the items on the overlay have a font-size of 20px.

### Actual outcome
The border doesn't disappear and the items on the overlay have the default font-size.

### Live Demo
jsbin is not working with v3.0.0-alpha2

### Steps to reproduce

1. Using the vaadin-combo-box element somewhere in your page.
```html
<vaadin-combo-box items="[[items]]">
	<template>
		<span class="myitems">[[item]]</span>
	</template>
</vaadin-combo-box>
```
2. Add the following CSS styles
```css

vaadin-combo-box {
	border: 0px;
}

.myitems {
	font-size: 20px;
}
```

### Browsers Affected
- [x ] Chrome
- [x ] Firefox
- [x ] Safari
- [x ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by manolo** [comment]
That is not going to work since we detach the overlay part from the original place and move to the body, so styles do not apply anymore.
I suggest different solutions like inlining styles 
```
<span style="font-size: 20px">
```
 or creating your own styled element 
```
<template>
  <my-styled-item item=[[item]]></my-styled-item>
</template>
```

**Comment by web-padawan** [comment]
BTW this is worth documentation like [`<iron-overlay>`](https://github.com/PolymerLabs/iron-overlay#styling-the-content) has. What about adding a section to `<vaadin-overlay>` readme and   pointing to it from other elements?

**Comment by eriklumme** [comment]
@manolo The problem with that approach is that all items get wrapped in `vaadin-combo-box-item`, so I can't remove the padding or change the background color of the overlay.

**Comment by ThomasCybulski** [comment]
Thanks for the comments! 
I've created my own styled element, but the dropdown seems to work much slower.

**Comment by moderndeveloperllc** [comment]
@manolo There is still the issue that since the `border` style is actually on the `vaadin-text-input` _inside_ `vaadin-combo-box`, we can't style that either to make it more material design-like.

**Comment by tomivirkki** [comment]
You can utilize the `vaadin-themable-mixin` (that’s included in all the Vaadin components by default) in styling different parts of the element. Here’s an example that:

1. Removes the border from the text-field
2. Removes the default paddings from `vaadin-combo-box-item`s
3. Sets 20px `font-size` for the items


```
<dom-module id="my-text-field-theme" theme-for="vaadin-text-field">
  <template>
    <style include="vaadin-text-field-default-theme">
      [part~="input-field"] {
        border: none;
      }
    </style>
  </template>
</dom-module>

<dom-module id="my-combo-box-item-theme" theme-for="vaadin-combo-box-item">
  <template>
    <style>
      :host {
        font-size: 20px;
      }
    </style>
  </template>
</dom-module>
```

Just include those on your page before the `<vaadin-combo-box>` import. The mechanism isn’t well documented yet but we’re working on it.

If you want material design look for the text field, it _can_ be done using the style modules as above but there’s already a ready-made (unstable though) package by Vaadin that includes all the necessary modules for Material so all you need to do is to import the module. Take a look at https://github.com/vaadin/vaadin-material-theme.

**Comment by moderndeveloperllc** [comment]
@tomivirkki Thanks for the update. I was able to import `vaadin-material-theme` and that works great. I do hope that the docs progress and y'all keep working on the elements. I've switched most of my app over to your version of the elements, and would hate to switch back!

```
<link rel="import" href="../bower_components/vaadin-material-theme/vaadin-text-field.html">
<link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
```

A note for others who may see this ticket: Many attributes from the `paper-*` equivalents are now in a `theme` attribute. For instance:
```
<vaadin-button theme="raised primary" on-click="_submit" disabled id="searchFormSubmit">Search</vaadin-button>
```
