### ISSUE TITLE
Clicking the toggle button gives inconsistent feedback about the focus state

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#521]
When you click the toggle button, the field is visually focused, but you can’t type in the field. Still, you can use the arrow keys to navigate the menu.

The field should become focused when clicking the toggle button on non-touch devices. On a touch device, the user should be able to open the dropdown without focusing the text input (to prevent the on-screen-keyboard from appearing and obscuring the overlay menu).

**Comment by tomivirkki** [comment]
Seems to be working fine with the latest version. Closing.
