### ISSUE TITLE
Overlay should not close when clearing the field using the clear button

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#523]
If the overlay was open when the user clears the field using the clear button, the overlay should not close.

Edit: I think we should actually open the overlay when the user clears the field using the button, if it was not open before (contrary to what I previously wrote).

**Comment by vicsstar** [comment]
@jouni 2 things.
1. Going over the demos, I see that vaadin-combo-boxes don't have the clear button when there's no item selected. Is that's what's expected? Cause I think it impedes at least one of your comments above.
2. When you edited your comment, were you insinuating that the former thing you said was no longer valid?

**Comment by jouni** [comment]
1. Take a combo box which has a value, focus it -> the overlay opens -> click the clear button -> the overlay closes (it should not)
2. I had previously written that the overlay should not open when pressing the clear button if the overlay is closed. But I changed my thoughts here, and think we should always open the dropdown when the user clears the value. Usually it means the user is going to change it to something else, so we make it easier for them to pick another value.

**Comment by vicsstar** [comment]
Okay, I get it now; sounds good to me.
