### ISSUE TITLE
Major speed regression: Combo box overlay taking multiple seconds to display.

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-combo-box#526]
### Description
Major regression: Clicking on the combo box now can take upwards of 4 seconds to animate approx. 600 items. I don't know if the issue is here, or possibly `vaadin-overlay` as both were updated very recently. On Friday, the display was pretty much instant. I've attached a screen shot of the JS Performance panel in Opera (Chrome basically). It looks like most of the time is being taken up with Polymer property effects when the items are set. Could https://github.com/vaadin/vaadin-overlay/pull/26 be causing this @platosha, @tomivirkki, or @jouni?

### Expected outcome
The close to instant display that _was_ occurring before the weekend.
### Actual outcome
Clicking on the combo-box element causes a 4 second pause as the item is attempting to animate.
### Live Demo
https://jsbin.com/nijaqev/edit?html,output

### Steps to reproduce
1. Put a `vaadin-combo-box` element in the page.
1a. Add LOTS of items to the element
2. Open the page in a web browser.
3. Click the input of `vaadin-combo-box` element.

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [X] iOS Safari
- [ ] Android Chrome
(Probably others too, I'm just testing these right now)

![jsperformance](https://user-images.githubusercontent.com/1920405/30550528-4eeddcd6-9c5d-11e7-8236-074df90546ec.png)

**Comment by moderndeveloperllc** [comment]
@manolo and @platosha, this actually appears to be an issue with `vaadin-themable-mixin` 1.2.0. I've [opened an issue there](https://github.com/vaadin/vaadin-themable-mixin/issues/17). I'm not sure if you wish to move this issue over there or what.

**Comment by platosha** [comment]
Thanks for reporting, we will take a look. I'll leave this one open for now in both places.

**Comment by platosha** [comment]
v1.2.0 of `vaadin-themable-mixin` was deleted until further research on the feature.

**Comment by Waynezhi** [comment]
Hello there,
i upgrade from very old version 1.0 to v3.0.2, to support polymer 2, but i got performance regression: for 500 elements in combobox, it displayed dropdown list immediately, but with the v3.0.2, it takes 2 or 3 seconds.
