### ISSUE TITLE
Overlay has wrong height

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-combo-box#532]
![screen shot 2017-09-20 at 17 38 10](https://user-images.githubusercontent.com/28781210/30650084-b0f4e78e-9e2a-11e7-9e44-901a850c7763.png)

Reproduced with v3.0.0-alpha4 and earlier versions

**Comment by tomivirkki** [comment]
Hi @alexberazouski, You'll probably need to use newer Valo theme

**Comment by jouni** [comment]
This is only fixed in master in Valo right now, but we will tag a new version this week.

**Comment by alexberazouski** [comment]
Thanks. it works with master branch
