### ISSUE TITLE
Double scroll bar when an external mouse is connected

### ISSUE THREAD

**Issue by sayo-vaadin** [vaadin/vaadin-combo-box#537]
When I select a vaadin-combo-box and an external mouse is connected, two scrollbars appear instead of one (see attached screenshot).

This can also be confirmed on https://vaadin.com/elements/vaadin-combo-box/html-examples/combo-box-basic-demos

### Browsers Affected
Confirmed present in Chrome and Firefox. Not present in Safari.

<img width="435" alt="screen shot 2017-09-22 at 6 03 46 pm" src="https://user-images.githubusercontent.com/28782058/30751378-dd5b9320-9fc1-11e7-8b64-05beff5859ef.png">

**Comment by johannesh2** [comment]
On my Win10 Chrome double scrollbars are present even without external mouse connected.

**Comment by limonte** [comment]
The same issue on Chrome/Linux: 

![](https://i.imgur.com/QFGMjc5.png)

**Comment by limonte** [comment]
Everything works fine without https://github.com/vaadin/vaadin-valo-theme/blob/4231a8797e4117d32360325cc0de3aff1ab1a5e8/vaadin-combo-box.html#L58

@jouni can we remove that padding?

**Comment by jouni** [comment]
@limonte, no, I want that padding there visually. So we need to find a way to support this sort of styling.

**Comment by limonte** [comment]
This is still the issue in the default theme: https://jsfiddle.net/6r5htd05/62/

![](https://i.imgur.com/h7TxumE.png)

**Comment by Retlawxx** [comment]
![overlay](https://user-images.githubusercontent.com/3471924/34098304-1e7246fc-e3dc-11e7-8100-a7090b551474.png)
I've noticed that the second bar disappears when removing overflow: auto from the overlay. Is it necessary there?

**Comment by jouni** [comment]
@Retlawxx what version of combo-box are you using? And what browser version?

**Comment by Retlawxx** [comment]
Hi @jouni 
The combo-box version: 3.0.2
My browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by jouni** [comment]
I can’t reproduce this in master, with Valo now as the default theme. macOS Sierra, Chrome/Safari.

**Comment by jouni** [comment]
This should now be fixed, and released in v4.0.0-alpha6
