### ISSUE TITLE
[NFR] Template for item-label-path

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-combo-box#547]
Right now (3.0.0-beta1), you can only select one element of the item to be displayed when the item is selected. This is an issue when you need more than one item. for instance I have:

```
<vaadin-combo-box filtered-items="[[doctors]]" filter="{{doctorFilter}}" item-value-path="doctorId" item-label-path="lastName" id="doctor" name="doctorId" label="Optional: Doctor" colspan="2">
  <template>
    [[item.lastName]], [[item.firstName]] [[[item.city]], [[item.state]]]
  </template>
</vaadin-combo-box>
```
`lastName` is pretty insufficient and looks weird that I display all the info in the dropdown, but not when selected.

Or am I missing something here?

**Comment by tomivirkki** [comment]
Since `item-label-path` can only can only refer to one item sub-property, would it be an option to generate an additional property to each of your items:
```
doctors.forEach(doctor => doctor.label = `${doctor.lastName}, ${doctor.firstName}`);
```

and then use `label` as `item-label-path`?

**Comment by moderndeveloperllc** [comment]
@tomivirkki Thanks, that works great. Should have tired a JS way around it. This is what happens when you make backend devs do frontend work :-D
