### ISSUE TITLE
Overlay is not opened when the input gets focused when tapping on the underline (iOS)

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#55]
Tap on the input underline border focuses the input instead of opening the fullscreen dropdown.

**Comment by jounik** [comment]
You don’t actually need to tap directly on top of the underline. The same thing happens even if you tap some pixels below it. This might be some iOS tap retargeting magic that just focuses the closest input element on the page.

**Comment by tomivirkki** [comment]
The components internals have been renewed since this was reported (not using `<paper-input>` anymore etc). Closing.
