### ISSUE TITLE
Overlay should be hidden if items is empty

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-combo-box#551]
Currently, overlay isn't hidden if there's no items:

![recorded](https://user-images.githubusercontent.com/6059356/31537773-03958cb2-b00c-11e7-9404-d28a438d5ddd.gif)

combo-box 3.0.0 + valo-theme-alpha3

Reproducible here: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha3/demo/combo-boxes.html

Related code: https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-mixin.html#L480

**Comment by web-padawan** [comment]
Fixed by #569
