### ISSUE TITLE
Overlay appears when the element is ready in ready

### ISSUE THREAD

**Issue by ksmlgl** [vaadin/vaadin-combo-box#552]
When the vaadin-combo-box elements placeholder element is set, in ie overlay comes with opened state , so you can not see the placeholder.

Overlay should appear when input is clicked. 

Overlay appear when the document is ready.

1. Put a `vaadin-combo-box` element with the placeholder attribute in the page.
2. Put some items to the the element
3. Open the page with ie
4. The element comes with opened overlay

### Browsers Affected
- [x] Edge
- [x] IE 11

**Comment by limonte** [comment]
Not related to combo-box, it's IE11 "feature" https://stackoverflow.com/questions/14445891/keep-placeholder-on-focus-in-ie10/16138480#16138480
