### ISSUE TITLE
Combobox doesn't show the selected item when the selectedItem property is set while the combobox is not appended to the DOM

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-combo-box#554]
### Description
If you set the property `selectedItem` before adding the combobox to the DOM, the property seems to be  reset - the component doesn't show the selected item.

This directly affects how the component works with Flow. See https://github.com/vaadin/flow/issues/2547

### Expected outcome
The component should show the selection no matter at what time the property was set (before or after attaching it to the DOM)

### Actual outcome
The input field inside the combobox remains empty if you set the property before attaching the component.

### Live Demo
https://jsfiddle.net/6r5htd05/64/

Click on `Append combo` and then click on `Set item` -> it works as expected.
Reset the demo
Then click on  `Set item` before and then `Append combo` -> the value is not shown on the combobox

(You can verify the selected item set by clicking on `Verify item`)

### Browsers Affected
Tested on the browsers below:
- [ x ] Chrome
- [ x ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by limonte** [comment]
I would like every issue report would look like this one.
