### ISSUE TITLE
v2 has bad dependencies

### ISSUE THREAD

**Issue by JosefJezek** [vaadin/vaadin-combo-box#559]
https://github.com/vaadin/vaadin-combo-box/blob/v2.0.0/bower.json#L20

Correct dependencies are

```
"iron-a11y-keys-behavior": "1 - 2",
 "polymer": "1.9 - 2",
...
```

**Comment by web-padawan** [comment]
We no longer support 2.x version and now it is quite outdated. Closing as won't fix.
