### ISSUE TITLE
Vaadin-grid and vaadin-combo-box, label are missing

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-combo-box#564]
### Description
When placed in a `vaadin-grid` cell, the `vaadin-combo-box` labels are not showing in the `vaadin-combo-box-item`.

### Expected outcome
Well, it should show.

### Steps to reproduce
```html
<vaadin-grid ...>
  <template is="dom-if" if="...">
    <vaadin-combo-box items="[[suggestions]]">
    </vaadin-combo-box>
  </template>
</vaadin-grid>
```

where `suggestions` are: 
```javascript
suggestion = [{"label": "123", value: "123"}]
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment]
`items` should be an array containing objects, not an object itself.

**Comment by yveslange** [comment]
Yes sorry, bad copy paste

**Comment by web-padawan** [comment]
@yveslange could you please fork this [jsbin](https://jsbin.com/pabitek/edit?html,output) and reproduce this issue? I'm sorry but I don't quite get what you mean, and your snippet is too small.

**Comment by yveslange** [comment]
Sorry, I wrote on Gitter but forgot to close the issue here. I deleted/re-installed my `bower_components/` and it resolved my issue.
