### ISSUE TITLE
Combobox does not select an item when appended to DOM, but before 'items' are set

### ISSUE THREAD

**Issue by asashour** [vaadin/vaadin-combo-box#580]
### Description
`vaadin-combo-box` does not select an item when appended to DOM, but before `items` are set (Chrome)

### Expected outcome
A combox should always select 'item1', no matter what order the appendChild()/.items/.selectedItem is set

### Actual outcome
In latest Chrome, the first scenario `appendThenSelectedThenItems()` doesn't show selected value, but in FF ESR, it does.

### Live Demo
https://jsfiddle.net/v6mqmcwj/1/

### Steps to reproduce
1. Open the page in a web browser.
2. Click on four buttons
3. Check the added comboboxes

### Browsers Affected
- [X] Chrome
- [ ] Firefox (works)
- [ ] Safari (not tested)
- [ ] Edge (not tested)
- [ ] IE 11 (doesn't show the combobox at all)
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

**Comment by asashour** [comment]
Can someone please confirm if this is a bug, or an expected behavior, before trying to fix it?

**Comment by samiheikki** [comment]
I was creating a fix for it (https://github.com/samiheikki/vaadin-combo-box/commit/57bc3683b38295ebc3d965f05493c5ee6c9e967c), but noticed that it breaks one test.

https://github.com/vaadin/vaadin-combo-box/blob/master/test/using-object-values.html#L115 (should use toString if provided label and value paths are not found). So to me it sounds like it should not `selectedItem` if it is not found in `items`, but not sure. @tomivirkki care to weigh in here?
