### ISSUE TITLE
Only mouse wheel scroll is working in Vaadin combo box for IE

### ISSUE THREAD

**Issue by udayghulaxe** [vaadin/vaadin-combo-box#583]
### Description
**Vaadin combo Box v1.3.3**
Vaadin combo box allows scrolling through only mouse wheel. Vaadin combo box gets close if  I try using right scroll bar to scroll through list of items. 

### Expected outcome
List of items should be scroll-able with right scroll bar also on IE 11.

### Actual outcome
Vaadin combo box gets close if  I try using right scroll bar to scroll through list of items on IE 11.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Hi @udayghulaxe, confirmed the issue with the version 1.3.3. Is it an option for you to use a newer version instead? Versions 2, 3, and 4 no longer seem to have the scrollbar issue on IE.

**Comment by porterfc** [comment]
I am also having this issue and cannot use a newer version because they are not compatible with Polymer 1.0 and ES5. Any chance you can identify what the fix in the newer versions was?
