### ISSUE TITLE
Demo: comboxes lose data after navigation

### ISSUE THREAD

**Issue by asashour** [vaadin/vaadin-combo-box#584]
### Description
In `basic examples` demo,  all comboboxes lose data after coming back from e.g. `object items` view.

### Expected outcome
When coming back, the comboboxes should have same values (at least initial).

### Actual outcome
the comboboxes are empty, and all items are empty.

### Steps to reproduce
1. Run `polymer serve --open`, the browser opens
2. Add `demo`, e.g. http://127.0.0.1:8080/components/vaadin-combo-box/demo
3. You will see in "Configuring the Combo Box" comoboxes, "Element" has all elements values, and "Read Only" value is "Carbon".
4. Click "Object Items" to navigate away
5. Click "Basic Examples" to return back.
6. You expect the "Element" to have all values, "Read Only" to have "Carbon", but they are all empty, same thing applies to all comboboxes in the view.

### Browsers Affected

- [X] Chrome Latest
- [X] Firefox 52 ESR
- [ ] Safari (not tested)
- [ ] Edge (not tested)
- [X] IE 11
- [ ] iOS Safari (not tested)
- [ ] Android Chrome (not tested)

**Comment by tomivirkki** [comment]
Confirmed. But this is actually an issue of [`vaadin-demo-helpers`](https://github.com/vaadin/vaadin-demo-helpers)
