### ISSUE TITLE
Error when converted to es5

### ISSUE THREAD

**Issue by aruntk** [vaadin/vaadin-combo-box#587]
### Description

I'm using vaadin-combo-box(version 3.0.2) after converting to es5. It is showing an error `Cannot read property 'input' of undefined` at

```js
#line no 313
get inputElement() {
  return this.$.input;
}
```
I've included custom-elements-es5.js from webcomponentsjs.

value of `this` inside inputElement is `vaadin-combo-box` but value of `this.$` is `undefined`. Please help.

### Browsers Affected

- [x] Chrome - checked in chrome only
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by aruntk** [comment]
## Update

If I downgrade the package to version `2.x` then it works fine.

**Comment by aruntk** [comment]
## Update

Same issue is found in `vaadin-date-picker` element.

**Comment by samiheikki** [comment]
I'm unable to reproduce the issue. How are you using the es5 transpilation and what version of chrome?

My workflow was:
1) `polymer init` and select `polymer2-starter-kit`
2) `bower i vaadin-combo-box#3.0.2 && bower i vaadin-date-picker#2.0.7`
3) Imported and added combo-box and date-picker to `my-view1.html`
4) Run`polymer build`
5) `cd build/es5-bundled`
6) `polymer serve`
7) Everything works on Chrome (63) and FF & Safari too.

**Comment by tomivirkki** [comment]
Please re-open if still relevant
