### ISSUE TITLE
Second press of up arrow should focus the dropdown

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-combo-box#59]
Opening the dropdown can be done with up or down arrow keys. However only down arrow can be used to bring focus to the first (or selected) item of the dropdown.

This feels a bit weird when the dropdown is positioned above the input field. It would probably make more sense to focus the dropdown item also on a second up key press.

**Comment by jounik** [comment]
Why not focus it directly when the dropdown opens?

**Comment by jounik** [comment]
Ping @tuomasnironen

**Comment by tuomasnironen** [comment]
My initial feeling was that it would feel natural to handle opening the dropdown with one keypress and focusing on the first item on the second keypress. I would argue this case if the user wants just to see first what kind of options there are available before implying with focus that he has already selected one (even thought the item would not get selected if the user chooses to abort with "Esc" key or a pointer event on another component etc.)

But I see the advantages of opening dropdown and focusing on the first/selected item with just one keypress = less user actions needed to make a selection (and maybe understanding better what would happen with the next up/down keypress -> changing the focused item). I suggest we'll do A/B comparison in the next end user testing round to validate which one is preferred.

In any case, the dropdown opening below or above the input with the keyboard should function similarly on both instances. Either the first/selected item gets focused with just one keypress, or then both require also the second keypress.

**Comment by jounik** [comment]
When there’s an existing selection, that item is immediately selected when you press key up/down and the dropdown opens, and the keyboard focus is also on that item. I think it should work like that even if you don’t have an item selected. But I’m okay with A/B testing this also.

About pressing key up: should it actually start highlighting items from the bottom of the list? I mean, even if the dropdown opens above the field when you press key down, it should still start at the top of the list, right? So just thinking it should work symmetrically the other way around.

**Comment by tuomasnironen** [comment]
That would be symmetrical, yes, but what about the case when the items is so long it doesn't fit the viewport and needs a scrollbar? I would find it annoying in such cases when the items are ordered e.g. alphabetically (you won't see the items at the start, that would make the ordering easier to grasp) or when the most important items are placed at the top. Maybe A/B test this, too?

**Comment by jounik** [comment]
That situation should be the expected case, as the element is designed for large data sets. But how often do people actually use the up arrow key to open a dropdown? It might be a “power user” feature and they could grasp it quicker and find it valuable from time to time. And it would be easy to revert it by pressing esc and the key down to start from the top again.

But yeah, starts to sound like an A/B or double-blind test (the latter requiring less participants).

**Comment by tuomasnironen** [comment]
- Define the optional prototypes
- Build prototypes
- A/B test prototypes
- Report test findings to PO

**Comment by jounik** [comment]
The current implementation of having to press the down arrow twice in order to highlight an item in the list (if the input is currently empty) was decided to be “correct”.

Further design regarding keyboard navigation is done in #87
