### ISSUE TITLE
Demo examples issues

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-combo-box#593]
### Description
I guess this look isn't intentional:

![](https://i.imgur.com/4VNZFUt.png)

### Live Demo
https://cdn.vaadin.com/vaadin-combo-box/4.0.0-alpha3/demo/#combo-box-item-template-demos

**Comment by web-padawan** [comment]
This should have been fixed in #590 but that PR had not handle all the demos.

We probably should drop these demos for now, like we did for `vaadin-context-menu` (removed `paper-listbox` integration demo). @jouni WDYT?

**Comment by jouni** [comment]
The reason for this particular rendering issue is that `vaadin-combo-box-item` is a flex container and not a block container like before.

**Comment by limonte** [comment]
should an item have `flex-direction: column` by default?

**Comment by jouni** [comment]
> should an item have flex-direction: column by default?

The selected item icon is placed using the row flex container, so no 😕

**Comment by jouni** [comment]
For this example/demo specifically, I’m not sure what the benefit is. These state attributes should be documented in the styling documentation, and not as an example how to use the element, IMO.

**Comment by jouni** [comment]
Related: https://github.com/vaadin/vaadin-item/issues/17
