### ISSUE TITLE
Native outline appears when clicking above the label

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#597]
### Description
![focus](https://user-images.githubusercontent.com/10589913/34612565-1febd8a8-f233-11e7-8a04-102f63fd665f.gif)

### Expected outcome
There should be no native outline I guess.

### Actual outcome
The native outline appears (especially funny in Safari).

### Live Demo
https://jsfiddle.net/webpadawan/44hksom1/

### Steps to reproduce
1. Put a `vaadin-combo-box` element in the page.
2. Add a label attribute
3. Open the page in a web browser.
4. Click the label of `vaadin-combo-box` element
5. Click a few pixels above the label

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment]
Why is the host element focusable anyway?

**Comment by web-padawan** [comment]
The area above the label is caused by [this style](https://github.com/vaadin/vaadin-text-field/blob/master/theme/valo/vaadin-text-field.html#L52). BTW date-picker does not have that margin, should we eliminate it in combo-box for consistency?

**Comment by web-padawan** [comment]
Note: also valid for `vaadin-dropdown-menu`

**Comment by jouni** [comment]
Yeah, I have a TODO that I should unify those margins.

**Comment by web-padawan** [comment]
Fixed in 677eecb
