### ISSUE TITLE
Overlay content theme padding inconsistent with vaadin-dropdown-menu

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#598]
### Description

`vaadin-combo-box` does not have padding around the content, see [this line](https://github.com/vaadin/vaadin-combo-box/blob/master/theme/valo/vaadin-combo-box-dropdown.html#L10)
![screen shot 2018-01-09 at 15 22 15](https://user-images.githubusercontent.com/10589913/34722952-801d4a38-f551-11e7-9d4c-21eea196ae82.png)

This causes the missing space around the first item at the top, and the last one at the bottom, which feels not so nice in comparison with `vaadin-dropdown-menu`:

![screen shot 2018-01-09 at 15 22 25](https://user-images.githubusercontent.com/10589913/34723049-dafc7dde-f551-11e7-994a-fff10b24054a.png)

Changing the padding to the following seems to fix this:
```css
[part="content"] {
  padding:  var(--valo-space-xs) 0;
}
```

**Comment by jouni** [comment]
Yeah, a known issue. I didn’t find a way to fix this without introducing double scrollbars for the combo-box overlay. Feel free to experiment if you can.
