### ISSUE TITLE
Src version icons are missing

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-combo-box#607]
<img width="350" alt="screenshot 2018-01-30 14 54 59" src="https://user-images.githubusercontent.com/1222264/35567419-afc2685e-05cd-11e8-9432-5cbd3953d9b7.png">

**Comment by jouni** [comment]
It’s debatable if we should bundle any icons with the src version. It’s meant to be unstyled, and not contain any unnecessary bytes, right?

**Comment by tomivirkki** [comment]
Ok for me, as long as it's aligned across elements. Currently, the other elements with icons do ship them with src versions.

**Comment by web-padawan** [comment]
Now when we also have #745 this one is controversial, and I think we agreed about the fact that current generation of unstyled components is OK to not include any icons. So, closing this one.
