### ISSUE TITLE
Unselecting is impossible on fullscreen mode

### ISSUE THREAD

**Issue by jojule** [vaadin/vaadin-combo-box#61]
After selecting an item, it is impossible to get back to initial state where nothing was selected. We should not force people to reload the page as an only way of getting back to unselected state. (tested on iPad only). 

Natural way of implementing this would be to unselect when one deletes the selection with keyboard.

**Comment by Saulis** [comment]
You should be able to unselect everything by clearing the value from the input field and hitting enter using the keyboard.

**Comment by jojule** [comment]
Argeed. Entrer does not nothing on ipad.
