### ISSUE TITLE
Allow remove selected icon on overlay content

### ISSUE THREAD

**Issue by jariberi** [vaadin/vaadin-combo-box#611]
I actually do it like this:

```html
<dom-module id="trineo-vaadin-combo-box-overlay-theme" theme-for="vaadin-combo-box-overlay">
    <template>
        <style>
            [part="content"] vaadin-combo-box-item::before {
                display: none;
            }
        </style>
    </template>
</dom-module>
```

But that applies on all occurrences of component.

**Comment by jouni** [comment]
Hi!

I would like to understand the need for hiding the checkmark. And if I understood correctly, you would only want to hide it for some combo boxes, not all?

**Comment by jariberi** [comment]
Yes, that's right

**Comment by jouni** [comment]
Closing. #48 tracks the generic fix for this issue.
