### ISSUE TITLE
How to reset text input?

### ISSUE THREAD

**Issue by ropoman** [vaadin/vaadin-combo-box#612]
I am using ComboBox with .setTextInputAllowed(true). When I type characters into the combo box it filters the values. 
I have three options to close the combo box:
1. select one of the filtered values
2. click somewhere else in the form to close the combo box
3. close the form
In case 3 I have the problem that the combo box is still filtered when I open the form again. Tried with Firefox, Chrome and Edge

**Comment by jouni** [comment]
This issue was moved to vaadin/framework#10608

**Comment by jouni** [comment]
I’m assuming you are using Vaadin Framework 6/7/8, judging from the `setTextInputAllowed` method.
