### ISSUE TITLE
Don’t open the overlay when clearing the field using the “clear” button

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#613]
### *Proposal for discussion*

The current behavior (focusing the field and opening the overlay) assumes the user would more often want to enter a new value when clearing the field.

A better assumption is that the user just wants to clear the field (common for filtering fields).

If they want to enter a new value, it’s more likely they will focus the field directly, and in that case, the overlay will open, so it’s quick to select another value from it.

The field should still become focused when pressing the “clear“ button with a mouse (current behavior). But, when pressing the “clear” button on a touch device, the field should not be focused to avoid the on-screen keyboard from popping up (which would be annoying when clearing filtering fields for example).

**Comment by jouni** [comment]
If we agree to change this, the same should be applied for `vaadin-date-picker` as well.

Also, eventually relevant: https://github.com/vaadin/vaadin-text-field/issues/92

**Comment by web-padawan** [comment]
This was implemented in #523 and some users were confused with the change, especially during UX test. One of the participants suggested to only open overlay again if the combo-box is required. So I'm happy with reverting this change, but I wish we could figure this out before beta 😞

**Comment by jouni** [comment]
> This was implemented in #523 and some users were confused with the change, especially during UX test.

Yes, I’m to blame for being a little bullish on this, trying to force consistency at the expense of usability.

> One of the participants suggested to only open overlay again if the combo-box is required

Don’t remember hearing that. I do remember hearing a suggestion that we should hide the clear button if a field is required, which encourages similar user behavior. As the developer can hide the clear button for required fields using a theme, I haven’t considered that as a must-have core feature.

> So I'm happy with reverting this change, but I wish we could figure this out before beta

Completely agree. But better do it before final, right? 😉 

If there’s consensus within the team, could someone prepare a PR, and we can have a quick test for it?

**Comment by jouni** [comment]
I’m currently under the assumption that we agree that this would be a change for the better.

@tomivirkki, this should then be done before the next beta, right?
