### ISSUE TITLE
blue tick in vaadin combo

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-combo-box#616]
Can anyone please tell me where is code that makes the blue tick appear beside a selected item in vaadin combo box?

**Comment by web-padawan** [comment]
This style is inherited from `vaadin-item` styles defined [here](https://github.com/vaadin/vaadin-item/blob/master/theme/lumo/vaadin-item.html#L26).
See also #611

**Comment by jouni** [comment]
Hi! Please use http://gitter.im/vaadin/vaadin-core-elements for questions. I’m closing this as a non-issue.
