### ISSUE TITLE
How to deselect an already selected item from dropdown menu

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-combo-box#617]
Is there a way to deselect an already selected item from combo box dropdown menu?
I have found out the method "_isItemSelected" [in vaadin-combo-box-dropdown-wrapper.html] which is called for all items in the menu whenever we change the selected item from menu. But when one clicks an already selected item this method is not called. How to call this method even when one clicks an already selected item?

**Comment by jouni** [comment]
Do you want the end user to be able to clear the selection, or do you just need to do that programmatically?

The end user can clear the value by clicking the “clear“ button inside the field. Programmatically it can be done with `combobox.value = '';`.

The items are not “togglable” if that’s what you are looking for.

**Comment by sudipta1411** [comment]
I just want the blue tick to be gone once I click an already selected item from the dropdown menu.

**Comment by jouni** [comment]
That’s not how the component is designed to be used, unfortunately. When we get to implement multi-select (#88), it might become a relevant interaction behavior, that you can toggle items directly from the dropdown. Though, I think we won’t do it for multi-select either.

Do you have examples of combo boxes that have the behavior you are looking for?

**Comment by jouni** [comment]
Closing, as this is not how the component is designed to be used. If you disagree, please add comments and, if you can, provide use cases or examples how you think it should work instead.

**Comment by tkdphoenix** [comment]
I have a use case where you can select from a list of people. Once selected, the dialog box is closed which houses the `vaadin-combo-box`. Also, you can choose to close the dialog box without selecting one. In my case, I tested the flow where a user selects someone and then decides to close the dialog box. If the `vaadin-combo-box` isn't cleared, then if  the dialog is reopened in the same session, the formerly selected person is still populated. the answer is to call the mixin method `_clear()`. Ex:
`combobox._clear()` and the person's name disappears, and they are not selected when the list of people  are pulled up again.
