### ISSUE TITLE
Regression: Dropdown opening speed when using dom-if/dom-repeat

### ISSUE THREAD

**Issue by flyweight** [vaadin/vaadin-combo-box#618]
### Description

Dropdown is really slow to open when wrapped in a dom-if/dom-repeat and has many items.  
Possibly relates to #605 - using version 3.0.3

### Expected outcome

Dropdown should not be slow to open.

### Actual outcome

Dropdown seizes DOM for several seconds before opening.

### Live Demo

https://jsbin.com/goyutetixi/1/edit?html,console,output

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
This actually can be reproduced without `dom-if` and only occurs in polyfilled browsers, especially Firefox. It works wine in Chrome and Safari. So it looks like the fix shipped in v3.0.3 was insufficient.

**Comment by web-padawan** [comment]
Added the [Glitch project](https://glitch.com/edit/#!/deeply-plow?path=my-element.html:31:23) for easier debugging.
