### ISSUE TITLE
Arrow key selection broken on fullscreen mode

### ISSUE THREAD

**Issue by jojule** [vaadin/vaadin-combo-box#62]
When iPad is attrached to an extgernal keyboard, it is impossible to navigate between items on up and down keys.

**Comment by jounik** [comment]
Most likely because keyboard nav is only implemented for the dropdown mode and not for the fullscreen mode. No reason why it couldn’t work there also, though.

**Comment by Saulis** [comment]
Related with #60
pe 27. marraskuuta 2015 klo 21.48 Jouni Koivuviita <notifications@github.com>
kirjoitti:

**Comment by Saulis** [comment]
Verified that iOS devices don't fire keydown events properly with arrow keys, so the fix only applies to Android devices running fullscreen mode. Tested with a BT keyboard on iPad mini running iOS 8.4 with Safari and Chrome + Nexus10 running Android 4.4.

Some discussion in Stack regarding the issue: http://stackoverflow.com/questions/14959048/how-to-detect-key-down-event-for-arrow-key-on-textarea

**Comment by jounik** [comment]
Would be nice to try on iOS9 as well, if anything has changed there.

**Comment by jounik** [comment]
Same result on iOS9.

**Comment by Saulis** [comment]
Furthermore, ESC doesn't fire any events at all.
