### ISSUE TITLE
[Question] _maxOverlayHeight() item limit + overlay height

### ISSUE THREAD

**Issue by justinribeiro** [vaadin/vaadin-combo-box#630]
When using 4.0.0-beta4, it appears that the maximum combo-box height is controlled in the `vaadin-combo-box-dropdown-wrapper.html` private method `_maxOverlayHeight`.

I have two questions regarding this:

1. `const minHeight = 116;` which the comment notes is the height of two items in the combo-box. Should this variable be hoisted to public so that it is configurable by end developers?

2. `const bottom` determines the min between the `window.innerHeight` and the math of `scrollHeight-scrollTop`. This has the side effect that if page has no scroll but has room for the combo box to be taller, it will default to 116px due to the math in the return statement `Math.max(bottom - targetRect.bottom - margin, minHeight) + 'px'`. A simple addition of a case to check for `bottom = 0` results in a better experience:

```
// Presuming the change `const bottom` to `let bottom`, when we have 
// no scroll on the page, we can expand beyond the min list count of two 
// to something more comfortable
if (bottom === 0) {
 bottom = window.innerHeight;
}
```

Note, the current documentation notes that `--vaadin-combo-box-overlay-max-height` will set the scroller overlay style, but the current code path in `_setOverlayHeight()` doesn't take that into account when setting `MaxHeight` for the dropdown overlay (and I'm not saying it should, it's just unclear as to what changes the current list height).

Current behavior:
![image](https://user-images.githubusercontent.com/643503/37484018-91275d8e-2844-11e8-9219-a4f971731903.png)

After `bottom === 0` check:
![image](https://user-images.githubusercontent.com/643503/37484037-9ec71358-2844-11e8-9dc7-f2dd53c11ff4.png)

Thoughts appreciated. Happy to submit a pull request if either 1 or 2 above make sense, or happy to close if I've simply missed a potential solution to the items viewable at default.

**Comment by mpilone** [comment]
I ran into this issue as well where I can't get the overlay to display more than ~3.5 items. In one case the combo box is in a `position: sticky`, scrollable div and scrollHeight and scrollTop report 0. This results in minHeight being used.

![all 2020-01-13 10-54-08](https://user-images.githubusercontent.com/3026098/72272036-f44a6f80-35f5-11ea-9721-c87b68188256.png)

<img width="1473" alt="CRABWall All Transmissions 2020-01-13 11-16-43" src="https://user-images.githubusercontent.com/3026098/72272303-6622b900-35f6-11ea-9d30-862893bb6139.png">


In a second case, if the body of the document is shorter than the the actual window size which causes the minHeight to be used. In this case you can hack/make the overlay larger by adding a `<div style="height: 500px"></div>` after the combo box to extend the height of the body.

<img width="869" alt="Bug Report 2020-01-13 11-19-08" src="https://user-images.githubusercontent.com/3026098/72272572-dc272000-35f6-11ea-82e4-3547c1afa18e.png">

**Comment by web-padawan** [comment]
Thanks for the additional use case helping to reproduce. I think we should fix this.
