### ISSUE TITLE
Cannot update a combobox in a dialog on tablet/phone

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-combo-box#634]
@jcgueriaud commented on [Tue Mar 27 2018](https://github.com/vaadin/flow/issues/3774)

Hello,

When I click on a combobox inside a dialog with my android tablet or my android phone (I use Google Chrome), I can't select a element.

The same combobox outside the dialog is working. I don't have any problem on computer.

See my example below.
Steps to reproduce:
- Click on OPEN button.
- Click inside the combobox (not on the arrow)
---> The keyboard is opened
- select an element
--> This element is not selected and the keyboard is closed

    /*** The main view contains a button and a template element.
     */
    @BodySize(height = "100vh", width = "100vw")
    @HtmlImport("styles/shared-styles.html")
    @Route("")
    @Theme(Lumo.class)
    public class MainView extends VerticalLayout {
    
    
        private ComboBox<String> comboBox;
    
        private Dialog editPopup;
        private Button openButton;
    
        public MainView() {
    
            comboBox = new ComboBox<>("Test");
            String[] data = {"Label 1","Label 2","Label 3","Label 4"};
            comboBox.setItems(data);
            editPopup = new Dialog();
            editPopup.add(comboBox);
            openButton = new Button("Open");
            openButton.addClickListener(event -> editPopup.open());
    
            add(openButton);
    
            setClassName("main-layout");
        }
    
    }

---

@pleku commented on [Wed Mar 28 2018](https://github.com/vaadin/flow/issues/3774#issuecomment-376768560)

Hello and thanks for the report. From looking at the code, I think the issue is with the web component and how it works inside a `vaadin-dialog`, thus I'm moving it to the web component repository.

**Comment by limonte** [comment]
Confirming the issue both for Android and iOS devices, jsfiddle: https://jsfiddle.net/6r5htd05/204/

Live demo: https://jsfiddle.net/6r5htd05/203/embedded/result/

**Comment by manolo** [comment]
Working on this I realised that it's not only an issue inside dialog, but also reproducible if we  have a combo-box with some CSS in the body like this code where combo-box is displaced from top using a margin:

```
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
    <base href="bower_components/">
    <script src="webcomponentsjs/webcomponents-lite.js"></script>
  </head>
  <body>
    <vaadin-combo-box id="combo-box" items='["uno", "dos", "tres"]' style="margin-top: 200px"></vaadin-combo-box>
  </body>
</html>
```

**Comment by manolo** [comment]
Actually it can be reproduced just opening demo of the element, and focusing any combo placed under the room occupied by the soft keyboard. Seems that always that the combobox needs to be scrolled when the keyboard opens
