### ISSUE TITLE
<style include=""> does not work when element is wrapped in <template> (polyfill)

### ISSUE THREAD

**Issue by flyweight** [vaadin/vaadin-combo-box#636]
*Wasn't 100% sure where to log this*

### Description
When using `<style include="">` to extend the default theme, if the combobox is wrapped with `<template>` tag, it loses the styles in browsers that need polyfills.

https://github.com/vaadin/vaadin-themable-mixin/wiki/Extending-the-Default-Theme-Module

### Expected outcome
Dropdown background should be dark.

### Actual outcome
Run in Chrome, note background for dropdown is dark.
Run in Firefox, note background for dropdown is white.

### Live Demo
http://jsbin.com/reravoqiya/edit?html,css,js,output

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
@flyweight no need to clean the issues like this. Just to ensure, have you solver your problem with styles? Or do we need to add some clarification to the ThemableMixin docs?
