### ISSUE TITLE
Set multiple fields for itemLabelPath

### ISSUE THREAD

**Issue by wouterz** [vaadin/vaadin-combo-box#643]
### Description
item-label-path only allows for one value to be set, is there a way to have multiple?

``` html
  <vaadin-combo-box items="[[users]]" item-label-path="first_name">
      <template>
             [[item.first_name]] [[item.last_name]]
    </template>
</vaadin-combo-box>
```

Desired: Show both first_name and last_name of the selected item

**Comment by web-padawan** [comment]
Thanks for the issue. It does not make much sense to introduce this functionality, since the user might also need to include arbitrary separators etc, and all this logic should be considered as app-specific.

So you can use it e. g. like this:
```js
this.users = data.map(user => {
  return {
    label: `${user.first_name}  ${user.last_name}`,
    ...
  }
});
```
