### ISSUE TITLE
Animation design

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#65]
- Dropdown open and close
- Loading indicator (when lazy loading data source has been implemented)
- Item selection

**Comment by manolo** [comment]
the overlay is now implemented using vaadin-overlay, moving this feature to https://github.com/vaadin/vaadin-overlay/issues/36

**Comment by jouni** [comment]
This issue was about more than just the overlay animations. And, similarly as with date picker, the open/close animations for the overlay might be customized for the combo box specifically.

The other animations are more interesting here than the overlay open/close. I want to keep this open still so I remember to come back to it someday.

**Comment by manolo** [comment]
But shouldn't have animations the overlay, and the element consuming it enable/disable it ?

**Comment by jouni** [comment]
Yes, the overlay can have a default animation for the overlay, but a specific component might want to override that. Not saying our current combo-box is one, so no issue there, but there are the other animations listed in this issue, that I would like to come back to at some point.

That said, I can put these in my personal TODO, so they don’t pollute the issue list here on GitHub.
