### ISSUE TITLE
There is not link for demo or api in v4.0.1

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-combo-box#659]

**Comment by web-padawan** [comment]
The 4.0.2 version is the latest included in V10 LTS and there is a demo link there:
https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.0.2

So, I think this should be closed. Unfortunately we can not deploy 4.0.1 now, as I had to pin some of the dependencies in 978b8884e473c64726d1fc65d3688db663fe08de before releasing 4.0.2 to avoid bower conflicts.
