### ISSUE TITLE
Editable Combo box

### ISSUE THREAD

**Issue by osamamaruf** [vaadin/vaadin-combo-box#663]
### Description
Provide a mechanism/documentation to add new items to the vaadin-combo-box.

### Expected outcome
Vaadin combo box should provide mechanism to add items e.g.

https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box

### Actual outcome
Cannot add new items.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by osamamaruf** [comment]
`
  /**
         * If `true`, the user can input a value that is not present in the items list.
         * `value` property will be set to the input value in this case.
         * Also, when `value` is set programmatically, the input value will be set
         * to reflect that value.
         */
        allowCustomValue: {
          type: Boolean,
          value: false
        },
`

Found the above snippet in `vaadin-combo-box-mixin.html`. :)

Can this mentioned in the docs as well [here.](https://vaadin.com/components/vaadin-combo-box/html-examples)

**Comment by web-padawan** [comment]
It is mentioned, actually. See the "Allow Custom Values" demo [here](https://vaadin.com/components/vaadin-combo-box/html-examples/combo-box-basic-demos). Is it clear enough for you, or maybe you suggest making a slightly more verbose description?

**Comment by osamamaruf** [comment]
It would be better if its made more verbose. 'Custom Values' to me is a bit misleading. It would be good if  'editable' can also be use to describe it.

**Comment by samiheikki** [comment]
To me `Custom Values` sounds better than `editable`. Editable sounds like you could edit the combo-box items (add/update/remove them) where as custom value is used only for one custom value.
