### ISSUE TITLE
Combobox dropdown flickers when disappearing

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-combo-box#664]
1. Open https://vaadin.com/components/vaadin-combo-box/html-examples/combo-box-basic-demos
2. Enter "bar" in the first combo box to filter out all item except one
3. Click on "Barium"

Expected behavior:
The dropdown is closed

Actual behavior:
The dropdown is resized to show 15 rows, then closed

**Comment by tomivirkki** [comment]
No longer an issue
