### ISSUE TITLE
Question: how to apply "paper" theme to <vaadin-combo-box>?

### ISSUE THREAD

**Issue by mflorence99** [vaadin/vaadin-combo-box#665]
My apologies if I'm asking this question in the wrong place!

We've been using `<vaadin-combo-box>` for a some time and in combination with the `<paper-...>` Web components. Until now, the Vaadin component has fit perfectly in the UI. We are upgrading to Polymer 3 to unify module processing, tree shaking etc etc.

How do we apply the original "paper" styles? It appears that only "lumo" theming is available.

Many thanks for any help!

**Comment by jouni** [comment]
No worries, you can ask questions here as well. The [Gitter chat](https://gitter.im/vaadin/web-components) or the [Polymer Slack #vaadin channel](https://polymer.slack.com/messages/C6ULJ2F7S) are probably more appropriate for questions, though 😃 

There’s the Material theme you can use for all Vaadin components: https://cdn.vaadin.com/vaadin-material-theme/0.4.0/demo/combo-boxes.html

It’s currently considered alpha quality, and not directly available for Polymer 3, but I assume you could run it through the Polymer modularizer.

**Comment by mflorence99** [comment]
Many thanks for your quick reply @jouni! The link you quoted however uses `bower` for installation and HTML imports for inclusion. We need to move away from them and use `npm` exclusively, together with standard JS module imports so that we can take advantage of standard Angular CLI bundling and tree-shaking capabilities. Indeed, all that works perfectly with the 4.0.1 version of `<vaadin-combo-box>` -- only the `lumo` theme is a problem. 

Am I missing something obvious? If not, I'll try the Slack channel for follow up.

**Comment by jouni** [comment]
Yeah, I expected something like that. We are moving towards npm, and all other packages are already there. The Material theme is currently under development, and is lagging a bit behind.

If you’re eager, you could try the [polymer-modularizer](https://github.com/Polymer/polymer-modulizer) yourself to convert the theme packages to JS modules.

**Comment by mflorence99** [comment]
Thanks @jouni -- I might just try that! In the meantime I'll look out for updates to the Material theme.

**Comment by jouni** [comment]
No problem – and I realized I forgot to actually link to the [Material theme repo](https://github.com/vaadin/vaadin-material-theme) 🤦‍♂️ (you probably found it already, though)
