### ISSUE TITLE
CustomElementRegistry's define method failing on 'vaadin-item' of vaadin-combo-box

### ISSUE THREAD

**Issue by stackt52** [vaadin/vaadin-combo-box#674]
I have two custom elements that I've defined and I'm lazy-importing each depending on which I navigate to first. The first element has `vaadin-combo-box` element import on in, and the second element has `vaadin-dropdown-menu` element import on it. If I navigate to the second element first (the one having `vaadin-dropdown-menu` element on it) and then try to navigate to the first element (the one having `vaadin-combo-box` element on it) I'm getting this error in the console:

`vaadin-item.js:78 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at http://localhost:8081/node_modules/@vaadin/vaadin-combo-box/node_modules/@vaadin/vaadin-item/src/vaadin-item.js:78:16`

And if i try to navigate to the first element first, before the second element is upgraded everything seems to work. But when I then navigate to the second element I again get the same error in the `console` and everything breaks.

When I looked at both `vaadin-combo-box` and `vaadin-dropdown-menu` I discovered both are importing the `vaadin-item` from `node_modules` that is in it's directory - which would cause issues when importing elements of the same name installed in a different `node_modules`. (with `vaadin-dropdown-menu` it even imports `vaadin-text-field` in it's `node_modules`, making every `vaadin-text-field` element imported from a different `node_modules` in any element where it is used to fail, because of the name collision) 

Element One's imports:
`import { PolymerElement, html } from '@polymer/polymer/polymer-element.js';`
`import '@polymer/iron-form/iron-form.js';`
`import '@vaadin/vaadin-text-field/vaadin-text-field.js';`
`import '@vaadin/vaadin-combo-box/vaadin-combo-box.js';`

Element Two's imports:
`import { PolymerElement, html } from '@polymer/polymer/polymer-element.js';`
`import '@polymer/iron-form/iron-form.js';`
`import '@vaadin/vaadin-dropdown-menu/vaadin-dropdown-menu.js';`
`import '@vaadin/vaadin-list-box/vaadin-list-box.js';`
`import '@vaadin/vaadin-item/vaadin-item.js';`

[And when I looked at Polymer 3 FAQ
](https://www.polymer-project.org/blog/2018-05-25-polymer-elements-3-faq.html) trying to read more about the CustomElementRegistry issue I saw this: 

> This is a symptom of duplicate dependencies installed. If you're adding new element dependencies (like paper-button) to your app, be sure you don't end up installing multiple, nested copies of Polymer. The best way to do this is to start with a fresh set of dependences (rm -rf node_modules/ package-lock.json; npm i).

> If that still doesn’t fix your problem, double check that you’re not accidentally importing multiple copies of Polymer: do you see multiple requests of polymer-legacy.js or paper-button.js (or whatever element you’re importing) from different node_modules/ in the network timeline? Are there multiple versions of Polymer in your package-lock.json?

I'm working with Polymer 3 and vaadin-combo-box and vaadin-dropdown-menu Polymer 3 and ES Modules compatible versions.
I'm using the google chrome browser.

The same error will  happen also  for elements that has `vaadin-text-field` import on it with other element that have `vaadin-dropdown-menu` element import on it.

Any help how I can solve this?

**Comment by web-padawan** [comment]
Hi, which versions of the components do you have? You can take a look at the [polymer3-webpack-starter](https://github.com/web-padawan/polymer3-webpack-starter) and check with the versions there, and probably need to regenerate the lockfile.

>When I looked at both vaadin-combo-box and vaadin-dropdown-menu I discovered both I importing the vaadin-item from `node_modules that is in it's directory - and suspected that maybe that could be the issue.

AFAIK, polymer-cli was promised to resolve the dependencies in this case also, but it appears that it is not always true, and cannot be true until they ship some "deduplication" postinstall transform.

For now, we are doing batched updates of Vaadin components npm versions, ensuring that there is no components depending on different versions. But in case if you mix newest alphas with older preview versions, you will most likely run into this issue.

**Comment by stackt52** [comment]
@web-padawan I upgraded my vaadin elements from preview versions to alpha and everything starts working fine. Thanks very much
