### ISSUE TITLE
Items property changes dynamically, dropdown not changing properly.

### ISSUE THREAD

**Issue by Top-Developer** [vaadin/vaadin-combo-box#676]
### Description
The one element of items array is removed, i.e. length `vaadin-combo-box` items property is reduced, but dropdown still shows the removed item.

### Expected outcome
Hide the removed item.

### Actual outcome
Shows removed item.

### Steps to reproduce

1. Put a `vaadin-combo-box` element in the page.
2. Set items property as [1, 2, 3]
3. Remove 2
3. The dropdown shows 1, 3, 3

### Browsers Affected
I tested on Chrome.

Thank you.

**Comment by marcushellberg** [comment]
How are you removing `2`? Are you using the Polymer array methods that notify the data binding system of property changes? (https://www.polymer-project.org/3.0/docs/devguide/model-data#array-mutation)

You will either need to:
1. Assign a new array without the second element to your property `this.myarray = [...this.myarray.slice(0, 1), ...this.myarray.slice(2)]
2. Use Polymer's array syntax `this.splice('myarray',  1, 1)

**Comment by tomivirkki** [comment]
Seems to be working fine when modified trough Polymer accessor methods.

**Comment by Top-Developer** [comment]
No, I am using polymer 2 hybrid mode and vaading-combo-box 1.3.3.
And the issue still persist even though I used Polymer accessor methods.

**Comment by Top-Developer** [comment]
@tomivirkki, @marcushellberg
I fixed the issue by updating vaadin-combo-box-item.
The vaadin-combo-box-overlay component is using iron-list to display items and iron-list adds attribute `hidden` when an item is removed.
But vaadin-combo-box-item does not have css property for attribute `hidden`.
This is the reason of such kind of bugs.
I think vaadin-combo-box-item 1.3.3 should be updated.
