### ISSUE TITLE
enhancement : add theme =small for vaadin-combo-box

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-combo-box#683]
theme=small is not working on vaadin-combo-box

it's working only for vaadin-text-field

enhancement : add theme=small for vaadin-combo-box

**Comment by jouni** [comment]
`include="lumo-combo-box"` is unnecessary, though, if you are already importing the Lumo theme version of the component.

**Comment by web-padawan** [comment]
Starting form the 4.2.0-alpha3, we implemented this as a general feature: from now on, you can set e. g. `theme="small"` and it will be propagated to the underlying text-field, so I'm closing this issue.
