### ISSUE TITLE
Combobox group uses the same array instance when value is changed

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-combo-box#687]
Combobox group always uses the same array instance as a value when it's modified.

Expected: Flow client engine expects different values for property when value is updated. Flow doesn't listen changes in array (and Flow doesn't know the exact type of the property value).
Flow has code which compares the current value cached internally with the new value gotten from web component. If it's the same value then update is ignored and nothing is sent to the server. Since the array instance is the same Flow doesn't update value on the server side.

Actual: the value is always the same array which is just modified.

All browsers affected.
No live demo since I can't create Vaadin Flow Combobox Group component because of this bug and there is no any documentation yet about `vaadin-checkbox-group` web component with HTML examples.

**Comment by platosha** [comment]
Wrong component? I guess it’s about `<vaadin-checkbox-group>` not `<vaadin-combo-box>`?

**Comment by denis-anisimov** [comment]
Right , sorry.
I always confuse them :(
