### ISSUE TITLE
Feature request. disable manual text input

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-combo-box#703]
The element already  has:

setAllowCustomValue and setPreventInvalidInput.

But both of them do not block the custom-text input by user completely, he still can type something, even though it disappears after tabbing out.

A workaround i use now is this:

(cb = ComboBox instance)
cb.getElement().setAttribute("onkeydown", "return false");

It would be nice having a simple setter for this or add it when setAllowCustomValue  is false

Thanks

**Comment by platosha** [comment]
@masbaehr thanks for your feature request.

Please consider using `<vaadin-dropdown-menu>`. Could it, perhaps, solve this issue entirely? Unlike the `<vaadin-combo-box>`, the `<vaadin-dropdown-menu>` does not have a true text input support in the first place. It looks like a better fit for your use case.

Another option is to try using `<vaadin-combo-box-light>`, which allows developers to provide an external input element for the combo-box, and then combine it with a read-only `<vaadin-text-field>`, for example.

**Comment by masbaehr** [comment]
Hi thanks for the hint. I guess dropdown is fine. Still i think the behaviour of ComboBox when setAllowCustomValue  is false is a bit strange, why would it allow to type something? But i will close this, as for my use-case it's fine!

**Comment by platosha** [comment]
@masbaehr the primary use case of `<vaadin-combo-box>` is to allow the users to select from a large number of items, and enable using text input for filtering the items.

If a custom value is allowed, then any text is accepted as the value of the component. But if the custom value is not allowed, it means that users set a value which is not from the items list. In that case, the text input is still enabled to facilitate filtering. The filter text, however, is discarded on blur, as you have already noticed.
