### ISSUE TITLE
Fails lighthouse "Does not use passive listeners to improve scroll performace"

### ISSUE THREAD

**Issue by aarondrabeck** [vaadin/vaadin-combo-box#704]
Should be easy to solve by adding `{passive: true}` on key event listeners in this component.

**Comment by samiheikki** [comment]
Polymer's `gestures.html` is the only one failing the scroll performance test. Closing this issue.

<img width="704" alt="Screenshot 2019-06-29 at 13 42 07" src="https://user-images.githubusercontent.com/8615573/60382973-b5970280-9a73-11e9-9eb3-288f022ba032.png">
