### ISSUE TITLE
Cannot be installed with vaadin-date-picker because of dependency conflicts

### ISSUE THREAD

**Issue by aarondrabeck** [vaadin/vaadin-combo-box#713]
### Description
This component requires  @vaadin/vaadin-overlay - 3.2.0-alpha1.  vaadin Datepicker requires @vaadin/vaadin-overlay - 3.1.0-beta2.  Installing both components in a project request in nested dependencies.  Then when you import both elements on the same page, you get a vaadin-overlay component already declared console error. 

Can we get a updated version of combo-box released to NPM with a vaadin-overlay 3.1.0-beta2 dependency? 

### Expected outcome
Both elements work on the same page.

### Actual outcome
Console Error

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by web-padawan** [comment]
Hello, thanks for pointing out. This is our issue with the npm tags. I have changed the tags for combo-box:

latest: 4.1.0
next: 4.2.0-alpha2

Please use 4.1.0 version for now, it should be now picked up correctly. 
Will do the same for other components having same overlay dependency.

**Comment by web-padawan** [comment]
npm tags have been updated so I'm closing this issue. We will handle it in our tool that we use for publishing. Also, date-picker will be soon updated to depend on the latest overlay as new alpha.
