### ISSUE TITLE
Combobox bad binding with flow 1.0.4

### ISSUE THREAD

**Issue by Nightbringer42** [vaadin/vaadin-combo-box#716]
### Description
With flow 1.0.4, binding fail the first time after an edit. (based on brewery webapp)

### Expected outcome
Correct binding

### Actual outcome
Empty binding

### Code :
> @Id("type")
> private ComboBox<String> doctorSent;
> 
> public EntryEditor() 
> {
> 	ListDataProvider<String> roleProvider = DataProvider.ofItems("", "Médecin 1", "Médecin 2", "Médecin 3", "Médecin 4");
> 			
> 	doctorSent.setDataProvider(roleProvider);
> 
> 	binder.forField(suivi)
> 		.withValidator(suiv -> !StringUtils.isBlank(suiv) || !StringUtils.isBlank(doctorSent.getValue()) 
> 			, "Le suivi ou le médecin envoyé doit être rempli")
> 		.bind("suivi");
> 
> 	//binder.bind(doctorSent, "sentDoctor");
> 	binder.forField(doctorSent)
> 	.withValidator(docsent -> !StringUtils.isBlank(docsent) || !StringUtils.isBlank(suivi.getValue()) 
> 		, "Le suivi ou le médecin envoyé doit être rempli")
> 	.bind("sentDoctor");
> }
> 
> public void read(Entry entry) 
> {
> 		//added to clean the bean before bind
> 		binder.removeBean();
> 		
> 		binder.readBean(entry);
> 		
> 		//Added to try to force bind
> 		doctorSent.setValue(entry.getSentDoctor());
> }

It was working fine in vaadin flow 1.0.0.rc5, when I've updated today to 1.0.4, it was broken. Reverted to rc5 : working.

**Comment by limonte** [comment]
Moved to https://github.com/vaadin/vaadin-combo-box-flow/issues/122
