### ISSUE TITLE
Fix the flaky test

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-combo-box#731]
### Description
Test is flaky on smaller screen.

### Expected outcome
Works the same way on all screens.

### Actual outcome
Not working on MBP screen.
<img width="373" alt="screen shot 2018-10-08 at 11 42 20" src="https://user-images.githubusercontent.com/29372419/46599310-a4762200-caef-11e8-98b3-e6236ba7d412.png">

### Live Demo
https://cdn.vaadin.com/vaadin-combo-box/4.2.0-alpha4/test/

### Steps to reproduce
1. Open the test page.
2. Wait till test will fail.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by Haprog** [comment]
There are currently at least 4 different tests that can fail depending on viewport height.

These 2 tests fail with timeout when viewport height >= 749px:
- `keyboard.html > keyboard navigation > scrolling items > should scroll to focused item when opening overlay`
- `scrolling.html > scrolling > scrolling position > should make selected item visible after open`

Fails with assertion failure when viewport height <= 166px:
- `keyboard.html > keyboard navigation > sanity checks for calculating visible item counts > should calculate items correctly when all items are visible`

Fails with assertion failure when viewport height <= 499px:
- `filtering.html > filtering items > setting items when opened > should properly display all items in the selector`

This means that atm. all tests can pass only if viewport height is in the range 500–748.

(tested with Chrome 74 on macOS 10.14.5)

**Comment by Haprog** [comment]
The failure of: `keyboard.html > keyboard navigation > scrolling items > should scroll to focused item when opening overlay` seems to be an actual bug. I opened a new issue about it here with more details: #815.

**Comment by Haprog** [comment]
Just noticed that it's not only about viewport height but also viewport width plays some role in these failures. E.g. on Chrome with DPR 2.2 the above `filtering.html` test fails also on viewport height 512px when the viewport width is less than 900px.
