### ISSUE TITLE
Theme the inner text field

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-combo-box#734]
Currently it is not possible to set a theme to the inner `vaadin-text-field`. Doing that manually via the browser inspector works, but there's no easy way.

This would permit to have e.g. `small` combo boxes, which align nice side by side with `small` text fields.

**Comment by tomivirkki** [comment]
This works with the upcoming 4.2.0 version (currently at alpha).
Try `$0.setAttribute('theme', 'small')` at https://cdn.vaadin.com/vaadin-combo-box/4.2.0-alpha4/demo/

**Comment by web-padawan** [comment]
Closing per above comment as already implemented.
