### ISSUE TITLE
Redundant vaadin-combo-box-icons usage

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-combo-box#745]
`vaadin-combo-box-icons` are still used in core styles, however that icons subset was already removed. It's replaced in themes, so it's not noticeable until importing of unstyled class.
Usage: https://github.com/vaadin/vaadin-combo-box/blob/master/src/vaadin-combo-box.html#L39
Commit: https://github.com/vaadin/vaadin-combo-box/commit/8717ef1136c044276353c8ef62be6730ed26a67b

**Comment by web-padawan** [comment]
Related: vaadin/vaadin-date-picker#564
