### ISSUE TITLE
Clear-button incorrect displaying IE11 & Edge

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-combo-box#746]
There is a problem with `clear-button` behaviour and displaying on IE11 and Edge.
Button is not visible till hovering/clicking the `combo-box`. Clicking on button right after inserting text won't take affect, enabled after a delay (most probably native behaviour for click listener).

`Configuring the Combo Box` demo (IE11): 
![combo-box-bug](https://user-images.githubusercontent.com/29372419/48486405-198df300-e824-11e8-8958-aba28f777035.gif)

Note: Difficult to record on Edge because of the freezes.

**Comment by web-padawan** [comment]
This should be fixed by #794 and there will be a new clear button API for V14 LTS, so closing this one.
