### ISSUE TITLE
The selected entry is not always displayed / selected in the dropdown menu.

### ISSUE THREAD

**Issue by tDD01069** [vaadin/vaadin-combo-box#747]
### Description
The selected entry is not always displayed / selected in the dropdown menu.

### Example
https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box

If I select "ANGOLA", "ANGOLA" is also selected in the drop-down menu after collapsing and reopening. 
When I select "BERMUDA", after collapse and reopen, I see the first 10 entries - without "BERMUDA".
Why is not the page with BERMUDA and its selection displayed?

**Comment by web-padawan** [comment]
The version demonstrated on that page is related to the older version of Vaadin Framework 8.
This is a repository for the web component used by Vaadin platform V10+
Moving the issue to the appropriate repository now so the team could handle it further.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/framework#11322
