### ISSUE TITLE
Scripting for ComboBox takes too much time.

### ISSUE THREAD

**Issue by brp-helena** [vaadin/vaadin-combo-box#748]
### Description
We have problems with UI changes from server taking too much time to update on client side.
We are using a solution where we from the server at times adds big groups of vaadin components.
 
For example in one of our action the server calls for the creation of ~70 components. 

I did some test to see what was eating time on the client side.

In one test I added 72 ComboBox (12 visible and 60 hidden).

This took:
Scripting: 4525ms
Rendering: 629ms
Painting: 37ms

This is not okay, we need these times to come down.

### Example 
https://gist.github.com/brp-helena/2885920dc037b87c20273b630529d60b
That gist link contains a patch for bookstore-starter-flow, this is the same test code i have used to get the numbers above.

### Steps to reproduce
1. Add this patch to bookstore-starter or vaadin-starter
2. After login go to http://localhost:8080/object
3. Use chromes "Performance" under DevTools to the record the time from when "Load Object" is pressed.

### Browsers Affected
- [x ] Chrome

**Comment by pekam** [comment]
It seems that when attaching a combo box, most of the execution time is spent attaching `vaadin-combo-box-dropdown`. This element is not needed until the dropdown is opened, so we can possibly improve the performance a lot by postponing the dropdown attach until it's opened for the first time.

I'm still investigating how feasible this kind of a change is.

Additional note: Flow client engine doesn't cause noticeable overhead.

**Comment by moderndeveloperllc** [comment]
> This element is not needed until the dropdown is opened, so we can possibly improve the performance a lot by postponing the dropdown attach until it's opened for the first time.

As long as this doesn't cause a noticeable delay or FOUC, this sounds like a good idea.
