### ISSUE TITLE
vaadin-combo-box-light css

### ISSUE THREAD

**Issue by avix89** [vaadin/vaadin-combo-box#753]
### Description
Hey 

I'm using multiple **vaadin-combo-box-light**  with custom **vaadin text field** and  icon button in my one file let's say test.html like this

  ```
<vaadin-combo-box-light id="testcombo" >  
                <vaadin-text-field id="testtext" ">   
                   <paper-icon-button  slot="suffix" icon="icons:expand-more"     
                        class="toggle-button"></paper-icon-button>                                    
                </vaadin-text-field>                                                                  
      </vaadin-combo-box-light>
```
Now i want to alter the height of this all the vaadin-text-fields which are under <vaadin-combo-box-light>  from  outside in test,html.But i'm unable to do this.Kindly tell me how to achieve this.

### Expected outcome
Should be able to change the height/size

**Comment by limonte** [comment]
Hello @avix89 

You need a style module in order to style `vaadin-text-field` inside `vaadin-combo-box`:

```html
  <dom-module id="my-text-field" theme-for="vaadin-text-field">
    <template>
      <style>
        [part="input-field"] {
          height: 50px;
        }
      </style>
    </template>
  </dom-module>
```

Live demo: https://agreeable-lark.glitch.me/
Source code: https://glitch.com/edit/#!/agreeable-lark?path=index.html:15:0

**Comment by web-padawan** [comment]
Closing per above comment as answered. See also docs for styling shadow parts here:
https://github.com/vaadin/vaadin-themable-mixin#stylable-shadow-parts
