### ISSUE TITLE
Themeable #scroller in vaadin-combo-box-dropdown-wrapper

### ISSUE THREAD

**Issue by flyweight** [vaadin/vaadin-combo-box#764]
### Description
In `vaadin-combo-box-dropdown-wrapper`, the `#scroller` element does not appear to be themeable.  I'm looking to apply a custom style to the scrollbar.

https://github.com/vaadin/vaadin-combo-box/blob/8192d2424ece4d4b8415d6e218d877a61e5a017f/src/vaadin-combo-box-dropdown-wrapper.html#L38

### Expected outcome
The `#scroller` element should be themeable.

### Actual outcome
The `#scroller` element currently cannot have styles applied to it.

**Comment by web-padawan** [comment]
Thanks for the issue. Yes, the `#scroller` is not stylable due to how it is rendered into the `vaadin-combo-box-overlay` content. We consider it an internal element, especially because of some styles needed to make it work. This might be changed in future at some point.

**Comment by web-padawan** [comment]
Closing per above comment and https://github.com/vaadin/vaadin-grid/issues/1348#issuecomment-410946067
