### ISSUE TITLE
Investigate Edge performance issues [2d]

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#767]
From the internal feedback: 

> ComboBox (Flow) with lazy loading is _incredibly_ slow in Edge 17 and 18
However, even normal combo boxes and the web component seems slower in Edge 17 than in IE11. In particular, typing into the box is very laggy.

We recently delayed rendering of the overlay until first opening. Now we should make it open faster.

One example problem: the `position-changed` event is dispatched too often (3 times when opening): https://github.com/vaadin/vaadin-combo-box/blob/79826d7c46d99c7f9d1a343f162e9ffd9c824067/src/vaadin-combo-box-dropdown.html#L250 
Also, overlay repositioning logic can be refactored and moved to vaadin-combo-box-dropdown-wrapper

**Comment by web-padawan** [comment]
Started by investigating the sequence of `_setPosition` calls. This method is invoked multiple times but even with memoization of the results of `getBoundingClientRect` performance is poor.

### Chrome

1. set position when opened set to true: 
2. set position from iron-resize: 95
3. set position from notify resize: 96
4. set position after animation frame: 98

### Edge

1. set position when opened set to true: 
2. set position from iron-resize: 1731
3. set position from notify resize: 1731
4. set position after animation frame: 1763

So, it looks like the most of work happens between `opened` set to true and `iron-resize` event. This logic involves `_onOpened` method, which calls `Polymer.flush` to render first 3 items based on hardcoded metrics, and then calls `updateViewportBoundaries` to render whole list.

So, the assumption from the initial issue appears to be not correct. I continue investigating to understand what can we do to make the mentioned part faster in Edge.

**Comment by Haprog** [comment]
The related improvements (#776) are now included in [v4.2.6](https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.6)
