### ISSUE TITLE
Dropdown closes on items filtering (user input)

### ISSUE THREAD

**Issue by marty-buly** [vaadin/vaadin-combo-box#769]
### Description
1. The `vaadin-combo-box` dropdown part is not showing filtered elements after typing into combo-box input field + it closes with every letter user types in
2. The `vaadin-combo-box` input field is not showing typed in letters

### Expected outcome
Dropdown should appear when input is typing in and show filtered items.

### Actual outcome
Dropdown vanishes

### Steps to reproduce
This behavior started with move from vaadin v12.0.2 -> v12.0.3+. I've been able pinpoint it to the release of `vaadin-combo-box` v4.2.1. It all works as expected with v4.2.0.

### Browsers Affected

- [x] Chrome
- [x] Firefox

**Comment by web-padawan** [comment]
Looks like this was changed in #752

**Comment by marty-buly** [comment]
@web-padawan that is my assumption as well

**Comment by tomivirkki** [comment]
Let's revert the change from #752 as it appears to be no longer needed
