### ISSUE TITLE
Selection doesn't work if `items` is an array of objects and values were filtered before selection

### ISSUE THREAD

**Issue by dzyubadmytro** [vaadin/vaadin-combo-box#779]
### Description
Found out that `on-selected-item-changed` triggers 2 times, first time with correct value, second time with wrong one.

### Expected outcome
The correct item should be selected.

### Actual outcome
The first item in the `items` array is selected.

### Live Demo
 ```
<vaadin-combo-box items="[[items]]">
 </vaadin-combo-box>
```
...
```
 items : {
   type : Array,
   value : [ { label : 'Test name 1', age : 15 }, { label : 'Test name 2', age : 25 }, { label : 'Name 0', age : 35 } ]
}
```
![combo-box-bug](https://user-images.githubusercontent.com/26431740/53795429-a6c39780-3f3a-11e9-9fd9-52a265739783.gif)

### Steps to reproduce
0. `items` should be an array  of objects
1. Filter out some items
2. Select any

### Browsers Affected

-  Chrome (only browser I tested)

**Comment by tomivirkki** [comment]
Hi, `<vaadin-combo-box>` has a `value` property of type `string`. By default, the value for that property is derived from the selected item's `value` (defined by `itemValuePath`) property. If it's not available `toString()` is used as a fallback and that's what happens in this case; all the items produce the same `value` of `"[object Object]"`.

So either
1. add unique `value`s to all of the items in the array or
2. change combo-box's `itemValuePath` to "label" for example

**Comment by dzyubadmytro** [comment]
Thanks a lot
