### ISSUE TITLE
vaadin-combo-box focus causes page width to change in certain browsers

### ISSUE THREAD

**Issue by teijo** [vaadin/vaadin-combo-box#78]
If vaadin-combo-box gets focus, it hides page scroll bar reducing page width on browsers that have non-overlaid scroll bar (e.g. Chrome on Windows and Chromium on Ubuntu, not OS X). Change to page width will align centered content again making the layout jump on each focus and blur.

To test, open https://cdn.vaadin.com/vaadin-elements/master/vaadin-combo-box/demo/ in non-OS X browser and focus any combo box.

**Comment by Saulis** [comment]
Thanks!

I can verify that this indeed happens also outside our demo page.

**Comment by components-stalker** [comment]
Probably happens also if you turn on the setting in OS X to always show
scrollbars.
ti 8. joulukuuta 2015 klo 22.51 Sauli Tähkäpää <notifications@github.com>
kirjoitti:

**Comment by tomivirkki** [comment]
Disabling scroll while the dropdown is open is an iron-dropdown feature. The issue with disappearing scrollbar/changing content width can be seen for example in this demo also https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html
