### ISSUE TITLE
Regression: calling render() before first open throws

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#780]
### Description
Calling `combobox.render()` throws in case combo-box has not yet been open:

```
Cannot read property 'querySelectorAll' of undefined
```

This is the line where is happens:
https://github.com/vaadin/vaadin-combo-box/blob/41f870912bdd872e3376b090e863641928568a24/src/vaadin-combo-box-mixin.html#L276

### Expected outcome
Calling `combobox.render()` doesn't throw

### Actual outcome
Error is thrown

### Steps to reproduce

1. Put a `vaadin-combo-box` element in the page.
2. Assign the renderer, don't open combo-box
3. Run `combobox.render()`

**Comment by web-padawan** [comment]
Note: this was reported for the `dom-if` version but should be still valid after `disable-upgrade` change as `_selector` isn't defined  either until combo-box is opened for the first time.

**Comment by web-padawan** [comment]
Discussed in person that `render()` could actually call `_initDropdown`, if called before first opening of the combobox, so as it would trigger actual rendering as users might expect it to be.

**Comment by tomivirkki** [comment]
Actual items wouldn't still be rendered before the dropdown is opened so this wouldn't invoke any renderers. From this point of view would make sense to not do anything unless `_selector` is there.

**Comment by Haprog** [comment]
After #782 is merged and build is green, I will rebase this fix on latest master to get this one to pass also.

**Comment by Haprog** [comment]
This fix is now included in [v4.2.6](https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.6)
