### ISSUE TITLE
DataProvider is called after filtering and selecting an item

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-combo-box#783]
Steps to reproduce:
1. Set a filter
2. Select an item

The filter is changed to empty string, but the `opened` property is still true (even though the overlay is closing).
Because the filter has changed and the combo box thinks it's still opened, `clearCache()` gets called and the first page gets requested: https://github.com/vaadin/vaadin-combo-box/blob/41f870912bdd872e3376b090e863641928568a24/src/vaadin-combo-box-data-provider-mixin.html#L101

**Comment by Haprog** [comment]
This fix is now included in [v4.2.6](https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.6)
