### ISSUE TITLE
Improve documentation on removing clear button

### ISSUE THREAD

**Issue by bsutton** [vaadin/vaadin-combo-box#784]
### Description
The documentation on basic features is almost non-existent.
If Vaadin want developers to take up their components the documentation has to drastically improve.

The specific issue I raise here is that the combo box has a 'clear' button that is displayed 'sometimes'.

If you have a look through the demos the ones that use javascript to create the combo box don't have the clear button whilst the ones that use a template do a have a clear button.
There is no obvious reason as to why some do and some don't.

I can't find any coherent documentation on controlling whether it should be visible or not.

I've found some samples that refers to '[part='clear-button]' but this is not part of the official documentation and the usage examples don't appear to conform to the coding patterns used else where.

If using the above noted part= technique is the actually intended method then we need to have a harder look at how this is being done.
Something as intrinsic as the clear button should be controlled by a simple attribute such as 'required'.

### Expected outcome
To have clear and helpful documentation.

### Actual outcome
I'm trying to be polite so I don't think I should answer this question :)
The documentation is missing key pieces.
Developer becomes extremely frustrated when answers to simple questions can't be found in the documentation.

### Steps to reproduce
Search for documentation. Find barely anything.

**Comment by tomivirkki** [comment]
Now that we have [`clearButtonVisible` api](https://github.com/vaadin/vaadin-text-field/releases/tag/v2.3.0) in `text-field`, we should just align `combo-box` and `date-picker` (and make the clear button hidden by default) as this is [quite a requested fix](https://github.com/vaadin/vaadin-combo-box-flow/issues/79). Currently, hiding the clear button is indeed unreasonably complex.

Made a feature branch & working prototype for this at https://github.com/vaadin/vaadin-combo-box/tree/clear-button-visible

**Comment by bsutton** [comment]
looks to be a reasonable approach.

thanks for the effort.

There is still a question as to why some of the combo box in the demo have a clear button and why some don't?

**Comment by web-padawan** [comment]
Will be fixed by #794 

> why some of the combo box in the demo have a clear button and why some don't?

When combo-box is disabled or readonly, the clear button is hidden despite value is selected.

**Comment by web-padawan** [comment]
Fixed by #794
