### ISSUE TITLE
Cannot open dropdown in paper-dialog on mobile w/ scroll-action="lock"

### ISSUE THREAD

**Issue by dejan9393** [vaadin/vaadin-combo-box#795]
### Description
The `vaadin-combo-box` element does not open on mobile devices when the input is inside a paper-dialog with `scroll-action="lock"`.

There's a chance that this is related to #634.

### Expected outcome
The combo-box should open

### Actual outcome
It doesn't

### Live Demo
https://spiced-kingfisher.glitch.me/

### Steps to reproduce
1. Place a `vaadin-combo-box` element inside a `paper-dialog` with `scroll-action="lock"` set.
2. Fire up Chrome and navigate to the live demo provided above.
3. Open the inspector (`⌘⇧I`).
4. Toggle the device toolbar (`⌘⇧M`) to view in responsive/mobile mode.
5. Select iPhone X (or any mobile) from the toolbar at the top of the screen.
6. Attempt to open the combo box.

**Comment by dejan9393** [comment]
On second thoughts, this could be a `paper-dialog` issue? It seems that even normal form inputs don't receive focus on tap when scroll-action is set to `lock`

**Comment by tomivirkki** [comment]
Hi, it seems that `<paper-dialog>` with `scroll-action="lock"` -combination will disable clicks on any type of element. So, even if I add a native `<button>` with a "click" listener, the listener will never invoke on click.
