### ISSUE TITLE
Multiple value-changed events fired

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/vaadin-combo-box#811]
### Description
If the user selects an item from the dropdown while the input field has a different value in it then the element dispatches two value-changed events because the `_onClosed` function seems to be responsible to update the value but it does not handle `_overlaySelectedItemChanged` case.

### Expected outcome
Only one value-changed event is fired if an item is selected in the dropdown overlay.

### Actual outcome
- If the input field has only a "filter" text in it and custom values are allowed, then the first value-changed event gives that value back.
- If `_focusedIndex > -1` then the first value-changed event contains the corresponding item for that index.

### Live Demo
https://vaadin.com/components/vaadin-combo-box/html-examples

If indeed the `_onClosed` is the main function where we need to update the selection then `_overlaySelectedItemChanged` might need to pre-configure something before calling close and let it to handle the selection.

**Comment by Haprog** [comment]
Thanks for the report! I can reproduce this.

**Comment by Haprog** [comment]
This actually seemed to have been fixed already about a week ago by commit 677d7ab (not reproducable in `master` branch anymore), but there hasn't been a new release yet since that fix.

This fix will be in vaadin-combo-box v5.0.2 which will be released soon.

**Comment by attilapuskas** [comment]
Thanks!

**Comment by Haprog** [comment]
Here you go [v5.0.2](https://github.com/vaadin/vaadin-combo-box/releases/tag/v5.0.2)
