### ISSUE TITLE
vaadin-text-field-flow demos

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-combo-box#813]
### Description
Make new demos for the vaadin-text-field-flow
### Expected outcome

New demos for the vaadin-text-field-flow will be made in different parts as Textfield, Numberfield, Passwordfield and Textareafield. Some common parts will also be made for all these components.

### Actual outcome
Demos of the vaadin-text-field-flow will be categorized into different parts as Textfield, Numberfield, Passwordfield, Textareafield and also some common parts for all these components will be made like Prefix and suffix, Validation and theme variants.

**Comment by web-padawan** [comment]
Wrong repo? Issue is for `text-field-flow` but this is a combo-box.

**Comment by web-padawan** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #188](https://github.com/vaadin/vaadin-text-field-flow/issues/188) via [**ZenHub**](https://www.zenhub.com/)

**Comment by web-padawan** [comment]
Issue moved to [vaadin/vaadin-text-field-flow #189](https://github.com/vaadin/vaadin-text-field-flow/issues/189) via [**ZenHub**](https://www.zenhub.com/)
