### ISSUE TITLE
vaadin-combo-box-light breaks the layout when opened

### ISSUE THREAD

**Issue by masonlouchart** [vaadin/vaadin-combo-box#817]
### Description
The `vaadin-combo-box-light` element breaks the layout when clicked.

### Expected outcome
Same outcome as the `vaadin-combo-box`:

![Kapture 2019-06-18 at 19 05 19](https://user-images.githubusercontent.com/2325091/59704326-2597c400-91fc-11e9-9358-305d5faee2dd.gif)

### Actual outcome
![Kapture 2019-06-18 at 19 23 35](https://user-images.githubusercontent.com/2325091/59705447-aa83dd00-91fe-11e9-8e35-016f72a7128a.gif)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
_(and all others I guess)_

**Comment by masonlouchart** [comment]
My bad. Wrong dependency version. 🙇

**Comment by web-padawan** [comment]
@masonlouchart thanks for letting us know.
