### ISSUE TITLE
Clear button does not set null value

### ISSUE THREAD

**Issue by mpetzold** [vaadin/vaadin-combo-box#823]
I have a ComboBox with values. When I select a value everything is fine. However, when I click the clear button, the originally selected value is set instead of null. If I then click somewhere outside of the ComboBox and click the clear button again, a null value is set.

Can be reproduced using a ValueChangeListener:

`combobox.addValueChangeListener(new ValueChangeListener<ComponentValueChangeEvent<ComboBox<MyObject>, MyObject>>() {

				@Override
				public void valueChanged(ComponentValueChangeEvent<ComboBox<MyObject>, MyObject> event) {
					System.out.println(event.getValue());
				}
				
			});
`

Vaadin / Flow version: 14.0.0.rc2
Java version: 1.8
OS version: Debian 9
Browser: Chrome 75.0.3770.100

**Comment by yuriy-fix** [comment]
Issue moved to [vaadin/vaadin-combo-box-flow #277](https://github.com/vaadin/vaadin-combo-box-flow/issues/277) via [**ZenHub**](https://www.zenhub.com/)
