### ISSUE TITLE
Poor ComboBox performance/ComboBox stops working when fast scrolling of lots of items 

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-combo-box#825]
### Description
When a large number of items is given to the combo box (10000) and the suggestion popup is scrolled rapidly down and up again, eventually the combo box stops responding and hogs the entire web page. After a while, the web page may resume, but the combo box no longer reacts to any mouse clicks.

Easily reproducible in Vaadin 14; somewhat harder to reproduce in Vaadin 13. Please see the attached video for details.

### Expected outcome
The combobox should handle potentially any number of items

### Actual outcome
The ComboBox will freeze the page when the contents of the suggestion box are scrolled rapidly.

### Steps to reproduce
1. Open and run the attached application
2. Click the ComboBox to show the suggestion box
3. Scroll like crazy :)

[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-combo-box/files/3359559/skeleton-starter-flow.zip)

### Browsers Affected

Tested on Chrome and Firefox only; whether other browsers are also affected or not is not known.

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by mvysny** [comment]
[Screencast from 04.07.2019 16.59.28.webm.zip](https://github.com/vaadin/vaadin-combo-box/files/3359584/Screencast.from.04.07.2019.16.59.28.webm.zip)

**Comment by tomivirkki** [comment]
While scrolling furiously, it looks like `iron-list` suddenly generates thousands of combo-box-items inside of itself and this jams the whole application.
