### ISSUE TITLE
clear-button-visible not mentioned on API or demos

### ISSUE THREAD

**Issue by alump** [vaadin/vaadin-combo-box#827]
If you check API documentation at https://vaadin.com/components/vaadin-combo-box/html-api it doesn't mention clearButtonVisible property at all (or at least I couldn't find it).

Also if you check all demos, those have clear button visible, even that none of the example code snippets show that attribute/property being set.

I couldn't find mention from anywhere else than by inspecting Flow API source code. Or maybe reading components code and reverse engineer behavior from there.

So please add this property to documentation, do not set properties in examples that aren't shown in code.

Specially this is bad, because before clear button was shown by default? Now you have hidden it and left it out from documentation?

**Comment by alump** [comment]
Looks like https://cdn.vaadin.com/vaadin-combo-box/5.0.5/#/elements/vaadin-combo-box has this property defined. So vaadin.com issue once more?

**Comment by alump** [comment]
Ok more searching... https://preview.vaadin.com/components/vaadin-combo-box/html-examples has correct examples, but API not mentioning property

**Comment by tomivirkki** [comment]
The API is correct and documented in the Web Component. The preview version of the website you linked apparently still shows API docs generated from an earlier component version. Here's what you should see once the APIs get generated properly: https://cdn.vaadin.com/vaadin-combo-box/5.0.5/#/elements/vaadin-combo-box#property-clearButtonVisible

**Comment by tomivirkki** [comment]
> For https://cdn.vaadin.com/vaadin-combo-box/5.0.5/#/elements/vaadin-combo-box/demos/demo/index.html there also isn't ghost clear buttons (not set in examples). But maybe at least one example should set clearButtonVisible property (now I think none of those do).

The linked demo page has an example where the `clearButtonVisible` property is set trough an attribute (`<vaadin-combo-box clear-button-visible>`). Are you suggesting we should have separate demos for each of your properties where one sets it via attribute and another one sets it as a property (`<vaadin-button disabled>` and `vaadinButton.disabled = true`)?

**Comment by jouni** [comment]
> So vaadin.com issue once more?

Yes. The version number it shows is out of sync with the examples and API docs of the component.
