### ISSUE TITLE
Input text selection logic

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-combo-box#83]
- Preselect the input value when opened/focused
- When you filter the items, and navigate using arrow keys, the ending of the value could be entered into the field and preselected, if we have an option for "begins with" type of filtering

Background: [End User UX Test Notes](https://docs.google.com/document/d/1h2OkslUkD3m_QG3VXJS-QOCrEgci6qCiqDPT7MPzaKo/edit#bookmark=id.sumcnli1be9t)

**Comment by jounik** [comment]
This has actually been implemented in some of the alpha versions, thought not necessarily exactly as described in this ticket. Further improvements should be done using separate issues.
