### ISSUE TITLE
Click outside combo box closes paper-dialog

### ISSUE THREAD

**Issue by bramkragten** [vaadin/vaadin-combo-box#834]
### Description
I'm seeing the same problem as mentioned before in https://github.com/vaadin/vaadin-combo-box/issues/405

When embedding a `vaadin-combo-box` in a `paper-dialog` without setting `no-cancel-on-outside-click`, the dialog closes when the combo box is opened and closed by clicking on the dialog. 

Using:
@polymer/paper-dialog@3.0.1
@polymer/iron-overlay-behavior@3.0.2
@vaadin/vaadin-combo-box@5.0.6

### Expected outcome
Combo box closes. dialog stays open.

### Actual outcome
Dialog closes

### Steps to reproduce
1. Put a `vaadin-combo-box` element in a `paper-dialog`.
2. Open the page in a web browser.
3. Click the input of `vaadin-combo-box` element.
4. Click on the `paper-dialog`

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by web-padawan** [comment]
Closing as outdated and because Paper Elements are now deprecated.
Let's submit a new issue if this turns out to be a problem also with `mwc-dialog`.
