### ISSUE TITLE
Fullscreen layout breaks down on Android

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-combo-box#84]
In the UX test proto the layout broke down on Android 5 test device. The error occurred at least when there was more than one instance of a combo box with the same items inside a form ("Languages" combo box in the proto).
- Options list was cut half from the middle even if there was so many items that they didn't fit in the viewport.
- Some options appeared as empty rows.

Background: [UX Test Notes](https://docs.google.com/document/d/1h2OkslUkD3m_QG3VXJS-QOCrEgci6qCiqDPT7MPzaKo/edit#bookmark=id.qk1y70nfcc9m)

**Comment by jounik** [comment]
This might depend on the results of #89

**Comment by jounik** [comment]
1d timebox for research.
