### ISSUE TITLE
Update the event listener registrations to use a previously stored bound version of the handler

### ISSUE THREAD

**Issue by gatanaso** [vaadin/vaadin-combo-box#847]
### Description
The current way in which event handlers are added is not consistent across the component sources. For example, if we look into `vaadin-combo-box-dropdown.html`, we can find the following code:
```
      constructor() {
        super();
        this._boundSetPosition = this._setPosition.bind(this);
        this._boundOutsideClickListener = this._outsideClickListener.bind(this);
      }
      connectedCallback() {
        super.connectedCallback();
        this.addEventListener('iron-resize', this._boundSetPosition);
      }
```
This is a good pattern, as i.e. the `iron-resize` listener can be removed as we have registered it with the "bound" version of `_setPosition`: `this._boundSetPosition`.

In comparison, if we look into `vaadin-combo-box-mixin.html`, we can find the following code:
```
    ready() {
     // ... omitted for clarity

      this.$.overlay.addEventListener('selection-changed', this._overlaySelectedItemChanged.bind(this));
      this.addEventListener('vaadin-combo-box-dropdown-closed', this.close.bind(this));
      this.addEventListener('vaadin-combo-box-dropdown-opened', this._onOpened.bind(this));
      this.addEventListener('keydown', this._onKeyDown.bind(this));
      this.addEventListener('click', this._onClick.bind(this));
      this.$.overlay.addEventListener('vaadin-overlay-touch-action', this._onOverlayTouchAction.bind(this));
```

As we can see here, the event listeners are directly added without saving a reference to their "bound" version. This effectively makes these listeners impossible to remove, as calling `bind` returns a new function, so removing the listener is not possible.

### Expected outcome
Update the event listener registrations to use a previously stored bound version of the handler (i.e. similarly to how it is done in `vaadin-combo-box-dropdown.html`).

### Actual outcome
The added event listeners in `vaadin-combo-box-mixin.html` are not possible to be removed i.e. in a subclass of the `vaadin-combo-box`.

### Additional information
The motivation for this change is to allow subclasses to remove or modify event listeners and be able to extend the given functionality. One example is allowing [multiselect-combo-box](https://github.com/gatanaso/multiselect-combo-box) to keep the overlay open whilst the user is selecting items (at this time this is not possible, as the `selection-changed` listener cannot be removed).

**Comment by gatanaso** [comment]
Please let me know if you consider this a sensible modification, I would be more than happy to contribute this changes to the component. Thank you 🙏

**Comment by tomivirkki** [comment]
Would it work if multiselect-combo-box also adds a listener for 'selection-changed' and in that listener calls `event.stopImmediatePropagation()`?

**Comment by gatanaso** [comment]
>Would it work if multiselect-combo-box also adds a listener for 'selection-changed' and in that listener calls event.stopImmediatePropagation()?

This does not prevent the initial `selection-changed` to be called, as the multiselect-combo-box uses the vaadin-combo-box-light internally, it does not override it.

Overriding it could be an option as well, but I also wanted to raise the question here of whether this kind of modification to the event listener registrations makes sense to the core team :)
