### ISSUE TITLE
Improve keyboard navigation for opening/closing

### ISSUE THREAD

**Issue by tuomasnironen** [vaadin/vaadin-combo-box#85]
Specify and implement opening/closing the combo box behaviour regarding up/down and esc keypresses. Things to keep in mind:
- prefilling the input while moving up/down in the dropdown
- cycling options list with arrows after the dropdown is opened (jumping from top to bottom or bottom to top)
- selecting vs. clearing the selection with which keypresses at which stages?

Background: [UX Test Notes](https://docs.google.com/document/d/1h2OkslUkD3m_QG3VXJS-QOCrEgci6qCiqDPT7MPzaKo/edit#bookmark=id.n2ul6ogjusxi)

**Comment by jounik** [comment]
Related to #87

**Comment by jounik** [comment]
The keyboard navigation was refined a lot during the alpha later alpha stages with many of the issues described here fixed. I consider this task done already. Further improvements should open new issues.
