### ISSUE TITLE
Vaadin-combo-box and Modeless does not work.

### ISSUE THREAD

**Issue by tregoning** [vaadin/vaadin-combo-box#852]
### Description
The boolean attribute "modeless" (inherited from Vaadin.OverlayElement) does not affect the overlay behaviour at all.

### Expected outcome
The overlay from the combo-box does not disable the main content.

### Actual outcome
There is an invisible overlay that disappears when clicked that disables the main content.

### Live Demo
Sample Code here: https://github.com/tregoning/vaadin-combo-box-modeless-bug
Alternatively, simply add the "modeless" attribute to any combo-box and try to hover a link. (it should work, but it does not)

### Steps to reproduce
- open drop-down
- move the mouse above some element with hover state (e.g. link) nothing happens.

**Comment by tomivirkki** [comment]
Hi, combo-box doesn't have the `modeless` property https://cdn.vaadin.com/vaadin-combo-box/5.0.9/ It's part of the internal `vaadin-overlay` component's API.
