### ISSUE TITLE
Dropdown keyboard opening and item highlighting

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-combo-box#87]
Different cases to solve:

- Key down ↓
  - Dropdown opens below
     - Key down ↓
       - Highlight first item in the list
     - Key up ↑
       - ?
  - Dropdown opens above
     - Key down ↓
       - Highlight first item in the list
     - Key up ↑
       - ?
- Key up ↑
  - Dropdown opens below
     - Key down ↓
       - ?
     - Key up ↑
       - ?
  - Dropdown opens above
     - Key down ↓
       - ?
     - Key up ↑
       - ?

**Comment by tuomasnironen** [comment]
### Suggested KEY UP/DOWN behaviour

*No items selected (or multiple items selected)*
- KEY DOWN ↓
  - Dropdown opens below OR above depending on the available space in browser
    - KEY DOWN ↓
      - Highlight first item in the list
    - KEY UP ↑
      - Highlight last item in the list (jump if item doesn't fit in the viewport)
    - Once the highlight appears on the list, KEY UP ↑ and KEY DOWN ↓ moves it accordingly.
    - The highlight doesn't cycle through jumping from top to bottom or the other way around. When it reaches the top or the bottom of the list, it just doesn't move any further.

- KEY UP ↑
  - Do nothing

*One item selected*
- KEY DOWN ↓
  - Dropdown opens below or above depending on the available space in browser
    - Highlight the selected item

- KEY UP ↑
  - Do nothing

**Comment by jounik** [comment]
As discussed on Skype, this design is how we want to proceed. This issue can, in my opinion, be reused for the implementation task as well.

**Comment by jounik** [comment]
Need to still fix in the  new version of the combo box:
- When the dropdown is opened but no item is highlighted and the user pressed KEY UP and the last item in the list should get highlighted.

We will postpone the change about opening the dropdown with KEY UP, and keep the current implementation.
