### ISSUE TITLE
The option popup is not shown when typing if auto open is disabled

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-combo-box#899]
### Description
if `autoOpen` is false, the option popup is not shown when the user types in the input field.

### Expected outcome
The option popup is shown if there are matching items.

### Actual outcome
No matching items are shown.

Vaadin 14.3.1

```java
ComboBox c = new ComboBox("Country");
c.setItems("Afghanistan", "Albania", "Algeria", ...);
c.setAutoOpen(false);
```

https://www.dropbox.com/s/9zl2hd73cdtk1ub/combo-box-autoopen-disabled-bug.mov?dl=0

**Comment by alvarezguille** [comment]
Seems to be related to https://github.com/vaadin/vaadin-combo-box-flow/issues/326
This happens when ComboBox has a data provider. I'm not sure if the options popup should be shown when typing with auto open disabled, but at least a matching value shouldn't be lost.

**Comment by jouni** [comment]
> I'm not sure if the options popup should be shown when typing with auto open disabled

Sigh. Apparently [we actually specced the feature to work like that](https://github.com/vaadin/vaadin-combo-box/issues/863). Can’t remember a reason why, though.

Now, I think matching options should be shown when the user types in the field.

**Comment by jouni** [comment]
Digging through memories, and it seems that this behavior was first designed for date picker, and then decided that it should apply for combo box similarly.

In date picker, it’s more expected that the popup stays closed, as the user knows the format of the value they want to enter, and the popup would only be a distraction.

We’ll keep the behavior as it is now, that the popup is not shown even when the user types in the field.

**Comment by jouni** [comment]
The other identified issue from the video is that the typed string is not actually set as the field value when the user blurs the field. That should be fixed (another issue should be opened for that).
