### ISSUE TITLE
Enforce iOS viewport scroll position for fullscreen mode

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-combo-box#9]
Clean up the prototype code in the fullscreen-ios branch.

Remove code related to viewport resizing (when the keyboard is open)

**Comment by tomivirkki** [comment]
Changes in the ios-scrollposition branch currently:
- Always maintains the dropdown position absolute
- Tries to keep the scroll position of the window so the the dropdown covers the whole viewport (by timing a scroll restore fucntion on every touchstart)

**Comment by jounik** [comment]
Before this is done, the following needs to happen

- [ ] Add tests
- [ ] Merge to master
