### ISSUE TITLE
Valid item is not selected if ComboBox has a dataprovider and autoopendisabled

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-combo-box#900]
### Description
The input is cleared even though there's a match in the backend items.
Main problem seems to be that typing in the input does not trigger a data provider request unless the popup is opened.

### Live Demo
Can be reproduced in [v5.2.0 demo](https://cdn.vaadin.com/vaadin-combo-box/5.2.0/demo/#combo-box-basic-demos)

### Steps to reproduce
* Set autoOpenDisabled = true to the ComboBox in lazy loading demo
* Type a valid country name without opening the popup 
* Blur the field

### Expected outcome
Item is selected

### Actual outcome
Item is cleared

**Comment by DiegoCardoso** [comment]
The solution proposed is to change the behavior of how data is fetched for combo-box regardless if `autoOpenDisabled` is on or off.

#### This is the user case that this issue should cover:

1. User start typing on combo-box field
1. Data is fetched based on the user input
1. _**User moves focus away from combo-box**_
1. Value inserted by the user **is not cleared** from the field while data is being fetched
1. When dataProvider returns with the response, then:
  	- if **there's a match**, set it as the combo-box value; or
  	- if **there's no match**, clear combo-box

User's feedback while data is being fetched should be handled by #901.

**Comment by tomivirkki** [comment]
Related: https://github.com/vaadin/vaadin-combo-box/issues/919
