### ISSUE TITLE
Combobox popup rendering issue when css variable is set

### ISSUE THREAD

**Issue by onuridrisoglu** [vaadin/vaadin-combo-box#904]
The code below works fine by default settings:
```
ComboBox<String> combo = new ComboBox<>();
List<String> items = new ArrayList<>();
for (int i = 0; i < 5000; i++) {
	items.add("Person#" + i);
}
combo.setItems(items);
add(combo);
```

However, if the `--iron-list-items-container_-_border-style` css variable is set to `none`, populating the items in popup seems to take quite long, and mostly empty records are displayed.

```
@CssImport(value = "./styles/combobox-overlay.css", themeFor = "vaadin-combo-box-overlay")
```

The content of `combobox-overlay.css` file: 
```
:host(:not([disabled])) {
   --iron-list-items-container_-_border-style: none;
}
```

**Vaadin Version:** 14.3.7
**Browser:** Chrome Version 85.0.4183.121

**Comment by rolfsmeds** [comment]
Closing, as changing a private css property of iron-list is not a supported feature in ComboBox.
