### ISSUE TITLE
Verify fetched items range for undefined size in AbstractItemCountComboBoxIT

### ISSUE THREAD

**Issue by mshabarov** [vaadin/vaadin-combo-box#907]
It would be helpful and reasonable to verify the range of fetched items for `ComboBox` undefined size lazy loading scenario. There is a `TODO` comment in `AbstractItemCountComboBoxIT::doScroll` method about this.

At the moment, there is an issue with scrolling for undefined size lazy loading, which has been intentionally introduced to scroll to 0 position after the user implements any text filter (https://github.com/vaadin/vaadin-combo-box-flow/issues/386). 

`AbstractItemCountComboBoxIT::doScroll` method now has a workaround for this so as to scroll the combobox for a few times until it reaches the desired target item index. 

In order to avoid redundant code rewriting, I propose to implement this verification after vaadin/vaadin-combo-box-flow#386 will have been done.

**Comment by web-padawan** [comment]
The mentioned workaround was removed in https://github.com/vaadin/vaadin-combo-box-flow/pull/380/commits/836029ce70391681fa9c49f7e5097cf3a6847d9e before merging the PR. Closing.
