### ISSUE TITLE
Unify sizing with paper-inputs

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-combo-box#91]
Currently `vaadin-combo-box` looks a bit out of place in a form with other paper-inputs as it is sized or aligned differently.

<img width="811" alt="screen shot 2015-12-14 at 8 54 33 am" src="https://cloud.githubusercontent.com/assets/883698/11787620/88217c50-a241-11e5-9fff-2fbf031c3cfb.png">

**Comment by jounik** [comment]
1d timebox for the research

**Comment by manolo** [comment]
Probably fixed with : https://github.com/vaadin/vaadin-combo-box/pull/95
