### ISSUE TITLE
It should be possbile to create a lazy data binding to ComboBox without providing the count of items that match the filter

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-combo-box#910]
Currently one needs to provide two callback to implement the lazy data binding to a combobox. One for a page of items that match the given filter string and one for count of items that match to the query. The count callback should be optional, as in V17 Grid.

**Comment by web-padawan** [comment]
This feature was released in [Vaadin 18](https://vaadin.com/blog/vaadin-18-brings-enhancements-for-fusion-and-flow). Closing.
