### ISSUE TITLE
ComboBox.getDataProvider throws NullPointerException

### ISSUE THREAD

**Issue by tltv** [vaadin/vaadin-combo-box#915]
Call to `ComboBox.getDataProvider` throws `NullPointerException` if data provider is not set yet.

Expecting it to return `null` instead when data provider is not provided yet. Or at least expecting Javadoc to tell that it may throw `NullPointerException` if not set yet. 

For example: developers may encounter this exception when they want to initialize a ComboBox beforehand and then later check if data provider was already set by `if(getDataProvider() != null)`.

`NullPointerException` is caused by unchecked call `dataCommunicator.getDataProvider()` in `ComboBox.getDataProvider()`.

**Comment by TatuLund** [comment]
The needed null pointer check was included in this PR for other reasons https://github.com/vaadin/vaadin-combo-box-flow/pull/382 so I would assume that this issue does not happen anymore.

**Comment by web-padawan** [comment]
Closing per above comment. Please submit a new issue if the problem still persists.
