### ISSUE TITLE
ComboBox loses value entered from keyboard if filtering is done on server-side

### ISSUE THREAD

**Issue by guttormvik** [vaadin/vaadin-combo-box#919]
In example below I have 2 almost equal ComboBox<String>. One with values1..49, one with values 1..51.
When running, if I write "22" and tab out, the value is accepted in the 1st combobox, and lost in the 2nd.
If I wait until the filtering is done for the 2nd ComboBox it works, but this is not very user friendly.

```
@Route
public class ComboBoxView extends HorizontalLayout {

	public ComboBox<String> createComboBox(int itemCount) {

		List<String> stringList = new ArrayList<>(); 
		
		for(int i=1; i<=itemCount; i++) {
			stringList.add(Integer.toString(i));
		}
		
		ComboBox<String> comboBox = new ComboBox<>("ComboBox 1.."+itemCount);
		comboBox.setItems(stringList);
		
		return comboBox;
		
	}
	
	public ComboBoxView() {
		add(new TextField("Before"), createComboBox(49), createComboBox(51), new TextField("After"));
	}
	
}
```

**Comment by tulioag** [comment]
Fixed. Tested in current master with webcomponent `v5.4.6`.

Fix is #961

**Comment by guttormvik** [comment]
If the text you write is in different case ("bb") than the values ("BB"), then you have to wait until the filtering is completed before tabbing out. Ie same issue as before. If you tab before filtering is complete, you lose the value.

Tested with Vaadin 19.0.5

```
@Route
public class ComboBoxBugView extends MasterScreen {

	public ComboBox<String> createStringComboBox() {

		List<String> list = new ArrayList<>(); 
		
		for(char a = 'A'; a<='Z'; a++) {
			for(char b = 'A'; b<='Z'; b++) {
				list.add("" + a + b);
			}
		}
		
		ComboBox<String> comboBox = new ComboBox<>("ComboBox AA..ZZ");
		comboBox.setItems(list);
		
		return comboBox;
		
	}
	
	public ComboBoxBugView() {		
		add(new TextField("Before"), createStringComboBox(), new TextField("After"));
	}
	
}
```

**Comment by tulioag** [comment]
Hi @guttormvik. Since this issue has been closed for some time, would you mind creating a new issue linking this one?

**Comment by guttormvik** [comment]
Hi @tulioag, not sure. I was asked to comment on the old issue by @rolfsmeds
