### ISSUE TITLE
Blurring out of combobox, having some value inside input prompt, makes scrollbars visible

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-combo-box#938]
**VERSION**: 10.0.9
(Works in 12.0.2)
When blurring event from the Combobox (with some value inside input prompt) is occurred, both horizontal and vertical scrollbars become visible for a second.

Hopefully, the video describes problem better: 

![comboboxjumps](https://user-images.githubusercontent.com/15248706/49797240-80c99500-fd47-11e8-8134-7654d865d6bb.gif)

**Comment by web-padawan** [comment]
Closing as inactive and because we haven't been able to reproduce the issue as mentioned in the comments above.
