### ISSUE TITLE
ComboBox consumes huge parts of a site

### ISSUE THREAD

**Issue by AB-xdev** [vaadin/vaadin-combo-box#939]
### The Problem
Sometimes important information is covered by the dropdown of a combobox and you can't set the length of the dropdown (like in Vaadin 8 with `setPageLength`):

![grafik](https://user-images.githubusercontent.com/45384811/49633426-94989280-f9f9-11e8-8417-21dace9bb0b2.png)
![grafik](https://user-images.githubusercontent.com/45384811/49633620-551e7600-f9fa-11e8-86f0-38d9563e02c7.png)

#### How to reproduce
Code used in the above example:
```
final List<String> in = new ArrayList<>();

for(int i = 100; i < 200; i++)
{
	in.add(String.valueOf(i));
}

this.cb.setItems(in);
this.cb.setWidth("80%");

this.add(this.cb);

final Label l = new Label("Important content!");

l.getStyle().set("margin-top", "500px");

this.add(l);
```

**Comment by web-padawan** [comment]
Closing in favor of #754. See workaround at https://github.com/vaadin/vaadin-combo-box/issues/754#issuecomment-451902140
