### ISSUE TITLE
Allow specifying overlay width

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box#942]
It seems that the overlay element's width is fixed to be the same as the input field's. In some cases (short input, long item captions) it would be useful to allow customizing the overlay width to be larger. If this is doable with styles, such a method should be documented.

**Comment by web-padawan** [comment]
The new docs site has examples of using a feature mentioned above:
https://vaadin.com/docs-beta/latest/ds/components/combo-box/#popup-width

**Comment by mvysny** [comment]
Follow-up ticket: https://github.com/vaadin/flow-components/issues/2331
