### ISSUE TITLE
If data provider is changed combobox loose selection

### ISSUE THREAD

**Issue by ovidiupopa91** [vaadin/vaadin-combo-box#947]
Problem: 
Initially we have a data provider for the combobox and a binder which is selecting one element. 
On an event we have to change the data provider and select another item from this new list. 

What happens is that after the event the combobox will have no selection in the UI.
In the backend if I run this code I will get the correct selected value (after data provider change). 
` binder.readBean(viewModel);
    comboBox.getValue();`

But this is how the UI looks like:
![image](https://user-images.githubusercontent.com/35370284/46195931-4cc90100-c30e-11e8-92a6-b6e767081f2f.png)

It looks like there is a synchronization issue between the backend and the frontend. 

Background: 

- flow 1.0.5
- vaadin-combo-box-flow 1.0.7
- the combobox is declared in a polymer template and used server side `@Id("comboBox")`

**Comment by web-padawan** [comment]
Closing as inactive and because the bug is already fixed and there are different options listed in the above comment.
