### ISSUE TITLE
ItemLabelGenerator doesn't work with IconRenderer

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box#952]
If you have an IconRenderer and an ItemLabelGenerator as follows:

```java
ComboBox<Song> comboBox = new ComboBox<>();
comboBox.setRenderer(new IconRenderer<>(song -> VaadinIcon.ACADEMY_CAP.create()));
List<Song> listOfSongs = createListOfSongs();
comboBox.setItems(listOfSongs);
comboBox.setItemLabelGenerator(Song::getName);
```
I'd expect to see the icon and the `Song`:s `name` in the ComboBox. Currently it shows the Icon and the Song's toString instead:
![image](https://user-images.githubusercontent.com/15027701/41418418-5198263e-6ff8-11e8-8556-206e7437ec84.png)

**Comment by tomivirkki** [comment]
This works as expected

`setItemLabelGenerator` API documentation says that `When the setRenderer(Renderer) is used, the ItemLabelGenerator is only used to show the selected item label.`, and that is what happens here = you only see the generated label for the _selected_ item in the combo box's text field ("A V Club Disagrees")

How the items in the overlay are rendered is then up to the `Renderer` implementation. In the case of `IconRenderer`, you can pass an `ItemLabelGenerator` as the second argument and that will affect how the `IconRenderer` renders the labels. `comboBox.setRenderer(new IconRenderer<>(song -> VaadinIcon.ACADEMY_CAP.create(), Song::getName));`
