### ISSUE TITLE
Mouse scroll doesn't fetch new items

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-combo-box#957]
### Description
When `FetchCallback` without `CountCallback` is set to the `ComboBox` and the suggestion popup is scrolled to the end and then scrolled some more with the mouse wheel, some items are not fetched/blank items are shown. The problem fixes itself when scrolling some more.

### Expected outcome
The items should be shown.

### Actual outcome
Empty lines are shown in the combobox.

### Live Demo
I'll post a video recording.

### Steps to reproduce
1. Run the example app
2. Drag the scroll bar and try to "scroll to the end" once. You'll probably end around the item 800. That's fine.
3. Scroll very slightly with the mouse wheel.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

Vaadin 18.0.0.alpha1, combo box 5.4.1
[video.zip](https://github.com/vaadin/vaadin-combo-box/files/5369945/video.zip)

**Comment by mvysny** [comment]
Example app

[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-combo-box/files/5369955/skeleton-starter-flow.zip)

**Comment by werwolfberlin** [comment]
Can confirm same behavior for latest MS Edge version.

**Comment by mshabarov** [comment]
I also experienced this issue. It only appears in recently introduced 'undefined size' lazy loading.

**Comment by mshabarov** [comment]
I'm not able to reproduce this issue with the attached project, but with the 'Custom Item Count Estimate And Increase' demo http://localhost:8080/vaadin-combo-box/lazy-loading.

The blanks items and the loading indicator appear when the `__requestItemByIndex(item, index)` in `vaadin-combo-box-dropdown-wrapper.html` triggers non-sequential index to the, i.e. `145`, `146`, `147` -> suddenly `122`. This leads to the non-sequential active pages in `dataProvider` function: `13`, `14`, `15` -> `12` and causes a reset of the cached pages and breaks the normal fetching. 

So, there might be a bug in old position restoring function `_restoreScrollerPosition(items)`, which restores the scroller's position after size update.
