### ISSUE TITLE
Polymer 3 conversion and TS event type definitions

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-combo-box#974]
### Description

- convert codebase to Polymer 3
- use `registerStyles` API instead of `<dom-module theme-for>`
- add events type definitions

**Comment by moderndeveloperllc** [comment]
@web-padawan Not going to go to LitElement, or has Vaadin roadmap changed?

**Comment by web-padawan** [comment]
The ultimate goal to migrate components to LitElement is still valid. However that will be a long lasting effort.
Also, now when the next `lit-html` version is coming, we would like to wait for it to become stable.

For now, we are converting the components to Polymer 3 and update tests to use `@web/test-runner`.
The next step would be removing `<template>` and adding helpers for using `vaadin-dialog` etc with LitElement.

Once those changes are done, we will continue migrating to LitElement. We will also try to do all the breaking changes before next Vaadin LTS release, so that changing the base class used internally would be possible in minor releases.
